// Code generated by Kitex v0.15.2. DO NOT EDIT.

package userservice

import (
	user "MengGoods/kitex_gen/user"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newUserServiceRegisterArgs,
		newUserServiceRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newUserServiceLoginArgs,
		newUserServiceLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AddAddress": kitex.NewMethodInfo(
		addAddressHandler,
		newUserServiceAddAddressArgs,
		newUserServiceAddAddressResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetAddresses": kitex.NewMethodInfo(
		getAddressesHandler,
		newUserServiceGetAddressesArgs,
		newUserServiceGetAddressesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetAddress": kitex.NewMethodInfo(
		getAddressHandler,
		newUserServiceGetAddressArgs,
		newUserServiceGetAddressResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"BanUser": kitex.NewMethodInfo(
		banUserHandler,
		newUserServiceBanUserArgs,
		newUserServiceBanUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UnBanUser": kitex.NewMethodInfo(
		unBanUserHandler,
		newUserServiceUnBanUserArgs,
		newUserServiceUnBanUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SetAdmin": kitex.NewMethodInfo(
		setAdminHandler,
		newUserServiceSetAdminArgs,
		newUserServiceSetAdminResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserInfo": kitex.NewMethodInfo(
		getUserInfoHandler,
		newUserServiceGetUserInfoArgs,
		newUserServiceGetUserInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"logout": kitex.NewMethodInfo(
		logoutHandler,
		newUserServiceLogoutArgs,
		newUserServiceLogoutResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SendCode": kitex.NewMethodInfo(
		sendCodeHandler,
		newUserServiceSendCodeArgs,
		newUserServiceSendCodeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ResetPwd": kitex.NewMethodInfo(
		resetPwdHandler,
		newUserServiceResetPwdArgs,
		newUserServiceResetPwdResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UploadAvatar": kitex.NewMethodInfo(
		uploadAvatarHandler,
		newUserServiceUploadAvatarArgs,
		newUserServiceUploadAvatarResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	userServiceServiceInfo                = NewServiceInfo()
	userServiceServiceInfoForClient       = NewServiceInfoForClient()
	userServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*user.UserService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "user",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceRegisterArgs)
	realResult := result.(*user.UserServiceRegisterResult)
	success, err := handler.(user.UserService).Register(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceRegisterArgs() interface{} {
	return user.NewUserServiceRegisterArgs()
}

func newUserServiceRegisterResult() interface{} {
	return user.NewUserServiceRegisterResult()
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceLoginArgs)
	realResult := result.(*user.UserServiceLoginResult)
	success, err := handler.(user.UserService).Login(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceLoginArgs() interface{} {
	return user.NewUserServiceLoginArgs()
}

func newUserServiceLoginResult() interface{} {
	return user.NewUserServiceLoginResult()
}

func addAddressHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceAddAddressArgs)
	realResult := result.(*user.UserServiceAddAddressResult)
	success, err := handler.(user.UserService).AddAddress(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceAddAddressArgs() interface{} {
	return user.NewUserServiceAddAddressArgs()
}

func newUserServiceAddAddressResult() interface{} {
	return user.NewUserServiceAddAddressResult()
}

func getAddressesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceGetAddressesArgs)
	realResult := result.(*user.UserServiceGetAddressesResult)
	success, err := handler.(user.UserService).GetAddresses(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetAddressesArgs() interface{} {
	return user.NewUserServiceGetAddressesArgs()
}

func newUserServiceGetAddressesResult() interface{} {
	return user.NewUserServiceGetAddressesResult()
}

func getAddressHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceGetAddressArgs)
	realResult := result.(*user.UserServiceGetAddressResult)
	success, err := handler.(user.UserService).GetAddress(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetAddressArgs() interface{} {
	return user.NewUserServiceGetAddressArgs()
}

func newUserServiceGetAddressResult() interface{} {
	return user.NewUserServiceGetAddressResult()
}

func banUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceBanUserArgs)
	realResult := result.(*user.UserServiceBanUserResult)
	success, err := handler.(user.UserService).BanUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceBanUserArgs() interface{} {
	return user.NewUserServiceBanUserArgs()
}

func newUserServiceBanUserResult() interface{} {
	return user.NewUserServiceBanUserResult()
}

func unBanUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceUnBanUserArgs)
	realResult := result.(*user.UserServiceUnBanUserResult)
	success, err := handler.(user.UserService).UnBanUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceUnBanUserArgs() interface{} {
	return user.NewUserServiceUnBanUserArgs()
}

func newUserServiceUnBanUserResult() interface{} {
	return user.NewUserServiceUnBanUserResult()
}

func setAdminHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceSetAdminArgs)
	realResult := result.(*user.UserServiceSetAdminResult)
	success, err := handler.(user.UserService).SetAdmin(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceSetAdminArgs() interface{} {
	return user.NewUserServiceSetAdminArgs()
}

func newUserServiceSetAdminResult() interface{} {
	return user.NewUserServiceSetAdminResult()
}

func getUserInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceGetUserInfoArgs)
	realResult := result.(*user.UserServiceGetUserInfoResult)
	success, err := handler.(user.UserService).GetUserInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetUserInfoArgs() interface{} {
	return user.NewUserServiceGetUserInfoArgs()
}

func newUserServiceGetUserInfoResult() interface{} {
	return user.NewUserServiceGetUserInfoResult()
}

func logoutHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceLogoutArgs)
	realResult := result.(*user.UserServiceLogoutResult)
	success, err := handler.(user.UserService).Logout(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceLogoutArgs() interface{} {
	return user.NewUserServiceLogoutArgs()
}

func newUserServiceLogoutResult() interface{} {
	return user.NewUserServiceLogoutResult()
}

func sendCodeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceSendCodeArgs)
	realResult := result.(*user.UserServiceSendCodeResult)
	success, err := handler.(user.UserService).SendCode(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceSendCodeArgs() interface{} {
	return user.NewUserServiceSendCodeArgs()
}

func newUserServiceSendCodeResult() interface{} {
	return user.NewUserServiceSendCodeResult()
}

func resetPwdHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceResetPwdArgs)
	realResult := result.(*user.UserServiceResetPwdResult)
	success, err := handler.(user.UserService).ResetPwd(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceResetPwdArgs() interface{} {
	return user.NewUserServiceResetPwdArgs()
}

func newUserServiceResetPwdResult() interface{} {
	return user.NewUserServiceResetPwdResult()
}

func uploadAvatarHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceUploadAvatarArgs)
	realResult := result.(*user.UserServiceUploadAvatarResult)
	success, err := handler.(user.UserService).UploadAvatar(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceUploadAvatarArgs() interface{} {
	return user.NewUserServiceUploadAvatarArgs()
}

func newUserServiceUploadAvatarResult() interface{} {
	return user.NewUserServiceUploadAvatarResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Register(ctx context.Context, req *user.RegisterReq) (r *user.RegisterResp, err error) {
	var _args user.UserServiceRegisterArgs
	_args.Req = req
	var _result user.UserServiceRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Login(ctx context.Context, req *user.LoginReq) (r *user.LoginResp, err error) {
	var _args user.UserServiceLoginArgs
	_args.Req = req
	var _result user.UserServiceLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddAddress(ctx context.Context, req *user.AddAddressReq) (r *user.AddAddressResp, err error) {
	var _args user.UserServiceAddAddressArgs
	_args.Req = req
	var _result user.UserServiceAddAddressResult
	if err = p.c.Call(ctx, "AddAddress", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetAddresses(ctx context.Context, req *user.GetAddressesReq) (r *user.GetAddressesResp, err error) {
	var _args user.UserServiceGetAddressesArgs
	_args.Req = req
	var _result user.UserServiceGetAddressesResult
	if err = p.c.Call(ctx, "GetAddresses", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetAddress(ctx context.Context, req *user.GetAddressReq) (r *user.GetAddressResp, err error) {
	var _args user.UserServiceGetAddressArgs
	_args.Req = req
	var _result user.UserServiceGetAddressResult
	if err = p.c.Call(ctx, "GetAddress", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BanUser(ctx context.Context, req *user.BanUserReq) (r *user.BanUserResp, err error) {
	var _args user.UserServiceBanUserArgs
	_args.Req = req
	var _result user.UserServiceBanUserResult
	if err = p.c.Call(ctx, "BanUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UnBanUser(ctx context.Context, req *user.UnBanUserReq) (r *user.UnBanUserResp, err error) {
	var _args user.UserServiceUnBanUserArgs
	_args.Req = req
	var _result user.UserServiceUnBanUserResult
	if err = p.c.Call(ctx, "UnBanUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SetAdmin(ctx context.Context, req *user.SetAdminReq) (r *user.SetAdminResp, err error) {
	var _args user.UserServiceSetAdminArgs
	_args.Req = req
	var _result user.UserServiceSetAdminResult
	if err = p.c.Call(ctx, "SetAdmin", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserInfo(ctx context.Context, req *user.GetUserInfoReq) (r *user.GetUserInfoResp, err error) {
	var _args user.UserServiceGetUserInfoArgs
	_args.Req = req
	var _result user.UserServiceGetUserInfoResult
	if err = p.c.Call(ctx, "GetUserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Logout(ctx context.Context, req *user.LogoutReq) (r *user.LogoutResp, err error) {
	var _args user.UserServiceLogoutArgs
	_args.Req = req
	var _result user.UserServiceLogoutResult
	if err = p.c.Call(ctx, "logout", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SendCode(ctx context.Context, req *user.SendCodeReq) (r *user.SendCodeResp, err error) {
	var _args user.UserServiceSendCodeArgs
	_args.Req = req
	var _result user.UserServiceSendCodeResult
	if err = p.c.Call(ctx, "SendCode", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ResetPwd(ctx context.Context, req *user.ResetPwdReq) (r *user.ResetPwdResp, err error) {
	var _args user.UserServiceResetPwdArgs
	_args.Req = req
	var _result user.UserServiceResetPwdResult
	if err = p.c.Call(ctx, "ResetPwd", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UploadAvatar(ctx context.Context, req *user.UploadAvatarReq) (r *user.UploadAvatarResp, err error) {
	var _args user.UserServiceUploadAvatarArgs
	_args.Req = req
	var _result user.UserServiceUploadAvatarResult
	if err = p.c.Call(ctx, "UploadAvatar", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
