// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package order

import (
	"MengGoods/kitex_gen/model"
	"context"
	"fmt"
)

type CreateOrderReq struct {
	Items     []*model.OrderItem `thrift:"items,1" frugal:"1,default,list<model.OrderItem>" json:"items"`
	CouponId  int64              `thrift:"couponId,2" frugal:"2,default,i64" json:"couponId"`
	AddressId int64              `thrift:"addressId,3" frugal:"3,default,i64" json:"addressId"`
}

func NewCreateOrderReq() *CreateOrderReq {
	return &CreateOrderReq{}
}

func (p *CreateOrderReq) InitDefault() {
}

func (p *CreateOrderReq) GetItems() (v []*model.OrderItem) {
	return p.Items
}

func (p *CreateOrderReq) GetCouponId() (v int64) {
	return p.CouponId
}

func (p *CreateOrderReq) GetAddressId() (v int64) {
	return p.AddressId
}
func (p *CreateOrderReq) SetItems(val []*model.OrderItem) {
	p.Items = val
}
func (p *CreateOrderReq) SetCouponId(val int64) {
	p.CouponId = val
}
func (p *CreateOrderReq) SetAddressId(val int64) {
	p.AddressId = val
}

func (p *CreateOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateOrderReq(%+v)", *p)
}

var fieldIDToName_CreateOrderReq = map[int16]string{
	1: "items",
	2: "couponId",
	3: "addressId",
}

type CreateOrderResp struct {
	Base    *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
	OrderId int64           `thrift:"orderId,2" frugal:"2,default,i64" json:"orderId"`
}

func NewCreateOrderResp() *CreateOrderResp {
	return &CreateOrderResp{}
}

func (p *CreateOrderResp) InitDefault() {
}

var CreateOrderResp_Base_DEFAULT *model.BaseResp

func (p *CreateOrderResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return CreateOrderResp_Base_DEFAULT
	}
	return p.Base
}

func (p *CreateOrderResp) GetOrderId() (v int64) {
	return p.OrderId
}
func (p *CreateOrderResp) SetBase(val *model.BaseResp) {
	p.Base = val
}
func (p *CreateOrderResp) SetOrderId(val int64) {
	p.OrderId = val
}

func (p *CreateOrderResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *CreateOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateOrderResp(%+v)", *p)
}

var fieldIDToName_CreateOrderResp = map[int16]string{
	1: "base",
	2: "orderId",
}

type ViewOrderByIdReq struct {
	OrderId int64 `thrift:"orderId,1" frugal:"1,default,i64" json:"orderId"`
}

func NewViewOrderByIdReq() *ViewOrderByIdReq {
	return &ViewOrderByIdReq{}
}

func (p *ViewOrderByIdReq) InitDefault() {
}

func (p *ViewOrderByIdReq) GetOrderId() (v int64) {
	return p.OrderId
}
func (p *ViewOrderByIdReq) SetOrderId(val int64) {
	p.OrderId = val
}

func (p *ViewOrderByIdReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ViewOrderByIdReq(%+v)", *p)
}

var fieldIDToName_ViewOrderByIdReq = map[int16]string{
	1: "orderId",
}

type ViewOrderByIdResp struct {
	Base  *model.BaseResp       `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
	Order *model.OrderWithItems `thrift:"order,2" frugal:"2,default,model.OrderWithItems" json:"order"`
}

func NewViewOrderByIdResp() *ViewOrderByIdResp {
	return &ViewOrderByIdResp{}
}

func (p *ViewOrderByIdResp) InitDefault() {
}

var ViewOrderByIdResp_Base_DEFAULT *model.BaseResp

func (p *ViewOrderByIdResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return ViewOrderByIdResp_Base_DEFAULT
	}
	return p.Base
}

var ViewOrderByIdResp_Order_DEFAULT *model.OrderWithItems

func (p *ViewOrderByIdResp) GetOrder() (v *model.OrderWithItems) {
	if !p.IsSetOrder() {
		return ViewOrderByIdResp_Order_DEFAULT
	}
	return p.Order
}
func (p *ViewOrderByIdResp) SetBase(val *model.BaseResp) {
	p.Base = val
}
func (p *ViewOrderByIdResp) SetOrder(val *model.OrderWithItems) {
	p.Order = val
}

func (p *ViewOrderByIdResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *ViewOrderByIdResp) IsSetOrder() bool {
	return p.Order != nil
}

func (p *ViewOrderByIdResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ViewOrderByIdResp(%+v)", *p)
}

var fieldIDToName_ViewOrderByIdResp = map[int16]string{
	1: "base",
	2: "order",
}

type ViewOrderListReq struct {
	Status   int64 `thrift:"status,1" frugal:"1,default,i64" json:"status"`
	PageNum  int64 `thrift:"pageNum,2" frugal:"2,default,i64" json:"pageNum"`
	PageSize int64 `thrift:"pageSize,3" frugal:"3,default,i64" json:"pageSize"`
}

func NewViewOrderListReq() *ViewOrderListReq {
	return &ViewOrderListReq{}
}

func (p *ViewOrderListReq) InitDefault() {
}

func (p *ViewOrderListReq) GetStatus() (v int64) {
	return p.Status
}

func (p *ViewOrderListReq) GetPageNum() (v int64) {
	return p.PageNum
}

func (p *ViewOrderListReq) GetPageSize() (v int64) {
	return p.PageSize
}
func (p *ViewOrderListReq) SetStatus(val int64) {
	p.Status = val
}
func (p *ViewOrderListReq) SetPageNum(val int64) {
	p.PageNum = val
}
func (p *ViewOrderListReq) SetPageSize(val int64) {
	p.PageSize = val
}

func (p *ViewOrderListReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ViewOrderListReq(%+v)", *p)
}

var fieldIDToName_ViewOrderListReq = map[int16]string{
	1: "status",
	2: "pageNum",
	3: "pageSize",
}

type ViewOrderListResp struct {
	Base      *model.BaseResp    `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
	OrderList []*model.OrderInfo `thrift:"orderList,2" frugal:"2,default,list<model.OrderInfo>" json:"orderList"`
	Total     int64              `thrift:"total,3" frugal:"3,default,i64" json:"total"`
}

func NewViewOrderListResp() *ViewOrderListResp {
	return &ViewOrderListResp{}
}

func (p *ViewOrderListResp) InitDefault() {
}

var ViewOrderListResp_Base_DEFAULT *model.BaseResp

func (p *ViewOrderListResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return ViewOrderListResp_Base_DEFAULT
	}
	return p.Base
}

func (p *ViewOrderListResp) GetOrderList() (v []*model.OrderInfo) {
	return p.OrderList
}

func (p *ViewOrderListResp) GetTotal() (v int64) {
	return p.Total
}
func (p *ViewOrderListResp) SetBase(val *model.BaseResp) {
	p.Base = val
}
func (p *ViewOrderListResp) SetOrderList(val []*model.OrderInfo) {
	p.OrderList = val
}
func (p *ViewOrderListResp) SetTotal(val int64) {
	p.Total = val
}

func (p *ViewOrderListResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *ViewOrderListResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ViewOrderListResp(%+v)", *p)
}

var fieldIDToName_ViewOrderListResp = map[int16]string{
	1: "base",
	2: "orderList",
	3: "total",
}

type ConfirmReceiptOrderReq struct {
	OrderId int64 `thrift:"orderId,1" frugal:"1,default,i64" json:"orderId"`
}

func NewConfirmReceiptOrderReq() *ConfirmReceiptOrderReq {
	return &ConfirmReceiptOrderReq{}
}

func (p *ConfirmReceiptOrderReq) InitDefault() {
}

func (p *ConfirmReceiptOrderReq) GetOrderId() (v int64) {
	return p.OrderId
}
func (p *ConfirmReceiptOrderReq) SetOrderId(val int64) {
	p.OrderId = val
}

func (p *ConfirmReceiptOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ConfirmReceiptOrderReq(%+v)", *p)
}

var fieldIDToName_ConfirmReceiptOrderReq = map[int16]string{
	1: "orderId",
}

type ConfirmReceiptOrderResp struct {
	Base *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
}

func NewConfirmReceiptOrderResp() *ConfirmReceiptOrderResp {
	return &ConfirmReceiptOrderResp{}
}

func (p *ConfirmReceiptOrderResp) InitDefault() {
}

var ConfirmReceiptOrderResp_Base_DEFAULT *model.BaseResp

func (p *ConfirmReceiptOrderResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return ConfirmReceiptOrderResp_Base_DEFAULT
	}
	return p.Base
}
func (p *ConfirmReceiptOrderResp) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *ConfirmReceiptOrderResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *ConfirmReceiptOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ConfirmReceiptOrderResp(%+v)", *p)
}

var fieldIDToName_ConfirmReceiptOrderResp = map[int16]string{
	1: "base",
}

type CancelOrderReq struct {
	OrderId      int64  `thrift:"orderId,1" frugal:"1,default,i64" json:"orderId"`
	CancelReason string `thrift:"cancelReason,2" frugal:"2,default,string" json:"cancelReason"`
}

func NewCancelOrderReq() *CancelOrderReq {
	return &CancelOrderReq{}
}

func (p *CancelOrderReq) InitDefault() {
}

func (p *CancelOrderReq) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *CancelOrderReq) GetCancelReason() (v string) {
	return p.CancelReason
}
func (p *CancelOrderReq) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *CancelOrderReq) SetCancelReason(val string) {
	p.CancelReason = val
}

func (p *CancelOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CancelOrderReq(%+v)", *p)
}

var fieldIDToName_CancelOrderReq = map[int16]string{
	1: "orderId",
	2: "cancelReason",
}

type CancelOrderResp struct {
	Base *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
}

func NewCancelOrderResp() *CancelOrderResp {
	return &CancelOrderResp{}
}

func (p *CancelOrderResp) InitDefault() {
}

var CancelOrderResp_Base_DEFAULT *model.BaseResp

func (p *CancelOrderResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return CancelOrderResp_Base_DEFAULT
	}
	return p.Base
}
func (p *CancelOrderResp) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *CancelOrderResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *CancelOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CancelOrderResp(%+v)", *p)
}

var fieldIDToName_CancelOrderResp = map[int16]string{
	1: "base",
}

type MarkOrderPaidReq struct {
	OrderId int64 `thrift:"orderId,1" frugal:"1,default,i64" json:"orderId"`
}

func NewMarkOrderPaidReq() *MarkOrderPaidReq {
	return &MarkOrderPaidReq{}
}

func (p *MarkOrderPaidReq) InitDefault() {
}

func (p *MarkOrderPaidReq) GetOrderId() (v int64) {
	return p.OrderId
}
func (p *MarkOrderPaidReq) SetOrderId(val int64) {
	p.OrderId = val
}

func (p *MarkOrderPaidReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MarkOrderPaidReq(%+v)", *p)
}

var fieldIDToName_MarkOrderPaidReq = map[int16]string{
	1: "orderId",
}

type MarkOrderPaidResp struct {
	Base *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
}

func NewMarkOrderPaidResp() *MarkOrderPaidResp {
	return &MarkOrderPaidResp{}
}

func (p *MarkOrderPaidResp) InitDefault() {
}

var MarkOrderPaidResp_Base_DEFAULT *model.BaseResp

func (p *MarkOrderPaidResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return MarkOrderPaidResp_Base_DEFAULT
	}
	return p.Base
}
func (p *MarkOrderPaidResp) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *MarkOrderPaidResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *MarkOrderPaidResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MarkOrderPaidResp(%+v)", *p)
}

var fieldIDToName_MarkOrderPaidResp = map[int16]string{
	1: "base",
}

type GetPayAmountReq struct {
	OrderId int64 `thrift:"orderId,1" frugal:"1,default,i64" json:"orderId"`
}

func NewGetPayAmountReq() *GetPayAmountReq {
	return &GetPayAmountReq{}
}

func (p *GetPayAmountReq) InitDefault() {
}

func (p *GetPayAmountReq) GetOrderId() (v int64) {
	return p.OrderId
}
func (p *GetPayAmountReq) SetOrderId(val int64) {
	p.OrderId = val
}

func (p *GetPayAmountReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPayAmountReq(%+v)", *p)
}

var fieldIDToName_GetPayAmountReq = map[int16]string{
	1: "orderId",
}

type GetPayAmountResp struct {
	Base   *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
	Amount int64           `thrift:"amount,2" frugal:"2,default,i64" json:"amount"`
}

func NewGetPayAmountResp() *GetPayAmountResp {
	return &GetPayAmountResp{}
}

func (p *GetPayAmountResp) InitDefault() {
}

var GetPayAmountResp_Base_DEFAULT *model.BaseResp

func (p *GetPayAmountResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return GetPayAmountResp_Base_DEFAULT
	}
	return p.Base
}

func (p *GetPayAmountResp) GetAmount() (v int64) {
	return p.Amount
}
func (p *GetPayAmountResp) SetBase(val *model.BaseResp) {
	p.Base = val
}
func (p *GetPayAmountResp) SetAmount(val int64) {
	p.Amount = val
}

func (p *GetPayAmountResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetPayAmountResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPayAmountResp(%+v)", *p)
}

var fieldIDToName_GetPayAmountResp = map[int16]string{
	1: "base",
	2: "amount",
}

type OrderService interface {
	CreateOrder(ctx context.Context, req *CreateOrderReq) (r *CreateOrderResp, err error)

	ViewOrderById(ctx context.Context, req *ViewOrderByIdReq) (r *ViewOrderByIdResp, err error)

	ViewOrderList(ctx context.Context, req *ViewOrderListReq) (r *ViewOrderListResp, err error)

	CancelOrder(ctx context.Context, req *CancelOrderReq) (r *CancelOrderResp, err error)

	ConfirmReceiptOrder(ctx context.Context, req *ConfirmReceiptOrderReq) (r *ConfirmReceiptOrderResp, err error)

	MarkOrderPaid(ctx context.Context, req *MarkOrderPaidReq) (r *MarkOrderPaidResp, err error)

	GetPayAmount(ctx context.Context, req *GetPayAmountReq) (r *GetPayAmountResp, err error)
}

type OrderServiceCreateOrderArgs struct {
	Req *CreateOrderReq `thrift:"req,1" frugal:"1,default,CreateOrderReq" json:"req"`
}

func NewOrderServiceCreateOrderArgs() *OrderServiceCreateOrderArgs {
	return &OrderServiceCreateOrderArgs{}
}

func (p *OrderServiceCreateOrderArgs) InitDefault() {
}

var OrderServiceCreateOrderArgs_Req_DEFAULT *CreateOrderReq

func (p *OrderServiceCreateOrderArgs) GetReq() (v *CreateOrderReq) {
	if !p.IsSetReq() {
		return OrderServiceCreateOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceCreateOrderArgs) SetReq(val *CreateOrderReq) {
	p.Req = val
}

func (p *OrderServiceCreateOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceCreateOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCreateOrderArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceCreateOrderArgs = map[int16]string{
	1: "req",
}

type OrderServiceCreateOrderResult struct {
	Success *CreateOrderResp `thrift:"success,0,optional" frugal:"0,optional,CreateOrderResp" json:"success,omitempty"`
}

func NewOrderServiceCreateOrderResult() *OrderServiceCreateOrderResult {
	return &OrderServiceCreateOrderResult{}
}

func (p *OrderServiceCreateOrderResult) InitDefault() {
}

var OrderServiceCreateOrderResult_Success_DEFAULT *CreateOrderResp

func (p *OrderServiceCreateOrderResult) GetSuccess() (v *CreateOrderResp) {
	if !p.IsSetSuccess() {
		return OrderServiceCreateOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceCreateOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateOrderResp)
}

func (p *OrderServiceCreateOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceCreateOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCreateOrderResult(%+v)", *p)
}

var fieldIDToName_OrderServiceCreateOrderResult = map[int16]string{
	0: "success",
}

type OrderServiceViewOrderByIdArgs struct {
	Req *ViewOrderByIdReq `thrift:"req,1" frugal:"1,default,ViewOrderByIdReq" json:"req"`
}

func NewOrderServiceViewOrderByIdArgs() *OrderServiceViewOrderByIdArgs {
	return &OrderServiceViewOrderByIdArgs{}
}

func (p *OrderServiceViewOrderByIdArgs) InitDefault() {
}

var OrderServiceViewOrderByIdArgs_Req_DEFAULT *ViewOrderByIdReq

func (p *OrderServiceViewOrderByIdArgs) GetReq() (v *ViewOrderByIdReq) {
	if !p.IsSetReq() {
		return OrderServiceViewOrderByIdArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceViewOrderByIdArgs) SetReq(val *ViewOrderByIdReq) {
	p.Req = val
}

func (p *OrderServiceViewOrderByIdArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceViewOrderByIdArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceViewOrderByIdArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceViewOrderByIdArgs = map[int16]string{
	1: "req",
}

type OrderServiceViewOrderByIdResult struct {
	Success *ViewOrderByIdResp `thrift:"success,0,optional" frugal:"0,optional,ViewOrderByIdResp" json:"success,omitempty"`
}

func NewOrderServiceViewOrderByIdResult() *OrderServiceViewOrderByIdResult {
	return &OrderServiceViewOrderByIdResult{}
}

func (p *OrderServiceViewOrderByIdResult) InitDefault() {
}

var OrderServiceViewOrderByIdResult_Success_DEFAULT *ViewOrderByIdResp

func (p *OrderServiceViewOrderByIdResult) GetSuccess() (v *ViewOrderByIdResp) {
	if !p.IsSetSuccess() {
		return OrderServiceViewOrderByIdResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceViewOrderByIdResult) SetSuccess(x interface{}) {
	p.Success = x.(*ViewOrderByIdResp)
}

func (p *OrderServiceViewOrderByIdResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceViewOrderByIdResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceViewOrderByIdResult(%+v)", *p)
}

var fieldIDToName_OrderServiceViewOrderByIdResult = map[int16]string{
	0: "success",
}

type OrderServiceViewOrderListArgs struct {
	Req *ViewOrderListReq `thrift:"req,1" frugal:"1,default,ViewOrderListReq" json:"req"`
}

func NewOrderServiceViewOrderListArgs() *OrderServiceViewOrderListArgs {
	return &OrderServiceViewOrderListArgs{}
}

func (p *OrderServiceViewOrderListArgs) InitDefault() {
}

var OrderServiceViewOrderListArgs_Req_DEFAULT *ViewOrderListReq

func (p *OrderServiceViewOrderListArgs) GetReq() (v *ViewOrderListReq) {
	if !p.IsSetReq() {
		return OrderServiceViewOrderListArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceViewOrderListArgs) SetReq(val *ViewOrderListReq) {
	p.Req = val
}

func (p *OrderServiceViewOrderListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceViewOrderListArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceViewOrderListArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceViewOrderListArgs = map[int16]string{
	1: "req",
}

type OrderServiceViewOrderListResult struct {
	Success *ViewOrderListResp `thrift:"success,0,optional" frugal:"0,optional,ViewOrderListResp" json:"success,omitempty"`
}

func NewOrderServiceViewOrderListResult() *OrderServiceViewOrderListResult {
	return &OrderServiceViewOrderListResult{}
}

func (p *OrderServiceViewOrderListResult) InitDefault() {
}

var OrderServiceViewOrderListResult_Success_DEFAULT *ViewOrderListResp

func (p *OrderServiceViewOrderListResult) GetSuccess() (v *ViewOrderListResp) {
	if !p.IsSetSuccess() {
		return OrderServiceViewOrderListResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceViewOrderListResult) SetSuccess(x interface{}) {
	p.Success = x.(*ViewOrderListResp)
}

func (p *OrderServiceViewOrderListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceViewOrderListResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceViewOrderListResult(%+v)", *p)
}

var fieldIDToName_OrderServiceViewOrderListResult = map[int16]string{
	0: "success",
}

type OrderServiceCancelOrderArgs struct {
	Req *CancelOrderReq `thrift:"req,1" frugal:"1,default,CancelOrderReq" json:"req"`
}

func NewOrderServiceCancelOrderArgs() *OrderServiceCancelOrderArgs {
	return &OrderServiceCancelOrderArgs{}
}

func (p *OrderServiceCancelOrderArgs) InitDefault() {
}

var OrderServiceCancelOrderArgs_Req_DEFAULT *CancelOrderReq

func (p *OrderServiceCancelOrderArgs) GetReq() (v *CancelOrderReq) {
	if !p.IsSetReq() {
		return OrderServiceCancelOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceCancelOrderArgs) SetReq(val *CancelOrderReq) {
	p.Req = val
}

func (p *OrderServiceCancelOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceCancelOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCancelOrderArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceCancelOrderArgs = map[int16]string{
	1: "req",
}

type OrderServiceCancelOrderResult struct {
	Success *CancelOrderResp `thrift:"success,0,optional" frugal:"0,optional,CancelOrderResp" json:"success,omitempty"`
}

func NewOrderServiceCancelOrderResult() *OrderServiceCancelOrderResult {
	return &OrderServiceCancelOrderResult{}
}

func (p *OrderServiceCancelOrderResult) InitDefault() {
}

var OrderServiceCancelOrderResult_Success_DEFAULT *CancelOrderResp

func (p *OrderServiceCancelOrderResult) GetSuccess() (v *CancelOrderResp) {
	if !p.IsSetSuccess() {
		return OrderServiceCancelOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceCancelOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*CancelOrderResp)
}

func (p *OrderServiceCancelOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceCancelOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCancelOrderResult(%+v)", *p)
}

var fieldIDToName_OrderServiceCancelOrderResult = map[int16]string{
	0: "success",
}

type OrderServiceConfirmReceiptOrderArgs struct {
	Req *ConfirmReceiptOrderReq `thrift:"req,1" frugal:"1,default,ConfirmReceiptOrderReq" json:"req"`
}

func NewOrderServiceConfirmReceiptOrderArgs() *OrderServiceConfirmReceiptOrderArgs {
	return &OrderServiceConfirmReceiptOrderArgs{}
}

func (p *OrderServiceConfirmReceiptOrderArgs) InitDefault() {
}

var OrderServiceConfirmReceiptOrderArgs_Req_DEFAULT *ConfirmReceiptOrderReq

func (p *OrderServiceConfirmReceiptOrderArgs) GetReq() (v *ConfirmReceiptOrderReq) {
	if !p.IsSetReq() {
		return OrderServiceConfirmReceiptOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceConfirmReceiptOrderArgs) SetReq(val *ConfirmReceiptOrderReq) {
	p.Req = val
}

func (p *OrderServiceConfirmReceiptOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceConfirmReceiptOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceConfirmReceiptOrderArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceConfirmReceiptOrderArgs = map[int16]string{
	1: "req",
}

type OrderServiceConfirmReceiptOrderResult struct {
	Success *ConfirmReceiptOrderResp `thrift:"success,0,optional" frugal:"0,optional,ConfirmReceiptOrderResp" json:"success,omitempty"`
}

func NewOrderServiceConfirmReceiptOrderResult() *OrderServiceConfirmReceiptOrderResult {
	return &OrderServiceConfirmReceiptOrderResult{}
}

func (p *OrderServiceConfirmReceiptOrderResult) InitDefault() {
}

var OrderServiceConfirmReceiptOrderResult_Success_DEFAULT *ConfirmReceiptOrderResp

func (p *OrderServiceConfirmReceiptOrderResult) GetSuccess() (v *ConfirmReceiptOrderResp) {
	if !p.IsSetSuccess() {
		return OrderServiceConfirmReceiptOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceConfirmReceiptOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*ConfirmReceiptOrderResp)
}

func (p *OrderServiceConfirmReceiptOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceConfirmReceiptOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceConfirmReceiptOrderResult(%+v)", *p)
}

var fieldIDToName_OrderServiceConfirmReceiptOrderResult = map[int16]string{
	0: "success",
}

type OrderServiceMarkOrderPaidArgs struct {
	Req *MarkOrderPaidReq `thrift:"req,1" frugal:"1,default,MarkOrderPaidReq" json:"req"`
}

func NewOrderServiceMarkOrderPaidArgs() *OrderServiceMarkOrderPaidArgs {
	return &OrderServiceMarkOrderPaidArgs{}
}

func (p *OrderServiceMarkOrderPaidArgs) InitDefault() {
}

var OrderServiceMarkOrderPaidArgs_Req_DEFAULT *MarkOrderPaidReq

func (p *OrderServiceMarkOrderPaidArgs) GetReq() (v *MarkOrderPaidReq) {
	if !p.IsSetReq() {
		return OrderServiceMarkOrderPaidArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceMarkOrderPaidArgs) SetReq(val *MarkOrderPaidReq) {
	p.Req = val
}

func (p *OrderServiceMarkOrderPaidArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceMarkOrderPaidArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceMarkOrderPaidArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceMarkOrderPaidArgs = map[int16]string{
	1: "req",
}

type OrderServiceMarkOrderPaidResult struct {
	Success *MarkOrderPaidResp `thrift:"success,0,optional" frugal:"0,optional,MarkOrderPaidResp" json:"success,omitempty"`
}

func NewOrderServiceMarkOrderPaidResult() *OrderServiceMarkOrderPaidResult {
	return &OrderServiceMarkOrderPaidResult{}
}

func (p *OrderServiceMarkOrderPaidResult) InitDefault() {
}

var OrderServiceMarkOrderPaidResult_Success_DEFAULT *MarkOrderPaidResp

func (p *OrderServiceMarkOrderPaidResult) GetSuccess() (v *MarkOrderPaidResp) {
	if !p.IsSetSuccess() {
		return OrderServiceMarkOrderPaidResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceMarkOrderPaidResult) SetSuccess(x interface{}) {
	p.Success = x.(*MarkOrderPaidResp)
}

func (p *OrderServiceMarkOrderPaidResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceMarkOrderPaidResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceMarkOrderPaidResult(%+v)", *p)
}

var fieldIDToName_OrderServiceMarkOrderPaidResult = map[int16]string{
	0: "success",
}

type OrderServiceGetPayAmountArgs struct {
	Req *GetPayAmountReq `thrift:"req,1" frugal:"1,default,GetPayAmountReq" json:"req"`
}

func NewOrderServiceGetPayAmountArgs() *OrderServiceGetPayAmountArgs {
	return &OrderServiceGetPayAmountArgs{}
}

func (p *OrderServiceGetPayAmountArgs) InitDefault() {
}

var OrderServiceGetPayAmountArgs_Req_DEFAULT *GetPayAmountReq

func (p *OrderServiceGetPayAmountArgs) GetReq() (v *GetPayAmountReq) {
	if !p.IsSetReq() {
		return OrderServiceGetPayAmountArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceGetPayAmountArgs) SetReq(val *GetPayAmountReq) {
	p.Req = val
}

func (p *OrderServiceGetPayAmountArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceGetPayAmountArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceGetPayAmountArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceGetPayAmountArgs = map[int16]string{
	1: "req",
}

type OrderServiceGetPayAmountResult struct {
	Success *GetPayAmountResp `thrift:"success,0,optional" frugal:"0,optional,GetPayAmountResp" json:"success,omitempty"`
}

func NewOrderServiceGetPayAmountResult() *OrderServiceGetPayAmountResult {
	return &OrderServiceGetPayAmountResult{}
}

func (p *OrderServiceGetPayAmountResult) InitDefault() {
}

var OrderServiceGetPayAmountResult_Success_DEFAULT *GetPayAmountResp

func (p *OrderServiceGetPayAmountResult) GetSuccess() (v *GetPayAmountResp) {
	if !p.IsSetSuccess() {
		return OrderServiceGetPayAmountResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceGetPayAmountResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetPayAmountResp)
}

func (p *OrderServiceGetPayAmountResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceGetPayAmountResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceGetPayAmountResult(%+v)", *p)
}

var fieldIDToName_OrderServiceGetPayAmountResult = map[int16]string{
	0: "success",
}
