// Code generated by Kitex v0.15.2. DO NOT EDIT.

package cartservice

import (
	cart "MengGoods/kitex_gen/cart"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"AddCartItem": kitex.NewMethodInfo(
		addCartItemHandler,
		newCartServiceAddCartItemArgs,
		newCartServiceAddCartItemResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetCartItem": kitex.NewMethodInfo(
		getCartItemHandler,
		newCartServiceGetCartItemArgs,
		newCartServiceGetCartItemResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteCartItem": kitex.NewMethodInfo(
		deleteCartItemHandler,
		newCartServiceDeleteCartItemArgs,
		newCartServiceDeleteCartItemResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateCartItem": kitex.NewMethodInfo(
		updateCartItemHandler,
		newCartServiceUpdateCartItemArgs,
		newCartServiceUpdateCartItemResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	cartServiceServiceInfo                = NewServiceInfo()
	cartServiceServiceInfoForClient       = NewServiceInfoForClient()
	cartServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return cartServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return cartServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return cartServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "CartService"
	handlerType := (*cart.CartService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "cart",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func addCartItemHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*cart.CartServiceAddCartItemArgs)
	realResult := result.(*cart.CartServiceAddCartItemResult)
	success, err := handler.(cart.CartService).AddCartItem(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCartServiceAddCartItemArgs() interface{} {
	return cart.NewCartServiceAddCartItemArgs()
}

func newCartServiceAddCartItemResult() interface{} {
	return cart.NewCartServiceAddCartItemResult()
}

func getCartItemHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*cart.CartServiceGetCartItemArgs)
	realResult := result.(*cart.CartServiceGetCartItemResult)
	success, err := handler.(cart.CartService).GetCartItem(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCartServiceGetCartItemArgs() interface{} {
	return cart.NewCartServiceGetCartItemArgs()
}

func newCartServiceGetCartItemResult() interface{} {
	return cart.NewCartServiceGetCartItemResult()
}

func deleteCartItemHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*cart.CartServiceDeleteCartItemArgs)
	realResult := result.(*cart.CartServiceDeleteCartItemResult)
	success, err := handler.(cart.CartService).DeleteCartItem(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCartServiceDeleteCartItemArgs() interface{} {
	return cart.NewCartServiceDeleteCartItemArgs()
}

func newCartServiceDeleteCartItemResult() interface{} {
	return cart.NewCartServiceDeleteCartItemResult()
}

func updateCartItemHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*cart.CartServiceUpdateCartItemArgs)
	realResult := result.(*cart.CartServiceUpdateCartItemResult)
	success, err := handler.(cart.CartService).UpdateCartItem(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCartServiceUpdateCartItemArgs() interface{} {
	return cart.NewCartServiceUpdateCartItemArgs()
}

func newCartServiceUpdateCartItemResult() interface{} {
	return cart.NewCartServiceUpdateCartItemResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) AddCartItem(ctx context.Context, req *cart.AddCartItemReq) (r *cart.AddCartItemResp, err error) {
	var _args cart.CartServiceAddCartItemArgs
	_args.Req = req
	var _result cart.CartServiceAddCartItemResult
	if err = p.c.Call(ctx, "AddCartItem", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetCartItem(ctx context.Context, req *cart.GetCartItemReq) (r *cart.GetCartItemResp, err error) {
	var _args cart.CartServiceGetCartItemArgs
	_args.Req = req
	var _result cart.CartServiceGetCartItemResult
	if err = p.c.Call(ctx, "GetCartItem", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteCartItem(ctx context.Context, req *cart.DeleteCartItemReq) (r *cart.DeleteCartItemResp, err error) {
	var _args cart.CartServiceDeleteCartItemArgs
	_args.Req = req
	var _result cart.CartServiceDeleteCartItemResult
	if err = p.c.Call(ctx, "DeleteCartItem", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateCartItem(ctx context.Context, req *cart.UpdateCartItemReq) (r *cart.UpdateCartItemResp, err error) {
	var _args cart.CartServiceUpdateCartItemArgs
	_args.Req = req
	var _result cart.CartServiceUpdateCartItemResult
	if err = p.c.Call(ctx, "UpdateCartItem", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
