// Code generated by Kitex v0.15.2. DO NOT EDIT.

package cartservice

import (
	cart "MengGoods/kitex_gen/cart"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	AddCartItem(ctx context.Context, req *cart.AddCartItemReq, callOptions ...callopt.Option) (r *cart.AddCartItemResp, err error)
	GetCartItem(ctx context.Context, req *cart.GetCartItemReq, callOptions ...callopt.Option) (r *cart.GetCartItemResp, err error)
	DeleteCartItem(ctx context.Context, req *cart.DeleteCartItemReq, callOptions ...callopt.Option) (r *cart.DeleteCartItemResp, err error)
	UpdateCartItem(ctx context.Context, req *cart.UpdateCartItemReq, callOptions ...callopt.Option) (r *cart.UpdateCartItemResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kCartServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCartServiceClient struct {
	*kClient
}

func (p *kCartServiceClient) AddCartItem(ctx context.Context, req *cart.AddCartItemReq, callOptions ...callopt.Option) (r *cart.AddCartItemResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddCartItem(ctx, req)
}

func (p *kCartServiceClient) GetCartItem(ctx context.Context, req *cart.GetCartItemReq, callOptions ...callopt.Option) (r *cart.GetCartItemResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCartItem(ctx, req)
}

func (p *kCartServiceClient) DeleteCartItem(ctx context.Context, req *cart.DeleteCartItemReq, callOptions ...callopt.Option) (r *cart.DeleteCartItemResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteCartItem(ctx, req)
}

func (p *kCartServiceClient) UpdateCartItem(ctx context.Context, req *cart.UpdateCartItemReq, callOptions ...callopt.Option) (r *cart.UpdateCartItemResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateCartItem(ctx, req)
}
