// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package cart

import (
	"MengGoods/kitex_gen/model"
	"context"
	"fmt"
)

type AddCartItemReq struct {
	UserId   int64           `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	CartItem *model.CartItem `thrift:"cartItem,2" frugal:"2,default,model.CartItem" json:"cartItem"`
}

func NewAddCartItemReq() *AddCartItemReq {
	return &AddCartItemReq{}
}

func (p *AddCartItemReq) InitDefault() {
}

func (p *AddCartItemReq) GetUserId() (v int64) {
	return p.UserId
}

var AddCartItemReq_CartItem_DEFAULT *model.CartItem

func (p *AddCartItemReq) GetCartItem() (v *model.CartItem) {
	if !p.IsSetCartItem() {
		return AddCartItemReq_CartItem_DEFAULT
	}
	return p.CartItem
}
func (p *AddCartItemReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *AddCartItemReq) SetCartItem(val *model.CartItem) {
	p.CartItem = val
}

func (p *AddCartItemReq) IsSetCartItem() bool {
	return p.CartItem != nil
}

func (p *AddCartItemReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddCartItemReq(%+v)", *p)
}

var fieldIDToName_AddCartItemReq = map[int16]string{
	1: "userId",
	2: "cartItem",
}

type AddCartItemResp struct {
	Base *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
}

func NewAddCartItemResp() *AddCartItemResp {
	return &AddCartItemResp{}
}

func (p *AddCartItemResp) InitDefault() {
}

var AddCartItemResp_Base_DEFAULT *model.BaseResp

func (p *AddCartItemResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return AddCartItemResp_Base_DEFAULT
	}
	return p.Base
}
func (p *AddCartItemResp) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *AddCartItemResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *AddCartItemResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddCartItemResp(%+v)", *p)
}

var fieldIDToName_AddCartItemResp = map[int16]string{
	1: "base",
}

type GetCartItemReq struct {
}

func NewGetCartItemReq() *GetCartItemReq {
	return &GetCartItemReq{}
}

func (p *GetCartItemReq) InitDefault() {
}

func (p *GetCartItemReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetCartItemReq(%+v)", *p)
}

var fieldIDToName_GetCartItemReq = map[int16]string{}

type GetCartItemResp struct {
	Base      *model.BaseResp   `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
	CartItems []*model.CartItem `thrift:"cartItems,2" frugal:"2,default,list<model.CartItem>" json:"cartItems"`
}

func NewGetCartItemResp() *GetCartItemResp {
	return &GetCartItemResp{}
}

func (p *GetCartItemResp) InitDefault() {
}

var GetCartItemResp_Base_DEFAULT *model.BaseResp

func (p *GetCartItemResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return GetCartItemResp_Base_DEFAULT
	}
	return p.Base
}

func (p *GetCartItemResp) GetCartItems() (v []*model.CartItem) {
	return p.CartItems
}
func (p *GetCartItemResp) SetBase(val *model.BaseResp) {
	p.Base = val
}
func (p *GetCartItemResp) SetCartItems(val []*model.CartItem) {
	p.CartItems = val
}

func (p *GetCartItemResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetCartItemResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetCartItemResp(%+v)", *p)
}

var fieldIDToName_GetCartItemResp = map[int16]string{
	1: "base",
	2: "cartItems",
}

type DeleteCartItemReq struct {
	UserId int64 `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
}

func NewDeleteCartItemReq() *DeleteCartItemReq {
	return &DeleteCartItemReq{}
}

func (p *DeleteCartItemReq) InitDefault() {
}

func (p *DeleteCartItemReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *DeleteCartItemReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *DeleteCartItemReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteCartItemReq(%+v)", *p)
}

var fieldIDToName_DeleteCartItemReq = map[int16]string{
	1: "userId",
}

type DeleteCartItemResp struct {
	Base *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
}

func NewDeleteCartItemResp() *DeleteCartItemResp {
	return &DeleteCartItemResp{}
}

func (p *DeleteCartItemResp) InitDefault() {
}

var DeleteCartItemResp_Base_DEFAULT *model.BaseResp

func (p *DeleteCartItemResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return DeleteCartItemResp_Base_DEFAULT
	}
	return p.Base
}
func (p *DeleteCartItemResp) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *DeleteCartItemResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *DeleteCartItemResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteCartItemResp(%+v)", *p)
}

var fieldIDToName_DeleteCartItemResp = map[int16]string{
	1: "base",
}

type UpdateCartItemReq struct {
	UserId   int64           `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	CartItem *model.CartItem `thrift:"cartItem,2" frugal:"2,default,model.CartItem" json:"cartItem"`
}

func NewUpdateCartItemReq() *UpdateCartItemReq {
	return &UpdateCartItemReq{}
}

func (p *UpdateCartItemReq) InitDefault() {
}

func (p *UpdateCartItemReq) GetUserId() (v int64) {
	return p.UserId
}

var UpdateCartItemReq_CartItem_DEFAULT *model.CartItem

func (p *UpdateCartItemReq) GetCartItem() (v *model.CartItem) {
	if !p.IsSetCartItem() {
		return UpdateCartItemReq_CartItem_DEFAULT
	}
	return p.CartItem
}
func (p *UpdateCartItemReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *UpdateCartItemReq) SetCartItem(val *model.CartItem) {
	p.CartItem = val
}

func (p *UpdateCartItemReq) IsSetCartItem() bool {
	return p.CartItem != nil
}

func (p *UpdateCartItemReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateCartItemReq(%+v)", *p)
}

var fieldIDToName_UpdateCartItemReq = map[int16]string{
	1: "userId",
	2: "cartItem",
}

type UpdateCartItemResp struct {
	Base *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
}

func NewUpdateCartItemResp() *UpdateCartItemResp {
	return &UpdateCartItemResp{}
}

func (p *UpdateCartItemResp) InitDefault() {
}

var UpdateCartItemResp_Base_DEFAULT *model.BaseResp

func (p *UpdateCartItemResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return UpdateCartItemResp_Base_DEFAULT
	}
	return p.Base
}
func (p *UpdateCartItemResp) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *UpdateCartItemResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *UpdateCartItemResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateCartItemResp(%+v)", *p)
}

var fieldIDToName_UpdateCartItemResp = map[int16]string{
	1: "base",
}

type CartService interface {
	AddCartItem(ctx context.Context, req *AddCartItemReq) (r *AddCartItemResp, err error)

	GetCartItem(ctx context.Context, req *GetCartItemReq) (r *GetCartItemResp, err error)

	DeleteCartItem(ctx context.Context, req *DeleteCartItemReq) (r *DeleteCartItemResp, err error)

	UpdateCartItem(ctx context.Context, req *UpdateCartItemReq) (r *UpdateCartItemResp, err error)
}

type CartServiceAddCartItemArgs struct {
	Req *AddCartItemReq `thrift:"req,1" frugal:"1,default,AddCartItemReq" json:"req"`
}

func NewCartServiceAddCartItemArgs() *CartServiceAddCartItemArgs {
	return &CartServiceAddCartItemArgs{}
}

func (p *CartServiceAddCartItemArgs) InitDefault() {
}

var CartServiceAddCartItemArgs_Req_DEFAULT *AddCartItemReq

func (p *CartServiceAddCartItemArgs) GetReq() (v *AddCartItemReq) {
	if !p.IsSetReq() {
		return CartServiceAddCartItemArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *CartServiceAddCartItemArgs) SetReq(val *AddCartItemReq) {
	p.Req = val
}

func (p *CartServiceAddCartItemArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CartServiceAddCartItemArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CartServiceAddCartItemArgs(%+v)", *p)
}

var fieldIDToName_CartServiceAddCartItemArgs = map[int16]string{
	1: "req",
}

type CartServiceAddCartItemResult struct {
	Success *AddCartItemResp `thrift:"success,0,optional" frugal:"0,optional,AddCartItemResp" json:"success,omitempty"`
}

func NewCartServiceAddCartItemResult() *CartServiceAddCartItemResult {
	return &CartServiceAddCartItemResult{}
}

func (p *CartServiceAddCartItemResult) InitDefault() {
}

var CartServiceAddCartItemResult_Success_DEFAULT *AddCartItemResp

func (p *CartServiceAddCartItemResult) GetSuccess() (v *AddCartItemResp) {
	if !p.IsSetSuccess() {
		return CartServiceAddCartItemResult_Success_DEFAULT
	}
	return p.Success
}
func (p *CartServiceAddCartItemResult) SetSuccess(x interface{}) {
	p.Success = x.(*AddCartItemResp)
}

func (p *CartServiceAddCartItemResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CartServiceAddCartItemResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CartServiceAddCartItemResult(%+v)", *p)
}

var fieldIDToName_CartServiceAddCartItemResult = map[int16]string{
	0: "success",
}

type CartServiceGetCartItemArgs struct {
	Req *GetCartItemReq `thrift:"req,1" frugal:"1,default,GetCartItemReq" json:"req"`
}

func NewCartServiceGetCartItemArgs() *CartServiceGetCartItemArgs {
	return &CartServiceGetCartItemArgs{}
}

func (p *CartServiceGetCartItemArgs) InitDefault() {
}

var CartServiceGetCartItemArgs_Req_DEFAULT *GetCartItemReq

func (p *CartServiceGetCartItemArgs) GetReq() (v *GetCartItemReq) {
	if !p.IsSetReq() {
		return CartServiceGetCartItemArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *CartServiceGetCartItemArgs) SetReq(val *GetCartItemReq) {
	p.Req = val
}

func (p *CartServiceGetCartItemArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CartServiceGetCartItemArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CartServiceGetCartItemArgs(%+v)", *p)
}

var fieldIDToName_CartServiceGetCartItemArgs = map[int16]string{
	1: "req",
}

type CartServiceGetCartItemResult struct {
	Success *GetCartItemResp `thrift:"success,0,optional" frugal:"0,optional,GetCartItemResp" json:"success,omitempty"`
}

func NewCartServiceGetCartItemResult() *CartServiceGetCartItemResult {
	return &CartServiceGetCartItemResult{}
}

func (p *CartServiceGetCartItemResult) InitDefault() {
}

var CartServiceGetCartItemResult_Success_DEFAULT *GetCartItemResp

func (p *CartServiceGetCartItemResult) GetSuccess() (v *GetCartItemResp) {
	if !p.IsSetSuccess() {
		return CartServiceGetCartItemResult_Success_DEFAULT
	}
	return p.Success
}
func (p *CartServiceGetCartItemResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetCartItemResp)
}

func (p *CartServiceGetCartItemResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CartServiceGetCartItemResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CartServiceGetCartItemResult(%+v)", *p)
}

var fieldIDToName_CartServiceGetCartItemResult = map[int16]string{
	0: "success",
}

type CartServiceDeleteCartItemArgs struct {
	Req *DeleteCartItemReq `thrift:"req,1" frugal:"1,default,DeleteCartItemReq" json:"req"`
}

func NewCartServiceDeleteCartItemArgs() *CartServiceDeleteCartItemArgs {
	return &CartServiceDeleteCartItemArgs{}
}

func (p *CartServiceDeleteCartItemArgs) InitDefault() {
}

var CartServiceDeleteCartItemArgs_Req_DEFAULT *DeleteCartItemReq

func (p *CartServiceDeleteCartItemArgs) GetReq() (v *DeleteCartItemReq) {
	if !p.IsSetReq() {
		return CartServiceDeleteCartItemArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *CartServiceDeleteCartItemArgs) SetReq(val *DeleteCartItemReq) {
	p.Req = val
}

func (p *CartServiceDeleteCartItemArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CartServiceDeleteCartItemArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CartServiceDeleteCartItemArgs(%+v)", *p)
}

var fieldIDToName_CartServiceDeleteCartItemArgs = map[int16]string{
	1: "req",
}

type CartServiceDeleteCartItemResult struct {
	Success *DeleteCartItemResp `thrift:"success,0,optional" frugal:"0,optional,DeleteCartItemResp" json:"success,omitempty"`
}

func NewCartServiceDeleteCartItemResult() *CartServiceDeleteCartItemResult {
	return &CartServiceDeleteCartItemResult{}
}

func (p *CartServiceDeleteCartItemResult) InitDefault() {
}

var CartServiceDeleteCartItemResult_Success_DEFAULT *DeleteCartItemResp

func (p *CartServiceDeleteCartItemResult) GetSuccess() (v *DeleteCartItemResp) {
	if !p.IsSetSuccess() {
		return CartServiceDeleteCartItemResult_Success_DEFAULT
	}
	return p.Success
}
func (p *CartServiceDeleteCartItemResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteCartItemResp)
}

func (p *CartServiceDeleteCartItemResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CartServiceDeleteCartItemResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CartServiceDeleteCartItemResult(%+v)", *p)
}

var fieldIDToName_CartServiceDeleteCartItemResult = map[int16]string{
	0: "success",
}

type CartServiceUpdateCartItemArgs struct {
	Req *UpdateCartItemReq `thrift:"req,1" frugal:"1,default,UpdateCartItemReq" json:"req"`
}

func NewCartServiceUpdateCartItemArgs() *CartServiceUpdateCartItemArgs {
	return &CartServiceUpdateCartItemArgs{}
}

func (p *CartServiceUpdateCartItemArgs) InitDefault() {
}

var CartServiceUpdateCartItemArgs_Req_DEFAULT *UpdateCartItemReq

func (p *CartServiceUpdateCartItemArgs) GetReq() (v *UpdateCartItemReq) {
	if !p.IsSetReq() {
		return CartServiceUpdateCartItemArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *CartServiceUpdateCartItemArgs) SetReq(val *UpdateCartItemReq) {
	p.Req = val
}

func (p *CartServiceUpdateCartItemArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CartServiceUpdateCartItemArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CartServiceUpdateCartItemArgs(%+v)", *p)
}

var fieldIDToName_CartServiceUpdateCartItemArgs = map[int16]string{
	1: "req",
}

type CartServiceUpdateCartItemResult struct {
	Success *UpdateCartItemResp `thrift:"success,0,optional" frugal:"0,optional,UpdateCartItemResp" json:"success,omitempty"`
}

func NewCartServiceUpdateCartItemResult() *CartServiceUpdateCartItemResult {
	return &CartServiceUpdateCartItemResult{}
}

func (p *CartServiceUpdateCartItemResult) InitDefault() {
}

var CartServiceUpdateCartItemResult_Success_DEFAULT *UpdateCartItemResp

func (p *CartServiceUpdateCartItemResult) GetSuccess() (v *UpdateCartItemResp) {
	if !p.IsSetSuccess() {
		return CartServiceUpdateCartItemResult_Success_DEFAULT
	}
	return p.Success
}
func (p *CartServiceUpdateCartItemResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateCartItemResp)
}

func (p *CartServiceUpdateCartItemResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CartServiceUpdateCartItemResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CartServiceUpdateCartItemResult(%+v)", *p)
}

var fieldIDToName_CartServiceUpdateCartItemResult = map[int16]string{
	0: "success",
}
