// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package coupon

import (
	"MengGoods/kitex_gen/model"
	"context"
	"fmt"
)

type CreateCouponBatchReq struct {
	BatchName string `thrift:"batchName,1" frugal:"1,default,string" json:"batchName"`
	Remark    string `thrift:"remark,2" frugal:"2,default,string" json:"remark"`
	Type      int32  `thrift:"type,3" frugal:"3,default,i32" json:"type"`
	Threshold int64  `thrift:"threshold,4" frugal:"4,default,i64" json:"threshold"`
	Amount    int64  `thrift:"amount,5" frugal:"5,default,i64" json:"amount"`
	Rate      int64  `thrift:"rate,6" frugal:"6,default,i64" json:"rate"`
	Total     int64  `thrift:"total,7" frugal:"7,default,i64" json:"total"`
	StartTime int64  `thrift:"startTime,8" frugal:"8,default,i64" json:"startTime"`
	EndTime   int64  `thrift:"endTime,9" frugal:"9,default,i64" json:"endTime"`
	Duration  int64  `thrift:"duration,10" frugal:"10,default,i64" json:"duration"`
}

func NewCreateCouponBatchReq() *CreateCouponBatchReq {
	return &CreateCouponBatchReq{}
}

func (p *CreateCouponBatchReq) InitDefault() {
}

func (p *CreateCouponBatchReq) GetBatchName() (v string) {
	return p.BatchName
}

func (p *CreateCouponBatchReq) GetRemark() (v string) {
	return p.Remark
}

func (p *CreateCouponBatchReq) GetType() (v int32) {
	return p.Type
}

func (p *CreateCouponBatchReq) GetThreshold() (v int64) {
	return p.Threshold
}

func (p *CreateCouponBatchReq) GetAmount() (v int64) {
	return p.Amount
}

func (p *CreateCouponBatchReq) GetRate() (v int64) {
	return p.Rate
}

func (p *CreateCouponBatchReq) GetTotal() (v int64) {
	return p.Total
}

func (p *CreateCouponBatchReq) GetStartTime() (v int64) {
	return p.StartTime
}

func (p *CreateCouponBatchReq) GetEndTime() (v int64) {
	return p.EndTime
}

func (p *CreateCouponBatchReq) GetDuration() (v int64) {
	return p.Duration
}
func (p *CreateCouponBatchReq) SetBatchName(val string) {
	p.BatchName = val
}
func (p *CreateCouponBatchReq) SetRemark(val string) {
	p.Remark = val
}
func (p *CreateCouponBatchReq) SetType(val int32) {
	p.Type = val
}
func (p *CreateCouponBatchReq) SetThreshold(val int64) {
	p.Threshold = val
}
func (p *CreateCouponBatchReq) SetAmount(val int64) {
	p.Amount = val
}
func (p *CreateCouponBatchReq) SetRate(val int64) {
	p.Rate = val
}
func (p *CreateCouponBatchReq) SetTotal(val int64) {
	p.Total = val
}
func (p *CreateCouponBatchReq) SetStartTime(val int64) {
	p.StartTime = val
}
func (p *CreateCouponBatchReq) SetEndTime(val int64) {
	p.EndTime = val
}
func (p *CreateCouponBatchReq) SetDuration(val int64) {
	p.Duration = val
}

func (p *CreateCouponBatchReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateCouponBatchReq(%+v)", *p)
}

var fieldIDToName_CreateCouponBatchReq = map[int16]string{
	1:  "batchName",
	2:  "remark",
	3:  "type",
	4:  "threshold",
	5:  "amount",
	6:  "rate",
	7:  "total",
	8:  "startTime",
	9:  "endTime",
	10: "duration",
}

type CreateCouponBatchResp struct {
	Base    *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
	BatchId int64           `thrift:"batchId,2" frugal:"2,default,i64" json:"batchId"`
}

func NewCreateCouponBatchResp() *CreateCouponBatchResp {
	return &CreateCouponBatchResp{}
}

func (p *CreateCouponBatchResp) InitDefault() {
}

var CreateCouponBatchResp_Base_DEFAULT *model.BaseResp

func (p *CreateCouponBatchResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return CreateCouponBatchResp_Base_DEFAULT
	}
	return p.Base
}

func (p *CreateCouponBatchResp) GetBatchId() (v int64) {
	return p.BatchId
}
func (p *CreateCouponBatchResp) SetBase(val *model.BaseResp) {
	p.Base = val
}
func (p *CreateCouponBatchResp) SetBatchId(val int64) {
	p.BatchId = val
}

func (p *CreateCouponBatchResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *CreateCouponBatchResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateCouponBatchResp(%+v)", *p)
}

var fieldIDToName_CreateCouponBatchResp = map[int16]string{
	1: "base",
	2: "batchId",
}

type GetCouponReq struct {
	BatchId int64 `thrift:"batchId,1" frugal:"1,default,i64" json:"batchId"`
}

func NewGetCouponReq() *GetCouponReq {
	return &GetCouponReq{}
}

func (p *GetCouponReq) InitDefault() {
}

func (p *GetCouponReq) GetBatchId() (v int64) {
	return p.BatchId
}
func (p *GetCouponReq) SetBatchId(val int64) {
	p.BatchId = val
}

func (p *GetCouponReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetCouponReq(%+v)", *p)
}

var fieldIDToName_GetCouponReq = map[int16]string{
	1: "batchId",
}

type GetCouponResp struct {
	Base *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
}

func NewGetCouponResp() *GetCouponResp {
	return &GetCouponResp{}
}

func (p *GetCouponResp) InitDefault() {
}

var GetCouponResp_Base_DEFAULT *model.BaseResp

func (p *GetCouponResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return GetCouponResp_Base_DEFAULT
	}
	return p.Base
}
func (p *GetCouponResp) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *GetCouponResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetCouponResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetCouponResp(%+v)", *p)
}

var fieldIDToName_GetCouponResp = map[int16]string{
	1: "base",
}

type GetCouponListReq struct {
	Status int64 `thrift:"status,1" frugal:"1,default,i64" json:"status"`
}

func NewGetCouponListReq() *GetCouponListReq {
	return &GetCouponListReq{}
}

func (p *GetCouponListReq) InitDefault() {
}

func (p *GetCouponListReq) GetStatus() (v int64) {
	return p.Status
}
func (p *GetCouponListReq) SetStatus(val int64) {
	p.Status = val
}

func (p *GetCouponListReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetCouponListReq(%+v)", *p)
}

var fieldIDToName_GetCouponListReq = map[int16]string{
	1: "status",
}

type GetCouponListResp struct {
	Base       *model.BaseResp     `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
	CouponList []*model.CouponInfo `thrift:"couponList,2" frugal:"2,default,list<model.CouponInfo>" json:"couponList"`
	Total      int64               `thrift:"total,3" frugal:"3,default,i64" json:"total"`
}

func NewGetCouponListResp() *GetCouponListResp {
	return &GetCouponListResp{}
}

func (p *GetCouponListResp) InitDefault() {
}

var GetCouponListResp_Base_DEFAULT *model.BaseResp

func (p *GetCouponListResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return GetCouponListResp_Base_DEFAULT
	}
	return p.Base
}

func (p *GetCouponListResp) GetCouponList() (v []*model.CouponInfo) {
	return p.CouponList
}

func (p *GetCouponListResp) GetTotal() (v int64) {
	return p.Total
}
func (p *GetCouponListResp) SetBase(val *model.BaseResp) {
	p.Base = val
}
func (p *GetCouponListResp) SetCouponList(val []*model.CouponInfo) {
	p.CouponList = val
}
func (p *GetCouponListResp) SetTotal(val int64) {
	p.Total = val
}

func (p *GetCouponListResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetCouponListResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetCouponListResp(%+v)", *p)
}

var fieldIDToName_GetCouponListResp = map[int16]string{
	1: "base",
	2: "couponList",
	3: "total",
}

type LockCouponReq struct {
	CouponId int64 `thrift:"couponId,1" frugal:"1,default,i64" json:"couponId"`
	OrderId  int64 `thrift:"orderId,2" frugal:"2,default,i64" json:"orderId"`
}

func NewLockCouponReq() *LockCouponReq {
	return &LockCouponReq{}
}

func (p *LockCouponReq) InitDefault() {
}

func (p *LockCouponReq) GetCouponId() (v int64) {
	return p.CouponId
}

func (p *LockCouponReq) GetOrderId() (v int64) {
	return p.OrderId
}
func (p *LockCouponReq) SetCouponId(val int64) {
	p.CouponId = val
}
func (p *LockCouponReq) SetOrderId(val int64) {
	p.OrderId = val
}

func (p *LockCouponReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LockCouponReq(%+v)", *p)
}

var fieldIDToName_LockCouponReq = map[int16]string{
	1: "couponId",
	2: "orderId",
}

type LockCouponResp struct {
	Base *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
}

func NewLockCouponResp() *LockCouponResp {
	return &LockCouponResp{}
}

func (p *LockCouponResp) InitDefault() {
}

var LockCouponResp_Base_DEFAULT *model.BaseResp

func (p *LockCouponResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return LockCouponResp_Base_DEFAULT
	}
	return p.Base
}
func (p *LockCouponResp) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *LockCouponResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *LockCouponResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LockCouponResp(%+v)", *p)
}

var fieldIDToName_LockCouponResp = map[int16]string{
	1: "base",
}

type ReleaseCouponReq struct {
	CouponId int64 `thrift:"couponId,1" frugal:"1,default,i64" json:"couponId"`
	OrderId  int64 `thrift:"orderId,2" frugal:"2,default,i64" json:"orderId"`
}

func NewReleaseCouponReq() *ReleaseCouponReq {
	return &ReleaseCouponReq{}
}

func (p *ReleaseCouponReq) InitDefault() {
}

func (p *ReleaseCouponReq) GetCouponId() (v int64) {
	return p.CouponId
}

func (p *ReleaseCouponReq) GetOrderId() (v int64) {
	return p.OrderId
}
func (p *ReleaseCouponReq) SetCouponId(val int64) {
	p.CouponId = val
}
func (p *ReleaseCouponReq) SetOrderId(val int64) {
	p.OrderId = val
}

func (p *ReleaseCouponReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ReleaseCouponReq(%+v)", *p)
}

var fieldIDToName_ReleaseCouponReq = map[int16]string{
	1: "couponId",
	2: "orderId",
}

type ReleaseCouponResp struct {
	Base *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
}

func NewReleaseCouponResp() *ReleaseCouponResp {
	return &ReleaseCouponResp{}
}

func (p *ReleaseCouponResp) InitDefault() {
}

var ReleaseCouponResp_Base_DEFAULT *model.BaseResp

func (p *ReleaseCouponResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return ReleaseCouponResp_Base_DEFAULT
	}
	return p.Base
}
func (p *ReleaseCouponResp) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *ReleaseCouponResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *ReleaseCouponResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ReleaseCouponResp(%+v)", *p)
}

var fieldIDToName_ReleaseCouponResp = map[int16]string{
	1: "base",
}

type RedeemCouponReq struct {
	CouponId int64 `thrift:"couponId,1" frugal:"1,default,i64" json:"couponId"`
	OrderId  int64 `thrift:"orderId,2" frugal:"2,default,i64" json:"orderId"`
}

func NewRedeemCouponReq() *RedeemCouponReq {
	return &RedeemCouponReq{}
}

func (p *RedeemCouponReq) InitDefault() {
}

func (p *RedeemCouponReq) GetCouponId() (v int64) {
	return p.CouponId
}

func (p *RedeemCouponReq) GetOrderId() (v int64) {
	return p.OrderId
}
func (p *RedeemCouponReq) SetCouponId(val int64) {
	p.CouponId = val
}
func (p *RedeemCouponReq) SetOrderId(val int64) {
	p.OrderId = val
}

func (p *RedeemCouponReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RedeemCouponReq(%+v)", *p)
}

var fieldIDToName_RedeemCouponReq = map[int16]string{
	1: "couponId",
	2: "orderId",
}

type RedeemCouponResp struct {
	Base *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
}

func NewRedeemCouponResp() *RedeemCouponResp {
	return &RedeemCouponResp{}
}

func (p *RedeemCouponResp) InitDefault() {
}

var RedeemCouponResp_Base_DEFAULT *model.BaseResp

func (p *RedeemCouponResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return RedeemCouponResp_Base_DEFAULT
	}
	return p.Base
}
func (p *RedeemCouponResp) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *RedeemCouponResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *RedeemCouponResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RedeemCouponResp(%+v)", *p)
}

var fieldIDToName_RedeemCouponResp = map[int16]string{
	1: "base",
}

type CouponService interface {
	CreateCouponBatch(ctx context.Context, req *CreateCouponBatchReq) (r *CreateCouponBatchResp, err error)

	GetCoupon(ctx context.Context, req *GetCouponReq) (r *GetCouponResp, err error)

	GetCouponList(ctx context.Context, req *GetCouponListReq) (r *GetCouponListResp, err error)

	LockCoupon(ctx context.Context, req *LockCouponReq) (r *LockCouponResp, err error)

	ReleaseCoupon(ctx context.Context, req *ReleaseCouponReq) (r *ReleaseCouponResp, err error)

	RedeemCoupon(ctx context.Context, req *RedeemCouponReq) (r *RedeemCouponResp, err error)
}

type CouponServiceCreateCouponBatchArgs struct {
	Req *CreateCouponBatchReq `thrift:"req,1" frugal:"1,default,CreateCouponBatchReq" json:"req"`
}

func NewCouponServiceCreateCouponBatchArgs() *CouponServiceCreateCouponBatchArgs {
	return &CouponServiceCreateCouponBatchArgs{}
}

func (p *CouponServiceCreateCouponBatchArgs) InitDefault() {
}

var CouponServiceCreateCouponBatchArgs_Req_DEFAULT *CreateCouponBatchReq

func (p *CouponServiceCreateCouponBatchArgs) GetReq() (v *CreateCouponBatchReq) {
	if !p.IsSetReq() {
		return CouponServiceCreateCouponBatchArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *CouponServiceCreateCouponBatchArgs) SetReq(val *CreateCouponBatchReq) {
	p.Req = val
}

func (p *CouponServiceCreateCouponBatchArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CouponServiceCreateCouponBatchArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CouponServiceCreateCouponBatchArgs(%+v)", *p)
}

var fieldIDToName_CouponServiceCreateCouponBatchArgs = map[int16]string{
	1: "req",
}

type CouponServiceCreateCouponBatchResult struct {
	Success *CreateCouponBatchResp `thrift:"success,0,optional" frugal:"0,optional,CreateCouponBatchResp" json:"success,omitempty"`
}

func NewCouponServiceCreateCouponBatchResult() *CouponServiceCreateCouponBatchResult {
	return &CouponServiceCreateCouponBatchResult{}
}

func (p *CouponServiceCreateCouponBatchResult) InitDefault() {
}

var CouponServiceCreateCouponBatchResult_Success_DEFAULT *CreateCouponBatchResp

func (p *CouponServiceCreateCouponBatchResult) GetSuccess() (v *CreateCouponBatchResp) {
	if !p.IsSetSuccess() {
		return CouponServiceCreateCouponBatchResult_Success_DEFAULT
	}
	return p.Success
}
func (p *CouponServiceCreateCouponBatchResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateCouponBatchResp)
}

func (p *CouponServiceCreateCouponBatchResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CouponServiceCreateCouponBatchResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CouponServiceCreateCouponBatchResult(%+v)", *p)
}

var fieldIDToName_CouponServiceCreateCouponBatchResult = map[int16]string{
	0: "success",
}

type CouponServiceGetCouponArgs struct {
	Req *GetCouponReq `thrift:"req,1" frugal:"1,default,GetCouponReq" json:"req"`
}

func NewCouponServiceGetCouponArgs() *CouponServiceGetCouponArgs {
	return &CouponServiceGetCouponArgs{}
}

func (p *CouponServiceGetCouponArgs) InitDefault() {
}

var CouponServiceGetCouponArgs_Req_DEFAULT *GetCouponReq

func (p *CouponServiceGetCouponArgs) GetReq() (v *GetCouponReq) {
	if !p.IsSetReq() {
		return CouponServiceGetCouponArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *CouponServiceGetCouponArgs) SetReq(val *GetCouponReq) {
	p.Req = val
}

func (p *CouponServiceGetCouponArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CouponServiceGetCouponArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CouponServiceGetCouponArgs(%+v)", *p)
}

var fieldIDToName_CouponServiceGetCouponArgs = map[int16]string{
	1: "req",
}

type CouponServiceGetCouponResult struct {
	Success *GetCouponResp `thrift:"success,0,optional" frugal:"0,optional,GetCouponResp" json:"success,omitempty"`
}

func NewCouponServiceGetCouponResult() *CouponServiceGetCouponResult {
	return &CouponServiceGetCouponResult{}
}

func (p *CouponServiceGetCouponResult) InitDefault() {
}

var CouponServiceGetCouponResult_Success_DEFAULT *GetCouponResp

func (p *CouponServiceGetCouponResult) GetSuccess() (v *GetCouponResp) {
	if !p.IsSetSuccess() {
		return CouponServiceGetCouponResult_Success_DEFAULT
	}
	return p.Success
}
func (p *CouponServiceGetCouponResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetCouponResp)
}

func (p *CouponServiceGetCouponResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CouponServiceGetCouponResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CouponServiceGetCouponResult(%+v)", *p)
}

var fieldIDToName_CouponServiceGetCouponResult = map[int16]string{
	0: "success",
}

type CouponServiceGetCouponListArgs struct {
	Req *GetCouponListReq `thrift:"req,1" frugal:"1,default,GetCouponListReq" json:"req"`
}

func NewCouponServiceGetCouponListArgs() *CouponServiceGetCouponListArgs {
	return &CouponServiceGetCouponListArgs{}
}

func (p *CouponServiceGetCouponListArgs) InitDefault() {
}

var CouponServiceGetCouponListArgs_Req_DEFAULT *GetCouponListReq

func (p *CouponServiceGetCouponListArgs) GetReq() (v *GetCouponListReq) {
	if !p.IsSetReq() {
		return CouponServiceGetCouponListArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *CouponServiceGetCouponListArgs) SetReq(val *GetCouponListReq) {
	p.Req = val
}

func (p *CouponServiceGetCouponListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CouponServiceGetCouponListArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CouponServiceGetCouponListArgs(%+v)", *p)
}

var fieldIDToName_CouponServiceGetCouponListArgs = map[int16]string{
	1: "req",
}

type CouponServiceGetCouponListResult struct {
	Success *GetCouponListResp `thrift:"success,0,optional" frugal:"0,optional,GetCouponListResp" json:"success,omitempty"`
}

func NewCouponServiceGetCouponListResult() *CouponServiceGetCouponListResult {
	return &CouponServiceGetCouponListResult{}
}

func (p *CouponServiceGetCouponListResult) InitDefault() {
}

var CouponServiceGetCouponListResult_Success_DEFAULT *GetCouponListResp

func (p *CouponServiceGetCouponListResult) GetSuccess() (v *GetCouponListResp) {
	if !p.IsSetSuccess() {
		return CouponServiceGetCouponListResult_Success_DEFAULT
	}
	return p.Success
}
func (p *CouponServiceGetCouponListResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetCouponListResp)
}

func (p *CouponServiceGetCouponListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CouponServiceGetCouponListResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CouponServiceGetCouponListResult(%+v)", *p)
}

var fieldIDToName_CouponServiceGetCouponListResult = map[int16]string{
	0: "success",
}

type CouponServiceLockCouponArgs struct {
	Req *LockCouponReq `thrift:"req,1" frugal:"1,default,LockCouponReq" json:"req"`
}

func NewCouponServiceLockCouponArgs() *CouponServiceLockCouponArgs {
	return &CouponServiceLockCouponArgs{}
}

func (p *CouponServiceLockCouponArgs) InitDefault() {
}

var CouponServiceLockCouponArgs_Req_DEFAULT *LockCouponReq

func (p *CouponServiceLockCouponArgs) GetReq() (v *LockCouponReq) {
	if !p.IsSetReq() {
		return CouponServiceLockCouponArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *CouponServiceLockCouponArgs) SetReq(val *LockCouponReq) {
	p.Req = val
}

func (p *CouponServiceLockCouponArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CouponServiceLockCouponArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CouponServiceLockCouponArgs(%+v)", *p)
}

var fieldIDToName_CouponServiceLockCouponArgs = map[int16]string{
	1: "req",
}

type CouponServiceLockCouponResult struct {
	Success *LockCouponResp `thrift:"success,0,optional" frugal:"0,optional,LockCouponResp" json:"success,omitempty"`
}

func NewCouponServiceLockCouponResult() *CouponServiceLockCouponResult {
	return &CouponServiceLockCouponResult{}
}

func (p *CouponServiceLockCouponResult) InitDefault() {
}

var CouponServiceLockCouponResult_Success_DEFAULT *LockCouponResp

func (p *CouponServiceLockCouponResult) GetSuccess() (v *LockCouponResp) {
	if !p.IsSetSuccess() {
		return CouponServiceLockCouponResult_Success_DEFAULT
	}
	return p.Success
}
func (p *CouponServiceLockCouponResult) SetSuccess(x interface{}) {
	p.Success = x.(*LockCouponResp)
}

func (p *CouponServiceLockCouponResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CouponServiceLockCouponResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CouponServiceLockCouponResult(%+v)", *p)
}

var fieldIDToName_CouponServiceLockCouponResult = map[int16]string{
	0: "success",
}

type CouponServiceReleaseCouponArgs struct {
	Req *ReleaseCouponReq `thrift:"req,1" frugal:"1,default,ReleaseCouponReq" json:"req"`
}

func NewCouponServiceReleaseCouponArgs() *CouponServiceReleaseCouponArgs {
	return &CouponServiceReleaseCouponArgs{}
}

func (p *CouponServiceReleaseCouponArgs) InitDefault() {
}

var CouponServiceReleaseCouponArgs_Req_DEFAULT *ReleaseCouponReq

func (p *CouponServiceReleaseCouponArgs) GetReq() (v *ReleaseCouponReq) {
	if !p.IsSetReq() {
		return CouponServiceReleaseCouponArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *CouponServiceReleaseCouponArgs) SetReq(val *ReleaseCouponReq) {
	p.Req = val
}

func (p *CouponServiceReleaseCouponArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CouponServiceReleaseCouponArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CouponServiceReleaseCouponArgs(%+v)", *p)
}

var fieldIDToName_CouponServiceReleaseCouponArgs = map[int16]string{
	1: "req",
}

type CouponServiceReleaseCouponResult struct {
	Success *ReleaseCouponResp `thrift:"success,0,optional" frugal:"0,optional,ReleaseCouponResp" json:"success,omitempty"`
}

func NewCouponServiceReleaseCouponResult() *CouponServiceReleaseCouponResult {
	return &CouponServiceReleaseCouponResult{}
}

func (p *CouponServiceReleaseCouponResult) InitDefault() {
}

var CouponServiceReleaseCouponResult_Success_DEFAULT *ReleaseCouponResp

func (p *CouponServiceReleaseCouponResult) GetSuccess() (v *ReleaseCouponResp) {
	if !p.IsSetSuccess() {
		return CouponServiceReleaseCouponResult_Success_DEFAULT
	}
	return p.Success
}
func (p *CouponServiceReleaseCouponResult) SetSuccess(x interface{}) {
	p.Success = x.(*ReleaseCouponResp)
}

func (p *CouponServiceReleaseCouponResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CouponServiceReleaseCouponResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CouponServiceReleaseCouponResult(%+v)", *p)
}

var fieldIDToName_CouponServiceReleaseCouponResult = map[int16]string{
	0: "success",
}

type CouponServiceRedeemCouponArgs struct {
	Req *RedeemCouponReq `thrift:"req,1" frugal:"1,default,RedeemCouponReq" json:"req"`
}

func NewCouponServiceRedeemCouponArgs() *CouponServiceRedeemCouponArgs {
	return &CouponServiceRedeemCouponArgs{}
}

func (p *CouponServiceRedeemCouponArgs) InitDefault() {
}

var CouponServiceRedeemCouponArgs_Req_DEFAULT *RedeemCouponReq

func (p *CouponServiceRedeemCouponArgs) GetReq() (v *RedeemCouponReq) {
	if !p.IsSetReq() {
		return CouponServiceRedeemCouponArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *CouponServiceRedeemCouponArgs) SetReq(val *RedeemCouponReq) {
	p.Req = val
}

func (p *CouponServiceRedeemCouponArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CouponServiceRedeemCouponArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CouponServiceRedeemCouponArgs(%+v)", *p)
}

var fieldIDToName_CouponServiceRedeemCouponArgs = map[int16]string{
	1: "req",
}

type CouponServiceRedeemCouponResult struct {
	Success *RedeemCouponResp `thrift:"success,0,optional" frugal:"0,optional,RedeemCouponResp" json:"success,omitempty"`
}

func NewCouponServiceRedeemCouponResult() *CouponServiceRedeemCouponResult {
	return &CouponServiceRedeemCouponResult{}
}

func (p *CouponServiceRedeemCouponResult) InitDefault() {
}

var CouponServiceRedeemCouponResult_Success_DEFAULT *RedeemCouponResp

func (p *CouponServiceRedeemCouponResult) GetSuccess() (v *RedeemCouponResp) {
	if !p.IsSetSuccess() {
		return CouponServiceRedeemCouponResult_Success_DEFAULT
	}
	return p.Success
}
func (p *CouponServiceRedeemCouponResult) SetSuccess(x interface{}) {
	p.Success = x.(*RedeemCouponResp)
}

func (p *CouponServiceRedeemCouponResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CouponServiceRedeemCouponResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CouponServiceRedeemCouponResult(%+v)", *p)
}

var fieldIDToName_CouponServiceRedeemCouponResult = map[int16]string{
	0: "success",
}
