// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package stock

import (
	"MengGoods/kitex_gen/model"
	"context"
	"fmt"
)

type GetStockReq struct {
	SkuId int64 `thrift:"skuId,1" frugal:"1,default,i64" json:"skuId"`
}

func NewGetStockReq() *GetStockReq {
	return &GetStockReq{}
}

func (p *GetStockReq) InitDefault() {
}

func (p *GetStockReq) GetSkuId() (v int64) {
	return p.SkuId
}
func (p *GetStockReq) SetSkuId(val int64) {
	p.SkuId = val
}

func (p *GetStockReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetStockReq(%+v)", *p)
}

var fieldIDToName_GetStockReq = map[int16]string{
	1: "skuId",
}

type GetStockResp struct {
	Base  *model.BaseResp  `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
	Stock *model.StockItem `thrift:"stock,2" frugal:"2,default,model.StockItem" json:"stock"`
}

func NewGetStockResp() *GetStockResp {
	return &GetStockResp{}
}

func (p *GetStockResp) InitDefault() {
}

var GetStockResp_Base_DEFAULT *model.BaseResp

func (p *GetStockResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return GetStockResp_Base_DEFAULT
	}
	return p.Base
}

var GetStockResp_Stock_DEFAULT *model.StockItem

func (p *GetStockResp) GetStock() (v *model.StockItem) {
	if !p.IsSetStock() {
		return GetStockResp_Stock_DEFAULT
	}
	return p.Stock
}
func (p *GetStockResp) SetBase(val *model.BaseResp) {
	p.Base = val
}
func (p *GetStockResp) SetStock(val *model.StockItem) {
	p.Stock = val
}

func (p *GetStockResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetStockResp) IsSetStock() bool {
	return p.Stock != nil
}

func (p *GetStockResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetStockResp(%+v)", *p)
}

var fieldIDToName_GetStockResp = map[int16]string{
	1: "base",
	2: "stock",
}

type GetStocksReq struct {
	SkuIds []int64 `thrift:"skuIds,1" frugal:"1,default,list<i64>" json:"skuIds"`
}

func NewGetStocksReq() *GetStocksReq {
	return &GetStocksReq{}
}

func (p *GetStocksReq) InitDefault() {
}

func (p *GetStocksReq) GetSkuIds() (v []int64) {
	return p.SkuIds
}
func (p *GetStocksReq) SetSkuIds(val []int64) {
	p.SkuIds = val
}

func (p *GetStocksReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetStocksReq(%+v)", *p)
}

var fieldIDToName_GetStocksReq = map[int16]string{
	1: "skuIds",
}

type GetStocksResp struct {
	Base   *model.BaseResp    `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
	Stocks []*model.StockItem `thrift:"stocks,2" frugal:"2,default,list<model.StockItem>" json:"stocks"`
}

func NewGetStocksResp() *GetStocksResp {
	return &GetStocksResp{}
}

func (p *GetStocksResp) InitDefault() {
}

var GetStocksResp_Base_DEFAULT *model.BaseResp

func (p *GetStocksResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return GetStocksResp_Base_DEFAULT
	}
	return p.Base
}

func (p *GetStocksResp) GetStocks() (v []*model.StockItem) {
	return p.Stocks
}
func (p *GetStocksResp) SetBase(val *model.BaseResp) {
	p.Base = val
}
func (p *GetStocksResp) SetStocks(val []*model.StockItem) {
	p.Stocks = val
}

func (p *GetStocksResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetStocksResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetStocksResp(%+v)", *p)
}

var fieldIDToName_GetStocksResp = map[int16]string{
	1: "base",
	2: "stocks",
}

type CreateStockReq struct {
	SkuId int64 `thrift:"skuId,1" frugal:"1,default,i64" json:"skuId"`
	Count int32 `thrift:"count,2" frugal:"2,default,i32" json:"count"`
}

func NewCreateStockReq() *CreateStockReq {
	return &CreateStockReq{}
}

func (p *CreateStockReq) InitDefault() {
}

func (p *CreateStockReq) GetSkuId() (v int64) {
	return p.SkuId
}

func (p *CreateStockReq) GetCount() (v int32) {
	return p.Count
}
func (p *CreateStockReq) SetSkuId(val int64) {
	p.SkuId = val
}
func (p *CreateStockReq) SetCount(val int32) {
	p.Count = val
}

func (p *CreateStockReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateStockReq(%+v)", *p)
}

var fieldIDToName_CreateStockReq = map[int16]string{
	1: "skuId",
	2: "count",
}

type CreateStockResp struct {
	Base *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
}

func NewCreateStockResp() *CreateStockResp {
	return &CreateStockResp{}
}

func (p *CreateStockResp) InitDefault() {
}

var CreateStockResp_Base_DEFAULT *model.BaseResp

func (p *CreateStockResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return CreateStockResp_Base_DEFAULT
	}
	return p.Base
}
func (p *CreateStockResp) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *CreateStockResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *CreateStockResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateStockResp(%+v)", *p)
}

var fieldIDToName_CreateStockResp = map[int16]string{
	1: "base",
}

type AddStockReq struct {
	SkuId int64 `thrift:"skuId,1" frugal:"1,default,i64" json:"skuId"`
	Count int32 `thrift:"count,2" frugal:"2,default,i32" json:"count"`
}

func NewAddStockReq() *AddStockReq {
	return &AddStockReq{}
}

func (p *AddStockReq) InitDefault() {
}

func (p *AddStockReq) GetSkuId() (v int64) {
	return p.SkuId
}

func (p *AddStockReq) GetCount() (v int32) {
	return p.Count
}
func (p *AddStockReq) SetSkuId(val int64) {
	p.SkuId = val
}
func (p *AddStockReq) SetCount(val int32) {
	p.Count = val
}

func (p *AddStockReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddStockReq(%+v)", *p)
}

var fieldIDToName_AddStockReq = map[int16]string{
	1: "skuId",
	2: "count",
}

type AddStockResp struct {
	Base *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
}

func NewAddStockResp() *AddStockResp {
	return &AddStockResp{}
}

func (p *AddStockResp) InitDefault() {
}

var AddStockResp_Base_DEFAULT *model.BaseResp

func (p *AddStockResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return AddStockResp_Base_DEFAULT
	}
	return p.Base
}
func (p *AddStockResp) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *AddStockResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *AddStockResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddStockResp(%+v)", *p)
}

var fieldIDToName_AddStockResp = map[int16]string{
	1: "base",
}

type LockStockReq struct {
	OrderId    int64              `thrift:"orderId,1" frugal:"1,default,i64" json:"orderId"`
	StockItems []*model.StockItem `thrift:"stockItems,2" frugal:"2,default,list<model.StockItem>" json:"stockItems"`
}

func NewLockStockReq() *LockStockReq {
	return &LockStockReq{}
}

func (p *LockStockReq) InitDefault() {
}

func (p *LockStockReq) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *LockStockReq) GetStockItems() (v []*model.StockItem) {
	return p.StockItems
}
func (p *LockStockReq) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *LockStockReq) SetStockItems(val []*model.StockItem) {
	p.StockItems = val
}

func (p *LockStockReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LockStockReq(%+v)", *p)
}

var fieldIDToName_LockStockReq = map[int16]string{
	1: "orderId",
	2: "stockItems",
}

type LockStockResp struct {
	Base *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
}

func NewLockStockResp() *LockStockResp {
	return &LockStockResp{}
}

func (p *LockStockResp) InitDefault() {
}

var LockStockResp_Base_DEFAULT *model.BaseResp

func (p *LockStockResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return LockStockResp_Base_DEFAULT
	}
	return p.Base
}
func (p *LockStockResp) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *LockStockResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *LockStockResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LockStockResp(%+v)", *p)
}

var fieldIDToName_LockStockResp = map[int16]string{
	1: "base",
}

type UnlockStockReq struct {
	OrderId    int64              `thrift:"orderId,1" frugal:"1,default,i64" json:"orderId"`
	StockItems []*model.StockItem `thrift:"stockItems,2" frugal:"2,default,list<model.StockItem>" json:"stockItems"`
}

func NewUnlockStockReq() *UnlockStockReq {
	return &UnlockStockReq{}
}

func (p *UnlockStockReq) InitDefault() {
}

func (p *UnlockStockReq) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *UnlockStockReq) GetStockItems() (v []*model.StockItem) {
	return p.StockItems
}
func (p *UnlockStockReq) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *UnlockStockReq) SetStockItems(val []*model.StockItem) {
	p.StockItems = val
}

func (p *UnlockStockReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UnlockStockReq(%+v)", *p)
}

var fieldIDToName_UnlockStockReq = map[int16]string{
	1: "orderId",
	2: "stockItems",
}

type UnlockStockResp struct {
	Base *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
}

func NewUnlockStockResp() *UnlockStockResp {
	return &UnlockStockResp{}
}

func (p *UnlockStockResp) InitDefault() {
}

var UnlockStockResp_Base_DEFAULT *model.BaseResp

func (p *UnlockStockResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return UnlockStockResp_Base_DEFAULT
	}
	return p.Base
}
func (p *UnlockStockResp) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *UnlockStockResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *UnlockStockResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UnlockStockResp(%+v)", *p)
}

var fieldIDToName_UnlockStockResp = map[int16]string{
	1: "base",
}

type DeductStockReq struct {
	OrderId    int64              `thrift:"orderId,1" frugal:"1,default,i64" json:"orderId"`
	StockItems []*model.StockItem `thrift:"stockItems,2" frugal:"2,default,list<model.StockItem>" json:"stockItems"`
}

func NewDeductStockReq() *DeductStockReq {
	return &DeductStockReq{}
}

func (p *DeductStockReq) InitDefault() {
}

func (p *DeductStockReq) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *DeductStockReq) GetStockItems() (v []*model.StockItem) {
	return p.StockItems
}
func (p *DeductStockReq) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *DeductStockReq) SetStockItems(val []*model.StockItem) {
	p.StockItems = val
}

func (p *DeductStockReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeductStockReq(%+v)", *p)
}

var fieldIDToName_DeductStockReq = map[int16]string{
	1: "orderId",
	2: "stockItems",
}

type DeductStockResp struct {
	Base *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
}

func NewDeductStockResp() *DeductStockResp {
	return &DeductStockResp{}
}

func (p *DeductStockResp) InitDefault() {
}

var DeductStockResp_Base_DEFAULT *model.BaseResp

func (p *DeductStockResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return DeductStockResp_Base_DEFAULT
	}
	return p.Base
}
func (p *DeductStockResp) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *DeductStockResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *DeductStockResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeductStockResp(%+v)", *p)
}

var fieldIDToName_DeductStockResp = map[int16]string{
	1: "base",
}

type StockService interface {
	CreateStock(ctx context.Context, req *CreateStockReq) (r *CreateStockResp, err error)

	AddStock(ctx context.Context, req *AddStockReq) (r *AddStockResp, err error)

	GetStock(ctx context.Context, req *GetStockReq) (r *GetStockResp, err error)

	GetStocks(ctx context.Context, req *GetStocksReq) (r *GetStocksResp, err error)

	LockStock(ctx context.Context, req *LockStockReq) (r *LockStockResp, err error)

	UnlockStock(ctx context.Context, req *UnlockStockReq) (r *UnlockStockResp, err error)

	DeductStock(ctx context.Context, req *DeductStockReq) (r *DeductStockResp, err error)
}

type StockServiceCreateStockArgs struct {
	Req *CreateStockReq `thrift:"req,1" frugal:"1,default,CreateStockReq" json:"req"`
}

func NewStockServiceCreateStockArgs() *StockServiceCreateStockArgs {
	return &StockServiceCreateStockArgs{}
}

func (p *StockServiceCreateStockArgs) InitDefault() {
}

var StockServiceCreateStockArgs_Req_DEFAULT *CreateStockReq

func (p *StockServiceCreateStockArgs) GetReq() (v *CreateStockReq) {
	if !p.IsSetReq() {
		return StockServiceCreateStockArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *StockServiceCreateStockArgs) SetReq(val *CreateStockReq) {
	p.Req = val
}

func (p *StockServiceCreateStockArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *StockServiceCreateStockArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StockServiceCreateStockArgs(%+v)", *p)
}

var fieldIDToName_StockServiceCreateStockArgs = map[int16]string{
	1: "req",
}

type StockServiceCreateStockResult struct {
	Success *CreateStockResp `thrift:"success,0,optional" frugal:"0,optional,CreateStockResp" json:"success,omitempty"`
}

func NewStockServiceCreateStockResult() *StockServiceCreateStockResult {
	return &StockServiceCreateStockResult{}
}

func (p *StockServiceCreateStockResult) InitDefault() {
}

var StockServiceCreateStockResult_Success_DEFAULT *CreateStockResp

func (p *StockServiceCreateStockResult) GetSuccess() (v *CreateStockResp) {
	if !p.IsSetSuccess() {
		return StockServiceCreateStockResult_Success_DEFAULT
	}
	return p.Success
}
func (p *StockServiceCreateStockResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateStockResp)
}

func (p *StockServiceCreateStockResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *StockServiceCreateStockResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StockServiceCreateStockResult(%+v)", *p)
}

var fieldIDToName_StockServiceCreateStockResult = map[int16]string{
	0: "success",
}

type StockServiceAddStockArgs struct {
	Req *AddStockReq `thrift:"req,1" frugal:"1,default,AddStockReq" json:"req"`
}

func NewStockServiceAddStockArgs() *StockServiceAddStockArgs {
	return &StockServiceAddStockArgs{}
}

func (p *StockServiceAddStockArgs) InitDefault() {
}

var StockServiceAddStockArgs_Req_DEFAULT *AddStockReq

func (p *StockServiceAddStockArgs) GetReq() (v *AddStockReq) {
	if !p.IsSetReq() {
		return StockServiceAddStockArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *StockServiceAddStockArgs) SetReq(val *AddStockReq) {
	p.Req = val
}

func (p *StockServiceAddStockArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *StockServiceAddStockArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StockServiceAddStockArgs(%+v)", *p)
}

var fieldIDToName_StockServiceAddStockArgs = map[int16]string{
	1: "req",
}

type StockServiceAddStockResult struct {
	Success *AddStockResp `thrift:"success,0,optional" frugal:"0,optional,AddStockResp" json:"success,omitempty"`
}

func NewStockServiceAddStockResult() *StockServiceAddStockResult {
	return &StockServiceAddStockResult{}
}

func (p *StockServiceAddStockResult) InitDefault() {
}

var StockServiceAddStockResult_Success_DEFAULT *AddStockResp

func (p *StockServiceAddStockResult) GetSuccess() (v *AddStockResp) {
	if !p.IsSetSuccess() {
		return StockServiceAddStockResult_Success_DEFAULT
	}
	return p.Success
}
func (p *StockServiceAddStockResult) SetSuccess(x interface{}) {
	p.Success = x.(*AddStockResp)
}

func (p *StockServiceAddStockResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *StockServiceAddStockResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StockServiceAddStockResult(%+v)", *p)
}

var fieldIDToName_StockServiceAddStockResult = map[int16]string{
	0: "success",
}

type StockServiceGetStockArgs struct {
	Req *GetStockReq `thrift:"req,1" frugal:"1,default,GetStockReq" json:"req"`
}

func NewStockServiceGetStockArgs() *StockServiceGetStockArgs {
	return &StockServiceGetStockArgs{}
}

func (p *StockServiceGetStockArgs) InitDefault() {
}

var StockServiceGetStockArgs_Req_DEFAULT *GetStockReq

func (p *StockServiceGetStockArgs) GetReq() (v *GetStockReq) {
	if !p.IsSetReq() {
		return StockServiceGetStockArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *StockServiceGetStockArgs) SetReq(val *GetStockReq) {
	p.Req = val
}

func (p *StockServiceGetStockArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *StockServiceGetStockArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StockServiceGetStockArgs(%+v)", *p)
}

var fieldIDToName_StockServiceGetStockArgs = map[int16]string{
	1: "req",
}

type StockServiceGetStockResult struct {
	Success *GetStockResp `thrift:"success,0,optional" frugal:"0,optional,GetStockResp" json:"success,omitempty"`
}

func NewStockServiceGetStockResult() *StockServiceGetStockResult {
	return &StockServiceGetStockResult{}
}

func (p *StockServiceGetStockResult) InitDefault() {
}

var StockServiceGetStockResult_Success_DEFAULT *GetStockResp

func (p *StockServiceGetStockResult) GetSuccess() (v *GetStockResp) {
	if !p.IsSetSuccess() {
		return StockServiceGetStockResult_Success_DEFAULT
	}
	return p.Success
}
func (p *StockServiceGetStockResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetStockResp)
}

func (p *StockServiceGetStockResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *StockServiceGetStockResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StockServiceGetStockResult(%+v)", *p)
}

var fieldIDToName_StockServiceGetStockResult = map[int16]string{
	0: "success",
}

type StockServiceGetStocksArgs struct {
	Req *GetStocksReq `thrift:"req,1" frugal:"1,default,GetStocksReq" json:"req"`
}

func NewStockServiceGetStocksArgs() *StockServiceGetStocksArgs {
	return &StockServiceGetStocksArgs{}
}

func (p *StockServiceGetStocksArgs) InitDefault() {
}

var StockServiceGetStocksArgs_Req_DEFAULT *GetStocksReq

func (p *StockServiceGetStocksArgs) GetReq() (v *GetStocksReq) {
	if !p.IsSetReq() {
		return StockServiceGetStocksArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *StockServiceGetStocksArgs) SetReq(val *GetStocksReq) {
	p.Req = val
}

func (p *StockServiceGetStocksArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *StockServiceGetStocksArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StockServiceGetStocksArgs(%+v)", *p)
}

var fieldIDToName_StockServiceGetStocksArgs = map[int16]string{
	1: "req",
}

type StockServiceGetStocksResult struct {
	Success *GetStocksResp `thrift:"success,0,optional" frugal:"0,optional,GetStocksResp" json:"success,omitempty"`
}

func NewStockServiceGetStocksResult() *StockServiceGetStocksResult {
	return &StockServiceGetStocksResult{}
}

func (p *StockServiceGetStocksResult) InitDefault() {
}

var StockServiceGetStocksResult_Success_DEFAULT *GetStocksResp

func (p *StockServiceGetStocksResult) GetSuccess() (v *GetStocksResp) {
	if !p.IsSetSuccess() {
		return StockServiceGetStocksResult_Success_DEFAULT
	}
	return p.Success
}
func (p *StockServiceGetStocksResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetStocksResp)
}

func (p *StockServiceGetStocksResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *StockServiceGetStocksResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StockServiceGetStocksResult(%+v)", *p)
}

var fieldIDToName_StockServiceGetStocksResult = map[int16]string{
	0: "success",
}

type StockServiceLockStockArgs struct {
	Req *LockStockReq `thrift:"req,1" frugal:"1,default,LockStockReq" json:"req"`
}

func NewStockServiceLockStockArgs() *StockServiceLockStockArgs {
	return &StockServiceLockStockArgs{}
}

func (p *StockServiceLockStockArgs) InitDefault() {
}

var StockServiceLockStockArgs_Req_DEFAULT *LockStockReq

func (p *StockServiceLockStockArgs) GetReq() (v *LockStockReq) {
	if !p.IsSetReq() {
		return StockServiceLockStockArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *StockServiceLockStockArgs) SetReq(val *LockStockReq) {
	p.Req = val
}

func (p *StockServiceLockStockArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *StockServiceLockStockArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StockServiceLockStockArgs(%+v)", *p)
}

var fieldIDToName_StockServiceLockStockArgs = map[int16]string{
	1: "req",
}

type StockServiceLockStockResult struct {
	Success *LockStockResp `thrift:"success,0,optional" frugal:"0,optional,LockStockResp" json:"success,omitempty"`
}

func NewStockServiceLockStockResult() *StockServiceLockStockResult {
	return &StockServiceLockStockResult{}
}

func (p *StockServiceLockStockResult) InitDefault() {
}

var StockServiceLockStockResult_Success_DEFAULT *LockStockResp

func (p *StockServiceLockStockResult) GetSuccess() (v *LockStockResp) {
	if !p.IsSetSuccess() {
		return StockServiceLockStockResult_Success_DEFAULT
	}
	return p.Success
}
func (p *StockServiceLockStockResult) SetSuccess(x interface{}) {
	p.Success = x.(*LockStockResp)
}

func (p *StockServiceLockStockResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *StockServiceLockStockResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StockServiceLockStockResult(%+v)", *p)
}

var fieldIDToName_StockServiceLockStockResult = map[int16]string{
	0: "success",
}

type StockServiceUnlockStockArgs struct {
	Req *UnlockStockReq `thrift:"req,1" frugal:"1,default,UnlockStockReq" json:"req"`
}

func NewStockServiceUnlockStockArgs() *StockServiceUnlockStockArgs {
	return &StockServiceUnlockStockArgs{}
}

func (p *StockServiceUnlockStockArgs) InitDefault() {
}

var StockServiceUnlockStockArgs_Req_DEFAULT *UnlockStockReq

func (p *StockServiceUnlockStockArgs) GetReq() (v *UnlockStockReq) {
	if !p.IsSetReq() {
		return StockServiceUnlockStockArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *StockServiceUnlockStockArgs) SetReq(val *UnlockStockReq) {
	p.Req = val
}

func (p *StockServiceUnlockStockArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *StockServiceUnlockStockArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StockServiceUnlockStockArgs(%+v)", *p)
}

var fieldIDToName_StockServiceUnlockStockArgs = map[int16]string{
	1: "req",
}

type StockServiceUnlockStockResult struct {
	Success *UnlockStockResp `thrift:"success,0,optional" frugal:"0,optional,UnlockStockResp" json:"success,omitempty"`
}

func NewStockServiceUnlockStockResult() *StockServiceUnlockStockResult {
	return &StockServiceUnlockStockResult{}
}

func (p *StockServiceUnlockStockResult) InitDefault() {
}

var StockServiceUnlockStockResult_Success_DEFAULT *UnlockStockResp

func (p *StockServiceUnlockStockResult) GetSuccess() (v *UnlockStockResp) {
	if !p.IsSetSuccess() {
		return StockServiceUnlockStockResult_Success_DEFAULT
	}
	return p.Success
}
func (p *StockServiceUnlockStockResult) SetSuccess(x interface{}) {
	p.Success = x.(*UnlockStockResp)
}

func (p *StockServiceUnlockStockResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *StockServiceUnlockStockResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StockServiceUnlockStockResult(%+v)", *p)
}

var fieldIDToName_StockServiceUnlockStockResult = map[int16]string{
	0: "success",
}

type StockServiceDeductStockArgs struct {
	Req *DeductStockReq `thrift:"req,1" frugal:"1,default,DeductStockReq" json:"req"`
}

func NewStockServiceDeductStockArgs() *StockServiceDeductStockArgs {
	return &StockServiceDeductStockArgs{}
}

func (p *StockServiceDeductStockArgs) InitDefault() {
}

var StockServiceDeductStockArgs_Req_DEFAULT *DeductStockReq

func (p *StockServiceDeductStockArgs) GetReq() (v *DeductStockReq) {
	if !p.IsSetReq() {
		return StockServiceDeductStockArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *StockServiceDeductStockArgs) SetReq(val *DeductStockReq) {
	p.Req = val
}

func (p *StockServiceDeductStockArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *StockServiceDeductStockArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StockServiceDeductStockArgs(%+v)", *p)
}

var fieldIDToName_StockServiceDeductStockArgs = map[int16]string{
	1: "req",
}

type StockServiceDeductStockResult struct {
	Success *DeductStockResp `thrift:"success,0,optional" frugal:"0,optional,DeductStockResp" json:"success,omitempty"`
}

func NewStockServiceDeductStockResult() *StockServiceDeductStockResult {
	return &StockServiceDeductStockResult{}
}

func (p *StockServiceDeductStockResult) InitDefault() {
}

var StockServiceDeductStockResult_Success_DEFAULT *DeductStockResp

func (p *StockServiceDeductStockResult) GetSuccess() (v *DeductStockResp) {
	if !p.IsSetSuccess() {
		return StockServiceDeductStockResult_Success_DEFAULT
	}
	return p.Success
}
func (p *StockServiceDeductStockResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeductStockResp)
}

func (p *StockServiceDeductStockResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *StockServiceDeductStockResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StockServiceDeductStockResult(%+v)", *p)
}

var fieldIDToName_StockServiceDeductStockResult = map[int16]string{
	0: "success",
}
