// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package model

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type SpuStatus int64

const (
	SpuStatus_UNKNOWN SpuStatus = 0
	SpuStatus_ONLINE  SpuStatus = 1
	SpuStatus_OFFLINE SpuStatus = 2
	SpuStatus_DELETED SpuStatus = 3
)

func (p SpuStatus) String() string {
	switch p {
	case SpuStatus_UNKNOWN:
		return "UNKNOWN"
	case SpuStatus_ONLINE:
		return "ONLINE"
	case SpuStatus_OFFLINE:
		return "OFFLINE"
	case SpuStatus_DELETED:
		return "DELETED"
	}
	return "<UNSET>"
}

func SpuStatusFromString(s string) (SpuStatus, error) {
	switch s {
	case "UNKNOWN":
		return SpuStatus_UNKNOWN, nil
	case "ONLINE":
		return SpuStatus_ONLINE, nil
	case "OFFLINE":
		return SpuStatus_OFFLINE, nil
	case "DELETED":
		return SpuStatus_DELETED, nil
	}
	return SpuStatus(0), fmt.Errorf("not a valid SpuStatus string")
}

func SpuStatusPtr(v SpuStatus) *SpuStatus { return &v }
func (p *SpuStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = SpuStatus(result.Int64)
	return
}

func (p *SpuStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type BaseResp struct {
	Code    int64  `thrift:"code,1" frugal:"1,default,i64" json:"code"`
	Message string `thrift:"message,2" frugal:"2,default,string" json:"message"`
}

func NewBaseResp() *BaseResp {
	return &BaseResp{}
}

func (p *BaseResp) InitDefault() {
}

func (p *BaseResp) GetCode() (v int64) {
	return p.Code
}

func (p *BaseResp) GetMessage() (v string) {
	return p.Message
}
func (p *BaseResp) SetCode(val int64) {
	p.Code = val
}
func (p *BaseResp) SetMessage(val string) {
	p.Message = val
}

func (p *BaseResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BaseResp(%+v)", *p)
}

var fieldIDToName_BaseResp = map[int16]string{
	1: "code",
	2: "message",
}

type UserInfo struct {
	Id       int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Username string `thrift:"username,2" frugal:"2,default,string" json:"username"`
	Email    string `thrift:"email,3" frugal:"3,default,string" json:"email"`
	Avatar   string `thrift:"avatar,4" frugal:"4,default,string" json:"avatar"`
	Role     int64  `thrift:"role,5" frugal:"5,default,i64" json:"role"`
}

func NewUserInfo() *UserInfo {
	return &UserInfo{}
}

func (p *UserInfo) InitDefault() {
}

func (p *UserInfo) GetId() (v int64) {
	return p.Id
}

func (p *UserInfo) GetUsername() (v string) {
	return p.Username
}

func (p *UserInfo) GetEmail() (v string) {
	return p.Email
}

func (p *UserInfo) GetAvatar() (v string) {
	return p.Avatar
}

func (p *UserInfo) GetRole() (v int64) {
	return p.Role
}
func (p *UserInfo) SetId(val int64) {
	p.Id = val
}
func (p *UserInfo) SetUsername(val string) {
	p.Username = val
}
func (p *UserInfo) SetEmail(val string) {
	p.Email = val
}
func (p *UserInfo) SetAvatar(val string) {
	p.Avatar = val
}
func (p *UserInfo) SetRole(val int64) {
	p.Role = val
}

func (p *UserInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserInfo(%+v)", *p)
}

var fieldIDToName_UserInfo = map[int16]string{
	1: "id",
	2: "username",
	3: "email",
	4: "avatar",
	5: "role",
}

type AddressInfo struct {
	Province  string `thrift:"province,1" frugal:"1,default,string" json:"province"`
	City      string `thrift:"city,2" frugal:"2,default,string" json:"city"`
	Detail    string `thrift:"detail,3" frugal:"3,default,string" json:"detail"`
	AddressID int64  `thrift:"addressID,4" frugal:"4,default,i64" json:"addressID"`
}

func NewAddressInfo() *AddressInfo {
	return &AddressInfo{}
}

func (p *AddressInfo) InitDefault() {
}

func (p *AddressInfo) GetProvince() (v string) {
	return p.Province
}

func (p *AddressInfo) GetCity() (v string) {
	return p.City
}

func (p *AddressInfo) GetDetail() (v string) {
	return p.Detail
}

func (p *AddressInfo) GetAddressID() (v int64) {
	return p.AddressID
}
func (p *AddressInfo) SetProvince(val string) {
	p.Province = val
}
func (p *AddressInfo) SetCity(val string) {
	p.City = val
}
func (p *AddressInfo) SetDetail(val string) {
	p.Detail = val
}
func (p *AddressInfo) SetAddressID(val int64) {
	p.AddressID = val
}

func (p *AddressInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddressInfo(%+v)", *p)
}

var fieldIDToName_AddressInfo = map[int16]string{
	1: "province",
	2: "city",
	3: "detail",
	4: "addressID",
}

type SpuInfo struct {
	Id              int64      `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	CreatorId       int64      `thrift:"creatorId,2" frugal:"2,default,i64" json:"creatorId"`
	Name            string     `thrift:"name,3" frugal:"3,default,string" json:"name"`
	Description     string     `thrift:"description,4" frugal:"4,default,string" json:"description"`
	CategoryId      int64      `thrift:"categoryId,5" frugal:"5,default,i64" json:"categoryId"`
	MainImageURL    string     `thrift:"mainImageURL,6" frugal:"6,default,string" json:"mainImageURL"`
	SliderImageURLs string     `thrift:"sliderImageURLs,7" frugal:"7,default,string" json:"sliderImageURLs"`
	Status          SpuStatus  `thrift:"status,8" frugal:"8,default,SpuStatus" json:"status"`
	Sku             []*SkuInfo `thrift:"sku,9" frugal:"9,default,list<SkuInfo>" json:"sku"`
	CreateTime      int64      `thrift:"createTime,10" frugal:"10,default,i64" json:"createTime"`
	UpdateTime      int64      `thrift:"updateTime,11" frugal:"11,default,i64" json:"updateTime"`
	DeleteTime      int64      `thrift:"deleteTime,12" frugal:"12,default,i64" json:"deleteTime"`
}

func NewSpuInfo() *SpuInfo {
	return &SpuInfo{}
}

func (p *SpuInfo) InitDefault() {
}

func (p *SpuInfo) GetId() (v int64) {
	return p.Id
}

func (p *SpuInfo) GetCreatorId() (v int64) {
	return p.CreatorId
}

func (p *SpuInfo) GetName() (v string) {
	return p.Name
}

func (p *SpuInfo) GetDescription() (v string) {
	return p.Description
}

func (p *SpuInfo) GetCategoryId() (v int64) {
	return p.CategoryId
}

func (p *SpuInfo) GetMainImageURL() (v string) {
	return p.MainImageURL
}

func (p *SpuInfo) GetSliderImageURLs() (v string) {
	return p.SliderImageURLs
}

func (p *SpuInfo) GetStatus() (v SpuStatus) {
	return p.Status
}

func (p *SpuInfo) GetSku() (v []*SkuInfo) {
	return p.Sku
}

func (p *SpuInfo) GetCreateTime() (v int64) {
	return p.CreateTime
}

func (p *SpuInfo) GetUpdateTime() (v int64) {
	return p.UpdateTime
}

func (p *SpuInfo) GetDeleteTime() (v int64) {
	return p.DeleteTime
}
func (p *SpuInfo) SetId(val int64) {
	p.Id = val
}
func (p *SpuInfo) SetCreatorId(val int64) {
	p.CreatorId = val
}
func (p *SpuInfo) SetName(val string) {
	p.Name = val
}
func (p *SpuInfo) SetDescription(val string) {
	p.Description = val
}
func (p *SpuInfo) SetCategoryId(val int64) {
	p.CategoryId = val
}
func (p *SpuInfo) SetMainImageURL(val string) {
	p.MainImageURL = val
}
func (p *SpuInfo) SetSliderImageURLs(val string) {
	p.SliderImageURLs = val
}
func (p *SpuInfo) SetStatus(val SpuStatus) {
	p.Status = val
}
func (p *SpuInfo) SetSku(val []*SkuInfo) {
	p.Sku = val
}
func (p *SpuInfo) SetCreateTime(val int64) {
	p.CreateTime = val
}
func (p *SpuInfo) SetUpdateTime(val int64) {
	p.UpdateTime = val
}
func (p *SpuInfo) SetDeleteTime(val int64) {
	p.DeleteTime = val
}

func (p *SpuInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SpuInfo(%+v)", *p)
}

var fieldIDToName_SpuInfo = map[int16]string{
	1:  "id",
	2:  "creatorId",
	3:  "name",
	4:  "description",
	5:  "categoryId",
	6:  "mainImageURL",
	7:  "sliderImageURLs",
	8:  "status",
	9:  "sku",
	10: "createTime",
	11: "updateTime",
	12: "deleteTime",
}

type SkuInfo struct {
	Id          int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	SpuId       int64  `thrift:"spuId,2" frugal:"2,default,i64" json:"spuId"`
	Name        string `thrift:"name,3" frugal:"3,default,string" json:"name"`
	Description string `thrift:"description,4" frugal:"4,default,string" json:"description"`
	Price       int64  `thrift:"price,5" frugal:"5,default,i64" json:"price"`
	SkuImageURL string `thrift:"skuImageURL,6" frugal:"6,default,string" json:"skuImageURL"`
	Properties  string `thrift:"properties,7" frugal:"7,default,string" json:"properties"`
	CreateTime  int64  `thrift:"createTime,8" frugal:"8,default,i64" json:"createTime"`
	UpdateTime  int64  `thrift:"updateTime,9" frugal:"9,default,i64" json:"updateTime"`
	DeleteTime  int64  `thrift:"deleteTime,10" frugal:"10,default,i64" json:"deleteTime"`
}

func NewSkuInfo() *SkuInfo {
	return &SkuInfo{}
}

func (p *SkuInfo) InitDefault() {
}

func (p *SkuInfo) GetId() (v int64) {
	return p.Id
}

func (p *SkuInfo) GetSpuId() (v int64) {
	return p.SpuId
}

func (p *SkuInfo) GetName() (v string) {
	return p.Name
}

func (p *SkuInfo) GetDescription() (v string) {
	return p.Description
}

func (p *SkuInfo) GetPrice() (v int64) {
	return p.Price
}

func (p *SkuInfo) GetSkuImageURL() (v string) {
	return p.SkuImageURL
}

func (p *SkuInfo) GetProperties() (v string) {
	return p.Properties
}

func (p *SkuInfo) GetCreateTime() (v int64) {
	return p.CreateTime
}

func (p *SkuInfo) GetUpdateTime() (v int64) {
	return p.UpdateTime
}

func (p *SkuInfo) GetDeleteTime() (v int64) {
	return p.DeleteTime
}
func (p *SkuInfo) SetId(val int64) {
	p.Id = val
}
func (p *SkuInfo) SetSpuId(val int64) {
	p.SpuId = val
}
func (p *SkuInfo) SetName(val string) {
	p.Name = val
}
func (p *SkuInfo) SetDescription(val string) {
	p.Description = val
}
func (p *SkuInfo) SetPrice(val int64) {
	p.Price = val
}
func (p *SkuInfo) SetSkuImageURL(val string) {
	p.SkuImageURL = val
}
func (p *SkuInfo) SetProperties(val string) {
	p.Properties = val
}
func (p *SkuInfo) SetCreateTime(val int64) {
	p.CreateTime = val
}
func (p *SkuInfo) SetUpdateTime(val int64) {
	p.UpdateTime = val
}
func (p *SkuInfo) SetDeleteTime(val int64) {
	p.DeleteTime = val
}

func (p *SkuInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SkuInfo(%+v)", *p)
}

var fieldIDToName_SkuInfo = map[int16]string{
	1:  "id",
	2:  "spuId",
	3:  "name",
	4:  "description",
	5:  "price",
	6:  "skuImageURL",
	7:  "properties",
	8:  "createTime",
	9:  "updateTime",
	10: "deleteTime",
}

type CreateSkuItem struct {
	Name        string `thrift:"name,1" frugal:"1,default,string" json:"name"`
	Description string `thrift:"description,2" frugal:"2,default,string" json:"description"`
	Price       int64  `thrift:"price,3" frugal:"3,default,i64" json:"price"`
	Properties  string `thrift:"properties,4" frugal:"4,default,string" json:"properties"`
}

func NewCreateSkuItem() *CreateSkuItem {
	return &CreateSkuItem{}
}

func (p *CreateSkuItem) InitDefault() {
}

func (p *CreateSkuItem) GetName() (v string) {
	return p.Name
}

func (p *CreateSkuItem) GetDescription() (v string) {
	return p.Description
}

func (p *CreateSkuItem) GetPrice() (v int64) {
	return p.Price
}

func (p *CreateSkuItem) GetProperties() (v string) {
	return p.Properties
}
func (p *CreateSkuItem) SetName(val string) {
	p.Name = val
}
func (p *CreateSkuItem) SetDescription(val string) {
	p.Description = val
}
func (p *CreateSkuItem) SetPrice(val int64) {
	p.Price = val
}
func (p *CreateSkuItem) SetProperties(val string) {
	p.Properties = val
}

func (p *CreateSkuItem) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateSkuItem(%+v)", *p)
}

var fieldIDToName_CreateSkuItem = map[int16]string{
	1: "name",
	2: "description",
	3: "price",
	4: "properties",
}

type CategoryInfo struct {
	Id         int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Name       string `thrift:"name,2" frugal:"2,default,string" json:"name"`
	CreateTime int64  `thrift:"createTime,3" frugal:"3,default,i64" json:"createTime"`
	UpdateTime int64  `thrift:"updateTime,4" frugal:"4,default,i64" json:"updateTime"`
	DeleteTime int64  `thrift:"deleteTime,5" frugal:"5,default,i64" json:"deleteTime"`
}

func NewCategoryInfo() *CategoryInfo {
	return &CategoryInfo{}
}

func (p *CategoryInfo) InitDefault() {
}

func (p *CategoryInfo) GetId() (v int64) {
	return p.Id
}

func (p *CategoryInfo) GetName() (v string) {
	return p.Name
}

func (p *CategoryInfo) GetCreateTime() (v int64) {
	return p.CreateTime
}

func (p *CategoryInfo) GetUpdateTime() (v int64) {
	return p.UpdateTime
}

func (p *CategoryInfo) GetDeleteTime() (v int64) {
	return p.DeleteTime
}
func (p *CategoryInfo) SetId(val int64) {
	p.Id = val
}
func (p *CategoryInfo) SetName(val string) {
	p.Name = val
}
func (p *CategoryInfo) SetCreateTime(val int64) {
	p.CreateTime = val
}
func (p *CategoryInfo) SetUpdateTime(val int64) {
	p.UpdateTime = val
}
func (p *CategoryInfo) SetDeleteTime(val int64) {
	p.DeleteTime = val
}

func (p *CategoryInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CategoryInfo(%+v)", *p)
}

var fieldIDToName_CategoryInfo = map[int16]string{
	1: "id",
	2: "name",
	3: "createTime",
	4: "updateTime",
	5: "deleteTime",
}

type StockItem struct {
	SkuId int64 `thrift:"skuId,1" frugal:"1,default,i64" json:"skuId"`
	Count int32 `thrift:"count,2" frugal:"2,default,i32" json:"count"`
}

func NewStockItem() *StockItem {
	return &StockItem{}
}

func (p *StockItem) InitDefault() {
}

func (p *StockItem) GetSkuId() (v int64) {
	return p.SkuId
}

func (p *StockItem) GetCount() (v int32) {
	return p.Count
}
func (p *StockItem) SetSkuId(val int64) {
	p.SkuId = val
}
func (p *StockItem) SetCount(val int32) {
	p.Count = val
}

func (p *StockItem) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StockItem(%+v)", *p)
}

var fieldIDToName_StockItem = map[int16]string{
	1: "skuId",
	2: "count",
}

type CartItem struct {
	SkuId      int64 `thrift:"skuId,1" frugal:"1,default,i64" json:"skuId"`
	Count      int32 `thrift:"count,2" frugal:"2,default,i32" json:"count"`
	UpdateTime int64 `thrift:"updateTime,3" frugal:"3,default,i64" json:"updateTime"`
}

func NewCartItem() *CartItem {
	return &CartItem{}
}

func (p *CartItem) InitDefault() {
}

func (p *CartItem) GetSkuId() (v int64) {
	return p.SkuId
}

func (p *CartItem) GetCount() (v int32) {
	return p.Count
}

func (p *CartItem) GetUpdateTime() (v int64) {
	return p.UpdateTime
}
func (p *CartItem) SetSkuId(val int64) {
	p.SkuId = val
}
func (p *CartItem) SetCount(val int32) {
	p.Count = val
}
func (p *CartItem) SetUpdateTime(val int64) {
	p.UpdateTime = val
}

func (p *CartItem) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CartItem(%+v)", *p)
}

var fieldIDToName_CartItem = map[int16]string{
	1: "skuId",
	2: "count",
	3: "updateTime",
}

type CouponBatchInfo struct {
	Id         int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	BatchName  string `thrift:"batchName,2" frugal:"2,default,string" json:"batchName"`
	Remark     string `thrift:"remark,3" frugal:"3,default,string" json:"remark"`
	Type       int32  `thrift:"type,4" frugal:"4,default,i32" json:"type"`
	Threshold  int64  `thrift:"threshold,5" frugal:"5,default,i64" json:"threshold"`
	Amount     int64  `thrift:"amount,6" frugal:"6,default,i64" json:"amount"`
	Rate       int64  `thrift:"rate,7" frugal:"7,default,i64" json:"rate"`
	Total      int64  `thrift:"total,8" frugal:"8,default,i64" json:"total"`
	UsedNum    int64  `thrift:"usedNum,9" frugal:"9,default,i64" json:"usedNum"`
	StartTime  int64  `thrift:"startTime,10" frugal:"10,default,i64" json:"startTime"`
	EndTime    int64  `thrift:"endTime,11" frugal:"11,default,i64" json:"endTime"`
	Duration   int64  `thrift:"duration,12" frugal:"12,default,i64" json:"duration"`
	CreateTime int64  `thrift:"createTime,13" frugal:"13,default,i64" json:"createTime"`
	UpdateTime int64  `thrift:"updateTime,14" frugal:"14,default,i64" json:"updateTime"`
}

func NewCouponBatchInfo() *CouponBatchInfo {
	return &CouponBatchInfo{}
}

func (p *CouponBatchInfo) InitDefault() {
}

func (p *CouponBatchInfo) GetId() (v int64) {
	return p.Id
}

func (p *CouponBatchInfo) GetBatchName() (v string) {
	return p.BatchName
}

func (p *CouponBatchInfo) GetRemark() (v string) {
	return p.Remark
}

func (p *CouponBatchInfo) GetType() (v int32) {
	return p.Type
}

func (p *CouponBatchInfo) GetThreshold() (v int64) {
	return p.Threshold
}

func (p *CouponBatchInfo) GetAmount() (v int64) {
	return p.Amount
}

func (p *CouponBatchInfo) GetRate() (v int64) {
	return p.Rate
}

func (p *CouponBatchInfo) GetTotal() (v int64) {
	return p.Total
}

func (p *CouponBatchInfo) GetUsedNum() (v int64) {
	return p.UsedNum
}

func (p *CouponBatchInfo) GetStartTime() (v int64) {
	return p.StartTime
}

func (p *CouponBatchInfo) GetEndTime() (v int64) {
	return p.EndTime
}

func (p *CouponBatchInfo) GetDuration() (v int64) {
	return p.Duration
}

func (p *CouponBatchInfo) GetCreateTime() (v int64) {
	return p.CreateTime
}

func (p *CouponBatchInfo) GetUpdateTime() (v int64) {
	return p.UpdateTime
}
func (p *CouponBatchInfo) SetId(val int64) {
	p.Id = val
}
func (p *CouponBatchInfo) SetBatchName(val string) {
	p.BatchName = val
}
func (p *CouponBatchInfo) SetRemark(val string) {
	p.Remark = val
}
func (p *CouponBatchInfo) SetType(val int32) {
	p.Type = val
}
func (p *CouponBatchInfo) SetThreshold(val int64) {
	p.Threshold = val
}
func (p *CouponBatchInfo) SetAmount(val int64) {
	p.Amount = val
}
func (p *CouponBatchInfo) SetRate(val int64) {
	p.Rate = val
}
func (p *CouponBatchInfo) SetTotal(val int64) {
	p.Total = val
}
func (p *CouponBatchInfo) SetUsedNum(val int64) {
	p.UsedNum = val
}
func (p *CouponBatchInfo) SetStartTime(val int64) {
	p.StartTime = val
}
func (p *CouponBatchInfo) SetEndTime(val int64) {
	p.EndTime = val
}
func (p *CouponBatchInfo) SetDuration(val int64) {
	p.Duration = val
}
func (p *CouponBatchInfo) SetCreateTime(val int64) {
	p.CreateTime = val
}
func (p *CouponBatchInfo) SetUpdateTime(val int64) {
	p.UpdateTime = val
}

func (p *CouponBatchInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CouponBatchInfo(%+v)", *p)
}

var fieldIDToName_CouponBatchInfo = map[int16]string{
	1:  "id",
	2:  "batchName",
	3:  "remark",
	4:  "type",
	5:  "threshold",
	6:  "amount",
	7:  "rate",
	8:  "total",
	9:  "usedNum",
	10: "startTime",
	11: "endTime",
	12: "duration",
	13: "createTime",
	14: "updateTime",
}

type CouponInfo struct {
	Id         int64 `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	BatchId    int64 `thrift:"batchId,2" frugal:"2,default,i64" json:"batchId"`
	UserId     int64 `thrift:"userId,3" frugal:"3,default,i64" json:"userId"`
	OrderId    int64 `thrift:"orderId,4" frugal:"4,default,i64" json:"orderId"`
	Status     int64 `thrift:"status,5" frugal:"5,default,i64" json:"status"`
	Type       int32 `thrift:"type,6" frugal:"6,default,i32" json:"type"`
	Threshold  int64 `thrift:"threshold,7" frugal:"7,default,i64" json:"threshold"`
	Amount     int64 `thrift:"amount,8" frugal:"8,default,i64" json:"amount"`
	Rate       int64 `thrift:"rate,9" frugal:"9,default,i64" json:"rate"`
	CreateTime int64 `thrift:"createTime,10" frugal:"10,default,i64" json:"createTime"`
	ExpiredAt  int64 `thrift:"expiredAt,11" frugal:"11,default,i64" json:"expiredAt"`
	UsedAt     int64 `thrift:"usedAt,12" frugal:"12,default,i64" json:"usedAt"`
}

func NewCouponInfo() *CouponInfo {
	return &CouponInfo{}
}

func (p *CouponInfo) InitDefault() {
}

func (p *CouponInfo) GetId() (v int64) {
	return p.Id
}

func (p *CouponInfo) GetBatchId() (v int64) {
	return p.BatchId
}

func (p *CouponInfo) GetUserId() (v int64) {
	return p.UserId
}

func (p *CouponInfo) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *CouponInfo) GetStatus() (v int64) {
	return p.Status
}

func (p *CouponInfo) GetType() (v int32) {
	return p.Type
}

func (p *CouponInfo) GetThreshold() (v int64) {
	return p.Threshold
}

func (p *CouponInfo) GetAmount() (v int64) {
	return p.Amount
}

func (p *CouponInfo) GetRate() (v int64) {
	return p.Rate
}

func (p *CouponInfo) GetCreateTime() (v int64) {
	return p.CreateTime
}

func (p *CouponInfo) GetExpiredAt() (v int64) {
	return p.ExpiredAt
}

func (p *CouponInfo) GetUsedAt() (v int64) {
	return p.UsedAt
}
func (p *CouponInfo) SetId(val int64) {
	p.Id = val
}
func (p *CouponInfo) SetBatchId(val int64) {
	p.BatchId = val
}
func (p *CouponInfo) SetUserId(val int64) {
	p.UserId = val
}
func (p *CouponInfo) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *CouponInfo) SetStatus(val int64) {
	p.Status = val
}
func (p *CouponInfo) SetType(val int32) {
	p.Type = val
}
func (p *CouponInfo) SetThreshold(val int64) {
	p.Threshold = val
}
func (p *CouponInfo) SetAmount(val int64) {
	p.Amount = val
}
func (p *CouponInfo) SetRate(val int64) {
	p.Rate = val
}
func (p *CouponInfo) SetCreateTime(val int64) {
	p.CreateTime = val
}
func (p *CouponInfo) SetExpiredAt(val int64) {
	p.ExpiredAt = val
}
func (p *CouponInfo) SetUsedAt(val int64) {
	p.UsedAt = val
}

func (p *CouponInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CouponInfo(%+v)", *p)
}

var fieldIDToName_CouponInfo = map[int16]string{
	1:  "id",
	2:  "batchId",
	3:  "userId",
	4:  "orderId",
	5:  "status",
	6:  "type",
	7:  "threshold",
	8:  "amount",
	9:  "rate",
	10: "createTime",
	11: "expiredAt",
	12: "usedAt",
}

type OrderInfo struct {
	Id               int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	UserId           int64  `thrift:"userId,2" frugal:"2,default,i64" json:"userId"`
	Status           int32  `thrift:"status,3" frugal:"3,default,i32" json:"status"`
	TotalPrice       int64  `thrift:"totalPrice,4" frugal:"4,default,i64" json:"totalPrice"`
	PaymentPrice     int64  `thrift:"paymentPrice,5" frugal:"5,default,i64" json:"paymentPrice"`
	ReceiverName     string `thrift:"receiverName,6" frugal:"6,default,string" json:"receiverName"`
	ReceiverEmail    string `thrift:"receiverEmail,7" frugal:"7,default,string" json:"receiverEmail"`
	ReceiverProvince string `thrift:"receiverProvince,8" frugal:"8,default,string" json:"receiverProvince"`
	ReceiverCity     string `thrift:"receiverCity,9" frugal:"9,default,string" json:"receiverCity"`
	ReceiverDetail   string `thrift:"receiverDetail,10" frugal:"10,default,string" json:"receiverDetail"`
	CreateTime       int64  `thrift:"createTime,11" frugal:"11,default,i64" json:"createTime"`
	UpdateTime       int64  `thrift:"updateTime,12" frugal:"12,default,i64" json:"updateTime"`
	ExpireTime       int64  `thrift:"expireTime,13" frugal:"13,default,i64" json:"expireTime"`
	PayTime          int64  `thrift:"payTime,14" frugal:"14,default,i64" json:"payTime"`
	CancelTime       int64  `thrift:"cancelTime,15" frugal:"15,default,i64" json:"cancelTime"`
	CancelReason     string `thrift:"cancelReason,16" frugal:"16,default,string" json:"cancelReason"`
}

func NewOrderInfo() *OrderInfo {
	return &OrderInfo{}
}

func (p *OrderInfo) InitDefault() {
}

func (p *OrderInfo) GetId() (v int64) {
	return p.Id
}

func (p *OrderInfo) GetUserId() (v int64) {
	return p.UserId
}

func (p *OrderInfo) GetStatus() (v int32) {
	return p.Status
}

func (p *OrderInfo) GetTotalPrice() (v int64) {
	return p.TotalPrice
}

func (p *OrderInfo) GetPaymentPrice() (v int64) {
	return p.PaymentPrice
}

func (p *OrderInfo) GetReceiverName() (v string) {
	return p.ReceiverName
}

func (p *OrderInfo) GetReceiverEmail() (v string) {
	return p.ReceiverEmail
}

func (p *OrderInfo) GetReceiverProvince() (v string) {
	return p.ReceiverProvince
}

func (p *OrderInfo) GetReceiverCity() (v string) {
	return p.ReceiverCity
}

func (p *OrderInfo) GetReceiverDetail() (v string) {
	return p.ReceiverDetail
}

func (p *OrderInfo) GetCreateTime() (v int64) {
	return p.CreateTime
}

func (p *OrderInfo) GetUpdateTime() (v int64) {
	return p.UpdateTime
}

func (p *OrderInfo) GetExpireTime() (v int64) {
	return p.ExpireTime
}

func (p *OrderInfo) GetPayTime() (v int64) {
	return p.PayTime
}

func (p *OrderInfo) GetCancelTime() (v int64) {
	return p.CancelTime
}

func (p *OrderInfo) GetCancelReason() (v string) {
	return p.CancelReason
}
func (p *OrderInfo) SetId(val int64) {
	p.Id = val
}
func (p *OrderInfo) SetUserId(val int64) {
	p.UserId = val
}
func (p *OrderInfo) SetStatus(val int32) {
	p.Status = val
}
func (p *OrderInfo) SetTotalPrice(val int64) {
	p.TotalPrice = val
}
func (p *OrderInfo) SetPaymentPrice(val int64) {
	p.PaymentPrice = val
}
func (p *OrderInfo) SetReceiverName(val string) {
	p.ReceiverName = val
}
func (p *OrderInfo) SetReceiverEmail(val string) {
	p.ReceiverEmail = val
}
func (p *OrderInfo) SetReceiverProvince(val string) {
	p.ReceiverProvince = val
}
func (p *OrderInfo) SetReceiverCity(val string) {
	p.ReceiverCity = val
}
func (p *OrderInfo) SetReceiverDetail(val string) {
	p.ReceiverDetail = val
}
func (p *OrderInfo) SetCreateTime(val int64) {
	p.CreateTime = val
}
func (p *OrderInfo) SetUpdateTime(val int64) {
	p.UpdateTime = val
}
func (p *OrderInfo) SetExpireTime(val int64) {
	p.ExpireTime = val
}
func (p *OrderInfo) SetPayTime(val int64) {
	p.PayTime = val
}
func (p *OrderInfo) SetCancelTime(val int64) {
	p.CancelTime = val
}
func (p *OrderInfo) SetCancelReason(val string) {
	p.CancelReason = val
}

func (p *OrderInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderInfo(%+v)", *p)
}

var fieldIDToName_OrderInfo = map[int16]string{
	1:  "id",
	2:  "userId",
	3:  "status",
	4:  "totalPrice",
	5:  "paymentPrice",
	6:  "receiverName",
	7:  "receiverEmail",
	8:  "receiverProvince",
	9:  "receiverCity",
	10: "receiverDetail",
	11: "createTime",
	12: "updateTime",
	13: "expireTime",
	14: "payTime",
	15: "cancelTime",
	16: "cancelReason",
}

type OrderItem struct {
	Id                int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	SellerId          int64  `thrift:"sellerId,2" frugal:"2,default,i64" json:"sellerId"`
	UserId            int64  `thrift:"userId,3" frugal:"3,default,i64" json:"userId"`
	OrderId           int64  `thrift:"orderId,4" frugal:"4,default,i64" json:"orderId"`
	ProductId         int64  `thrift:"productId,5" frugal:"5,default,i64" json:"productId"`
	ProductName       string `thrift:"productName,6" frugal:"6,default,string" json:"productName"`
	ProductPrice      int64  `thrift:"productPrice,7" frugal:"7,default,i64" json:"productPrice"`
	ProductImage      string `thrift:"productImage,8" frugal:"8,default,string" json:"productImage"`
	ProductNum        int64  `thrift:"productNum,9" frugal:"9,default,i64" json:"productNum"`
	ProductTotalPrice int64  `thrift:"productTotalPrice,10" frugal:"10,default,i64" json:"productTotalPrice"`
	ProductProperties string `thrift:"productProperties,11" frugal:"11,default,string" json:"productProperties"`
}

func NewOrderItem() *OrderItem {
	return &OrderItem{}
}

func (p *OrderItem) InitDefault() {
}

func (p *OrderItem) GetId() (v int64) {
	return p.Id
}

func (p *OrderItem) GetSellerId() (v int64) {
	return p.SellerId
}

func (p *OrderItem) GetUserId() (v int64) {
	return p.UserId
}

func (p *OrderItem) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *OrderItem) GetProductId() (v int64) {
	return p.ProductId
}

func (p *OrderItem) GetProductName() (v string) {
	return p.ProductName
}

func (p *OrderItem) GetProductPrice() (v int64) {
	return p.ProductPrice
}

func (p *OrderItem) GetProductImage() (v string) {
	return p.ProductImage
}

func (p *OrderItem) GetProductNum() (v int64) {
	return p.ProductNum
}

func (p *OrderItem) GetProductTotalPrice() (v int64) {
	return p.ProductTotalPrice
}

func (p *OrderItem) GetProductProperties() (v string) {
	return p.ProductProperties
}
func (p *OrderItem) SetId(val int64) {
	p.Id = val
}
func (p *OrderItem) SetSellerId(val int64) {
	p.SellerId = val
}
func (p *OrderItem) SetUserId(val int64) {
	p.UserId = val
}
func (p *OrderItem) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *OrderItem) SetProductId(val int64) {
	p.ProductId = val
}
func (p *OrderItem) SetProductName(val string) {
	p.ProductName = val
}
func (p *OrderItem) SetProductPrice(val int64) {
	p.ProductPrice = val
}
func (p *OrderItem) SetProductImage(val string) {
	p.ProductImage = val
}
func (p *OrderItem) SetProductNum(val int64) {
	p.ProductNum = val
}
func (p *OrderItem) SetProductTotalPrice(val int64) {
	p.ProductTotalPrice = val
}
func (p *OrderItem) SetProductProperties(val string) {
	p.ProductProperties = val
}

func (p *OrderItem) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderItem(%+v)", *p)
}

var fieldIDToName_OrderItem = map[int16]string{
	1:  "id",
	2:  "sellerId",
	3:  "userId",
	4:  "orderId",
	5:  "productId",
	6:  "productName",
	7:  "productPrice",
	8:  "productImage",
	9:  "productNum",
	10: "productTotalPrice",
	11: "productProperties",
}

type OrderWithItems struct {
	OrderInfo  *OrderInfo   `thrift:"orderInfo,1" frugal:"1,default,OrderInfo" json:"orderInfo"`
	OrderItems []*OrderItem `thrift:"orderItems,2" frugal:"2,default,list<OrderItem>" json:"orderItems"`
}

func NewOrderWithItems() *OrderWithItems {
	return &OrderWithItems{}
}

func (p *OrderWithItems) InitDefault() {
}

var OrderWithItems_OrderInfo_DEFAULT *OrderInfo

func (p *OrderWithItems) GetOrderInfo() (v *OrderInfo) {
	if !p.IsSetOrderInfo() {
		return OrderWithItems_OrderInfo_DEFAULT
	}
	return p.OrderInfo
}

func (p *OrderWithItems) GetOrderItems() (v []*OrderItem) {
	return p.OrderItems
}
func (p *OrderWithItems) SetOrderInfo(val *OrderInfo) {
	p.OrderInfo = val
}
func (p *OrderWithItems) SetOrderItems(val []*OrderItem) {
	p.OrderItems = val
}

func (p *OrderWithItems) IsSetOrderInfo() bool {
	return p.OrderInfo != nil
}

func (p *OrderWithItems) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderWithItems(%+v)", *p)
}

var fieldIDToName_OrderWithItems = map[int16]string{
	1: "orderInfo",
	2: "orderItems",
}

type PaymentOrderInfo struct {
	Id            int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	OrderId       int64  `thrift:"orderId,2" frugal:"2,default,i64" json:"orderId"`
	UserId        int64  `thrift:"userId,3" frugal:"3,default,i64" json:"userId"`
	PaymentNo     string `thrift:"paymentNo,4" frugal:"4,default,string" json:"paymentNo"`
	Amount        int64  `thrift:"amount,5" frugal:"5,default,i64" json:"amount"`
	PaymentMethod int32  `thrift:"paymentMethod,6" frugal:"6,default,i32" json:"paymentMethod"`
	Status        int32  `thrift:"status,7" frugal:"7,default,i32" json:"status"`
	CreateTime    int64  `thrift:"createTime,8" frugal:"8,default,i64" json:"createTime"`
	UpdateTime    int64  `thrift:"updateTime,9" frugal:"9,default,i64" json:"updateTime"`
}

func NewPaymentOrderInfo() *PaymentOrderInfo {
	return &PaymentOrderInfo{}
}

func (p *PaymentOrderInfo) InitDefault() {
}

func (p *PaymentOrderInfo) GetId() (v int64) {
	return p.Id
}

func (p *PaymentOrderInfo) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *PaymentOrderInfo) GetUserId() (v int64) {
	return p.UserId
}

func (p *PaymentOrderInfo) GetPaymentNo() (v string) {
	return p.PaymentNo
}

func (p *PaymentOrderInfo) GetAmount() (v int64) {
	return p.Amount
}

func (p *PaymentOrderInfo) GetPaymentMethod() (v int32) {
	return p.PaymentMethod
}

func (p *PaymentOrderInfo) GetStatus() (v int32) {
	return p.Status
}

func (p *PaymentOrderInfo) GetCreateTime() (v int64) {
	return p.CreateTime
}

func (p *PaymentOrderInfo) GetUpdateTime() (v int64) {
	return p.UpdateTime
}
func (p *PaymentOrderInfo) SetId(val int64) {
	p.Id = val
}
func (p *PaymentOrderInfo) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *PaymentOrderInfo) SetUserId(val int64) {
	p.UserId = val
}
func (p *PaymentOrderInfo) SetPaymentNo(val string) {
	p.PaymentNo = val
}
func (p *PaymentOrderInfo) SetAmount(val int64) {
	p.Amount = val
}
func (p *PaymentOrderInfo) SetPaymentMethod(val int32) {
	p.PaymentMethod = val
}
func (p *PaymentOrderInfo) SetStatus(val int32) {
	p.Status = val
}
func (p *PaymentOrderInfo) SetCreateTime(val int64) {
	p.CreateTime = val
}
func (p *PaymentOrderInfo) SetUpdateTime(val int64) {
	p.UpdateTime = val
}

func (p *PaymentOrderInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PaymentOrderInfo(%+v)", *p)
}

var fieldIDToName_PaymentOrderInfo = map[int16]string{
	1: "id",
	2: "orderId",
	3: "userId",
	4: "paymentNo",
	5: "amount",
	6: "paymentMethod",
	7: "status",
	8: "createTime",
	9: "updateTime",
}

type PaymentRefundItem struct {
	Id           int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	OrderItemId  int64  `thrift:"orderItemId,2" frugal:"2,default,i64" json:"orderItemId"`
	SellerId     int64  `thrift:"sellerId,3" frugal:"3,default,i64" json:"sellerId"`
	UserId       int64  `thrift:"userId,4" frugal:"4,default,i64" json:"userId"`
	PaymentNo    string `thrift:"paymentNo,5" frugal:"5,default,string" json:"paymentNo"`
	RefundNo     string `thrift:"RefundNo,6" frugal:"6,default,string" json:"RefundNo"`
	RefundAmount int64  `thrift:"refundAmount,7" frugal:"7,default,i64" json:"refundAmount"`
	RefundReason string `thrift:"refundReason,8" frugal:"8,default,string" json:"refundReason"`
	Status       int32  `thrift:"status,9" frugal:"9,default,i32" json:"status"`
	CreateTime   int64  `thrift:"createTime,10" frugal:"10,default,i64" json:"createTime"`
	UpdateTime   int64  `thrift:"updateTime,11" frugal:"11,default,i64" json:"updateTime"`
}

func NewPaymentRefundItem() *PaymentRefundItem {
	return &PaymentRefundItem{}
}

func (p *PaymentRefundItem) InitDefault() {
}

func (p *PaymentRefundItem) GetId() (v int64) {
	return p.Id
}

func (p *PaymentRefundItem) GetOrderItemId() (v int64) {
	return p.OrderItemId
}

func (p *PaymentRefundItem) GetSellerId() (v int64) {
	return p.SellerId
}

func (p *PaymentRefundItem) GetUserId() (v int64) {
	return p.UserId
}

func (p *PaymentRefundItem) GetPaymentNo() (v string) {
	return p.PaymentNo
}

func (p *PaymentRefundItem) GetRefundNo() (v string) {
	return p.RefundNo
}

func (p *PaymentRefundItem) GetRefundAmount() (v int64) {
	return p.RefundAmount
}

func (p *PaymentRefundItem) GetRefundReason() (v string) {
	return p.RefundReason
}

func (p *PaymentRefundItem) GetStatus() (v int32) {
	return p.Status
}

func (p *PaymentRefundItem) GetCreateTime() (v int64) {
	return p.CreateTime
}

func (p *PaymentRefundItem) GetUpdateTime() (v int64) {
	return p.UpdateTime
}
func (p *PaymentRefundItem) SetId(val int64) {
	p.Id = val
}
func (p *PaymentRefundItem) SetOrderItemId(val int64) {
	p.OrderItemId = val
}
func (p *PaymentRefundItem) SetSellerId(val int64) {
	p.SellerId = val
}
func (p *PaymentRefundItem) SetUserId(val int64) {
	p.UserId = val
}
func (p *PaymentRefundItem) SetPaymentNo(val string) {
	p.PaymentNo = val
}
func (p *PaymentRefundItem) SetRefundNo(val string) {
	p.RefundNo = val
}
func (p *PaymentRefundItem) SetRefundAmount(val int64) {
	p.RefundAmount = val
}
func (p *PaymentRefundItem) SetRefundReason(val string) {
	p.RefundReason = val
}
func (p *PaymentRefundItem) SetStatus(val int32) {
	p.Status = val
}
func (p *PaymentRefundItem) SetCreateTime(val int64) {
	p.CreateTime = val
}
func (p *PaymentRefundItem) SetUpdateTime(val int64) {
	p.UpdateTime = val
}

func (p *PaymentRefundItem) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PaymentRefundItem(%+v)", *p)
}

var fieldIDToName_PaymentRefundItem = map[int16]string{
	1:  "id",
	2:  "orderItemId",
	3:  "sellerId",
	4:  "userId",
	5:  "paymentNo",
	6:  "RefundNo",
	7:  "refundAmount",
	8:  "refundReason",
	9:  "status",
	10: "createTime",
	11: "updateTime",
}
