// Code generated by Kitex v0.15.2. DO NOT EDIT.

package paymentservice

import (
	payment "MengGoods/kitex_gen/payment"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetPaymentToken(ctx context.Context, req *payment.GetPaymentTokenReq, callOptions ...callopt.Option) (r *payment.GetPaymentTokenResp, err error)
	Payment(ctx context.Context, req *payment.PaymentReq, callOptions ...callopt.Option) (r *payment.PaymentResp, err error)
	PaymentRefund(ctx context.Context, req *payment.PaymentRefundReq, callOptions ...callopt.Option) (r *payment.PaymentRefundResp, err error)
	Refund(ctx context.Context, req *payment.ReviewRefundReq, callOptions ...callopt.Option) (r *payment.RefundResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kPaymentServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPaymentServiceClient struct {
	*kClient
}

func (p *kPaymentServiceClient) GetPaymentToken(ctx context.Context, req *payment.GetPaymentTokenReq, callOptions ...callopt.Option) (r *payment.GetPaymentTokenResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPaymentToken(ctx, req)
}

func (p *kPaymentServiceClient) Payment(ctx context.Context, req *payment.PaymentReq, callOptions ...callopt.Option) (r *payment.PaymentResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Payment(ctx, req)
}

func (p *kPaymentServiceClient) PaymentRefund(ctx context.Context, req *payment.PaymentRefundReq, callOptions ...callopt.Option) (r *payment.PaymentRefundResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PaymentRefund(ctx, req)
}

func (p *kPaymentServiceClient) Refund(ctx context.Context, req *payment.ReviewRefundReq, callOptions ...callopt.Option) (r *payment.RefundResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Refund(ctx, req)
}
