// Code generated by Kitex v0.15.2. DO NOT EDIT.

package paymentservice

import (
	payment "MengGoods/kitex_gen/payment"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetPaymentToken": kitex.NewMethodInfo(
		getPaymentTokenHandler,
		newPaymentServiceGetPaymentTokenArgs,
		newPaymentServiceGetPaymentTokenResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Payment": kitex.NewMethodInfo(
		paymentHandler,
		newPaymentServicePaymentArgs,
		newPaymentServicePaymentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"PaymentRefund": kitex.NewMethodInfo(
		paymentRefundHandler,
		newPaymentServicePaymentRefundArgs,
		newPaymentServicePaymentRefundResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Refund": kitex.NewMethodInfo(
		refundHandler,
		newPaymentServiceRefundArgs,
		newPaymentServiceRefundResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	paymentServiceServiceInfo                = NewServiceInfo()
	paymentServiceServiceInfoForClient       = NewServiceInfoForClient()
	paymentServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return paymentServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return paymentServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return paymentServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "PaymentService"
	handlerType := (*payment.PaymentService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "payment",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func getPaymentTokenHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*payment.PaymentServiceGetPaymentTokenArgs)
	realResult := result.(*payment.PaymentServiceGetPaymentTokenResult)
	success, err := handler.(payment.PaymentService).GetPaymentToken(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPaymentServiceGetPaymentTokenArgs() interface{} {
	return payment.NewPaymentServiceGetPaymentTokenArgs()
}

func newPaymentServiceGetPaymentTokenResult() interface{} {
	return payment.NewPaymentServiceGetPaymentTokenResult()
}

func paymentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*payment.PaymentServicePaymentArgs)
	realResult := result.(*payment.PaymentServicePaymentResult)
	success, err := handler.(payment.PaymentService).Payment(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPaymentServicePaymentArgs() interface{} {
	return payment.NewPaymentServicePaymentArgs()
}

func newPaymentServicePaymentResult() interface{} {
	return payment.NewPaymentServicePaymentResult()
}

func paymentRefundHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*payment.PaymentServicePaymentRefundArgs)
	realResult := result.(*payment.PaymentServicePaymentRefundResult)
	success, err := handler.(payment.PaymentService).PaymentRefund(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPaymentServicePaymentRefundArgs() interface{} {
	return payment.NewPaymentServicePaymentRefundArgs()
}

func newPaymentServicePaymentRefundResult() interface{} {
	return payment.NewPaymentServicePaymentRefundResult()
}

func refundHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*payment.PaymentServiceRefundArgs)
	realResult := result.(*payment.PaymentServiceRefundResult)
	success, err := handler.(payment.PaymentService).Refund(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPaymentServiceRefundArgs() interface{} {
	return payment.NewPaymentServiceRefundArgs()
}

func newPaymentServiceRefundResult() interface{} {
	return payment.NewPaymentServiceRefundResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetPaymentToken(ctx context.Context, req *payment.GetPaymentTokenReq) (r *payment.GetPaymentTokenResp, err error) {
	var _args payment.PaymentServiceGetPaymentTokenArgs
	_args.Req = req
	var _result payment.PaymentServiceGetPaymentTokenResult
	if err = p.c.Call(ctx, "GetPaymentToken", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Payment(ctx context.Context, req *payment.PaymentReq) (r *payment.PaymentResp, err error) {
	var _args payment.PaymentServicePaymentArgs
	_args.Req = req
	var _result payment.PaymentServicePaymentResult
	if err = p.c.Call(ctx, "Payment", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) PaymentRefund(ctx context.Context, req *payment.PaymentRefundReq) (r *payment.PaymentRefundResp, err error) {
	var _args payment.PaymentServicePaymentRefundArgs
	_args.Req = req
	var _result payment.PaymentServicePaymentRefundResult
	if err = p.c.Call(ctx, "PaymentRefund", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Refund(ctx context.Context, req *payment.ReviewRefundReq) (r *payment.RefundResp, err error) {
	var _args payment.PaymentServiceRefundArgs
	_args.Req = req
	var _result payment.PaymentServiceRefundResult
	if err = p.c.Call(ctx, "Refund", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
