CREATE TABLE `order` (
    `order_id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '使用自增主键',
    `user_id` BIGINT NOT NULL COMMENT '用户 id',
    `total_price` DECIMAL(10,2) NOT NULL COMMENT '订单总金额',
    `status` TINYINT NOT NULL DEFAULT 0 COMMENT '订单状态, 0: 待支付, 1: 已支付, 2: 已发货, 3: 已确认, 4: 已取消',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '删除时间',
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单表';