// Code generated by Kitex v0.15.2. DO NOT EDIT.

package couponservice

import (
	coupon "MengGoods/kitex_gen/coupon"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateCouponBatch(ctx context.Context, req *coupon.CreateCouponBatchReq, callOptions ...callopt.Option) (r *coupon.CreateCouponBatchResp, err error)
	GetCoupon(ctx context.Context, req *coupon.GetCouponReq, callOptions ...callopt.Option) (r *coupon.GetCouponResp, err error)
	GetCouponList(ctx context.Context, req *coupon.GetCouponListReq, callOptions ...callopt.Option) (r *coupon.GetCouponListResp, err error)
	LockCoupon(ctx context.Context, req *coupon.LockCouponReq, callOptions ...callopt.Option) (r *coupon.LockCouponResp, err error)
	ReleaseCoupon(ctx context.Context, req *coupon.ReleaseCouponReq, callOptions ...callopt.Option) (r *coupon.ReleaseCouponResp, err error)
	RedeemCoupon(ctx context.Context, req *coupon.RedeemCouponReq, callOptions ...callopt.Option) (r *coupon.RedeemCouponResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kCouponServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCouponServiceClient struct {
	*kClient
}

func (p *kCouponServiceClient) CreateCouponBatch(ctx context.Context, req *coupon.CreateCouponBatchReq, callOptions ...callopt.Option) (r *coupon.CreateCouponBatchResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateCouponBatch(ctx, req)
}

func (p *kCouponServiceClient) GetCoupon(ctx context.Context, req *coupon.GetCouponReq, callOptions ...callopt.Option) (r *coupon.GetCouponResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCoupon(ctx, req)
}

func (p *kCouponServiceClient) GetCouponList(ctx context.Context, req *coupon.GetCouponListReq, callOptions ...callopt.Option) (r *coupon.GetCouponListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCouponList(ctx, req)
}

func (p *kCouponServiceClient) LockCoupon(ctx context.Context, req *coupon.LockCouponReq, callOptions ...callopt.Option) (r *coupon.LockCouponResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.LockCoupon(ctx, req)
}

func (p *kCouponServiceClient) ReleaseCoupon(ctx context.Context, req *coupon.ReleaseCouponReq, callOptions ...callopt.Option) (r *coupon.ReleaseCouponResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReleaseCoupon(ctx, req)
}

func (p *kCouponServiceClient) RedeemCoupon(ctx context.Context, req *coupon.RedeemCouponReq, callOptions ...callopt.Option) (r *coupon.RedeemCouponResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RedeemCoupon(ctx, req)
}
