// Code generated by Kitex v0.15.2. DO NOT EDIT.

package couponservice

import (
	coupon "MengGoods/kitex_gen/coupon"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateCouponBatch": kitex.NewMethodInfo(
		createCouponBatchHandler,
		newCouponServiceCreateCouponBatchArgs,
		newCouponServiceCreateCouponBatchResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetCoupon": kitex.NewMethodInfo(
		getCouponHandler,
		newCouponServiceGetCouponArgs,
		newCouponServiceGetCouponResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetCouponList": kitex.NewMethodInfo(
		getCouponListHandler,
		newCouponServiceGetCouponListArgs,
		newCouponServiceGetCouponListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"LockCoupon": kitex.NewMethodInfo(
		lockCouponHandler,
		newCouponServiceLockCouponArgs,
		newCouponServiceLockCouponResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ReleaseCoupon": kitex.NewMethodInfo(
		releaseCouponHandler,
		newCouponServiceReleaseCouponArgs,
		newCouponServiceReleaseCouponResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RedeemCoupon": kitex.NewMethodInfo(
		redeemCouponHandler,
		newCouponServiceRedeemCouponArgs,
		newCouponServiceRedeemCouponResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	couponServiceServiceInfo                = NewServiceInfo()
	couponServiceServiceInfoForClient       = NewServiceInfoForClient()
	couponServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return couponServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return couponServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return couponServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "CouponService"
	handlerType := (*coupon.CouponService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "coupon",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func createCouponBatchHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*coupon.CouponServiceCreateCouponBatchArgs)
	realResult := result.(*coupon.CouponServiceCreateCouponBatchResult)
	success, err := handler.(coupon.CouponService).CreateCouponBatch(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCouponServiceCreateCouponBatchArgs() interface{} {
	return coupon.NewCouponServiceCreateCouponBatchArgs()
}

func newCouponServiceCreateCouponBatchResult() interface{} {
	return coupon.NewCouponServiceCreateCouponBatchResult()
}

func getCouponHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*coupon.CouponServiceGetCouponArgs)
	realResult := result.(*coupon.CouponServiceGetCouponResult)
	success, err := handler.(coupon.CouponService).GetCoupon(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCouponServiceGetCouponArgs() interface{} {
	return coupon.NewCouponServiceGetCouponArgs()
}

func newCouponServiceGetCouponResult() interface{} {
	return coupon.NewCouponServiceGetCouponResult()
}

func getCouponListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*coupon.CouponServiceGetCouponListArgs)
	realResult := result.(*coupon.CouponServiceGetCouponListResult)
	success, err := handler.(coupon.CouponService).GetCouponList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCouponServiceGetCouponListArgs() interface{} {
	return coupon.NewCouponServiceGetCouponListArgs()
}

func newCouponServiceGetCouponListResult() interface{} {
	return coupon.NewCouponServiceGetCouponListResult()
}

func lockCouponHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*coupon.CouponServiceLockCouponArgs)
	realResult := result.(*coupon.CouponServiceLockCouponResult)
	success, err := handler.(coupon.CouponService).LockCoupon(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCouponServiceLockCouponArgs() interface{} {
	return coupon.NewCouponServiceLockCouponArgs()
}

func newCouponServiceLockCouponResult() interface{} {
	return coupon.NewCouponServiceLockCouponResult()
}

func releaseCouponHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*coupon.CouponServiceReleaseCouponArgs)
	realResult := result.(*coupon.CouponServiceReleaseCouponResult)
	success, err := handler.(coupon.CouponService).ReleaseCoupon(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCouponServiceReleaseCouponArgs() interface{} {
	return coupon.NewCouponServiceReleaseCouponArgs()
}

func newCouponServiceReleaseCouponResult() interface{} {
	return coupon.NewCouponServiceReleaseCouponResult()
}

func redeemCouponHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*coupon.CouponServiceRedeemCouponArgs)
	realResult := result.(*coupon.CouponServiceRedeemCouponResult)
	success, err := handler.(coupon.CouponService).RedeemCoupon(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCouponServiceRedeemCouponArgs() interface{} {
	return coupon.NewCouponServiceRedeemCouponArgs()
}

func newCouponServiceRedeemCouponResult() interface{} {
	return coupon.NewCouponServiceRedeemCouponResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateCouponBatch(ctx context.Context, req *coupon.CreateCouponBatchReq) (r *coupon.CreateCouponBatchResp, err error) {
	var _args coupon.CouponServiceCreateCouponBatchArgs
	_args.Req = req
	var _result coupon.CouponServiceCreateCouponBatchResult
	if err = p.c.Call(ctx, "CreateCouponBatch", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetCoupon(ctx context.Context, req *coupon.GetCouponReq) (r *coupon.GetCouponResp, err error) {
	var _args coupon.CouponServiceGetCouponArgs
	_args.Req = req
	var _result coupon.CouponServiceGetCouponResult
	if err = p.c.Call(ctx, "GetCoupon", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetCouponList(ctx context.Context, req *coupon.GetCouponListReq) (r *coupon.GetCouponListResp, err error) {
	var _args coupon.CouponServiceGetCouponListArgs
	_args.Req = req
	var _result coupon.CouponServiceGetCouponListResult
	if err = p.c.Call(ctx, "GetCouponList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) LockCoupon(ctx context.Context, req *coupon.LockCouponReq) (r *coupon.LockCouponResp, err error) {
	var _args coupon.CouponServiceLockCouponArgs
	_args.Req = req
	var _result coupon.CouponServiceLockCouponResult
	if err = p.c.Call(ctx, "LockCoupon", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ReleaseCoupon(ctx context.Context, req *coupon.ReleaseCouponReq) (r *coupon.ReleaseCouponResp, err error) {
	var _args coupon.CouponServiceReleaseCouponArgs
	_args.Req = req
	var _result coupon.CouponServiceReleaseCouponResult
	if err = p.c.Call(ctx, "ReleaseCoupon", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RedeemCoupon(ctx context.Context, req *coupon.RedeemCouponReq) (r *coupon.RedeemCouponResp, err error) {
	var _args coupon.CouponServiceRedeemCouponArgs
	_args.Req = req
	var _result coupon.CouponServiceRedeemCouponResult
	if err = p.c.Call(ctx, "RedeemCoupon", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
