// Code generated by Kitex v0.15.2. DO NOT EDIT.

package orderservice

import (
	order "MengGoods/kitex_gen/order"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateOrder(ctx context.Context, req *order.CreateOrderReq, callOptions ...callopt.Option) (r *order.CreateOrderResp, err error)
	ViewOrderById(ctx context.Context, req *order.ViewOrderByIdReq, callOptions ...callopt.Option) (r *order.ViewOrderByIdResp, err error)
	ViewOrderList(ctx context.Context, req *order.ViewOrderListReq, callOptions ...callopt.Option) (r *order.ViewOrderListResp, err error)
	CancelOrder(ctx context.Context, req *order.CancelOrderReq, callOptions ...callopt.Option) (r *order.CancelOrderResp, err error)
	ConfirmReceiptOrder(ctx context.Context, req *order.ConfirmReceiptOrderReq, callOptions ...callopt.Option) (r *order.ConfirmReceiptOrderResp, err error)
	MarkOrderPaid(ctx context.Context, req *order.MarkOrderPaidReq, callOptions ...callopt.Option) (r *order.MarkOrderPaidResp, err error)
	GetPayAmount(ctx context.Context, req *order.GetPayAmountReq, callOptions ...callopt.Option) (r *order.GetPayAmountResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kOrderServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kOrderServiceClient struct {
	*kClient
}

func (p *kOrderServiceClient) CreateOrder(ctx context.Context, req *order.CreateOrderReq, callOptions ...callopt.Option) (r *order.CreateOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateOrder(ctx, req)
}

func (p *kOrderServiceClient) ViewOrderById(ctx context.Context, req *order.ViewOrderByIdReq, callOptions ...callopt.Option) (r *order.ViewOrderByIdResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ViewOrderById(ctx, req)
}

func (p *kOrderServiceClient) ViewOrderList(ctx context.Context, req *order.ViewOrderListReq, callOptions ...callopt.Option) (r *order.ViewOrderListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ViewOrderList(ctx, req)
}

func (p *kOrderServiceClient) CancelOrder(ctx context.Context, req *order.CancelOrderReq, callOptions ...callopt.Option) (r *order.CancelOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CancelOrder(ctx, req)
}

func (p *kOrderServiceClient) ConfirmReceiptOrder(ctx context.Context, req *order.ConfirmReceiptOrderReq, callOptions ...callopt.Option) (r *order.ConfirmReceiptOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ConfirmReceiptOrder(ctx, req)
}

func (p *kOrderServiceClient) MarkOrderPaid(ctx context.Context, req *order.MarkOrderPaidReq, callOptions ...callopt.Option) (r *order.MarkOrderPaidResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MarkOrderPaid(ctx, req)
}

func (p *kOrderServiceClient) GetPayAmount(ctx context.Context, req *order.GetPayAmountReq, callOptions ...callopt.Option) (r *order.GetPayAmountResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPayAmount(ctx, req)
}
