// Code generated by Kitex v0.15.2. DO NOT EDIT.

package orderservice

import (
	order "MengGoods/kitex_gen/order"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateOrder": kitex.NewMethodInfo(
		createOrderHandler,
		newOrderServiceCreateOrderArgs,
		newOrderServiceCreateOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ViewOrderById": kitex.NewMethodInfo(
		viewOrderByIdHandler,
		newOrderServiceViewOrderByIdArgs,
		newOrderServiceViewOrderByIdResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ViewOrderList": kitex.NewMethodInfo(
		viewOrderListHandler,
		newOrderServiceViewOrderListArgs,
		newOrderServiceViewOrderListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CancelOrder": kitex.NewMethodInfo(
		cancelOrderHandler,
		newOrderServiceCancelOrderArgs,
		newOrderServiceCancelOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ConfirmReceiptOrder": kitex.NewMethodInfo(
		confirmReceiptOrderHandler,
		newOrderServiceConfirmReceiptOrderArgs,
		newOrderServiceConfirmReceiptOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"MarkOrderPaid": kitex.NewMethodInfo(
		markOrderPaidHandler,
		newOrderServiceMarkOrderPaidArgs,
		newOrderServiceMarkOrderPaidResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetPayAmount": kitex.NewMethodInfo(
		getPayAmountHandler,
		newOrderServiceGetPayAmountArgs,
		newOrderServiceGetPayAmountResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	orderServiceServiceInfo                = NewServiceInfo()
	orderServiceServiceInfoForClient       = NewServiceInfoForClient()
	orderServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return orderServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return orderServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return orderServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "OrderService"
	handlerType := (*order.OrderService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "order",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func createOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*order.OrderServiceCreateOrderArgs)
	realResult := result.(*order.OrderServiceCreateOrderResult)
	success, err := handler.(order.OrderService).CreateOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServiceCreateOrderArgs() interface{} {
	return order.NewOrderServiceCreateOrderArgs()
}

func newOrderServiceCreateOrderResult() interface{} {
	return order.NewOrderServiceCreateOrderResult()
}

func viewOrderByIdHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*order.OrderServiceViewOrderByIdArgs)
	realResult := result.(*order.OrderServiceViewOrderByIdResult)
	success, err := handler.(order.OrderService).ViewOrderById(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServiceViewOrderByIdArgs() interface{} {
	return order.NewOrderServiceViewOrderByIdArgs()
}

func newOrderServiceViewOrderByIdResult() interface{} {
	return order.NewOrderServiceViewOrderByIdResult()
}

func viewOrderListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*order.OrderServiceViewOrderListArgs)
	realResult := result.(*order.OrderServiceViewOrderListResult)
	success, err := handler.(order.OrderService).ViewOrderList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServiceViewOrderListArgs() interface{} {
	return order.NewOrderServiceViewOrderListArgs()
}

func newOrderServiceViewOrderListResult() interface{} {
	return order.NewOrderServiceViewOrderListResult()
}

func cancelOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*order.OrderServiceCancelOrderArgs)
	realResult := result.(*order.OrderServiceCancelOrderResult)
	success, err := handler.(order.OrderService).CancelOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServiceCancelOrderArgs() interface{} {
	return order.NewOrderServiceCancelOrderArgs()
}

func newOrderServiceCancelOrderResult() interface{} {
	return order.NewOrderServiceCancelOrderResult()
}

func confirmReceiptOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*order.OrderServiceConfirmReceiptOrderArgs)
	realResult := result.(*order.OrderServiceConfirmReceiptOrderResult)
	success, err := handler.(order.OrderService).ConfirmReceiptOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServiceConfirmReceiptOrderArgs() interface{} {
	return order.NewOrderServiceConfirmReceiptOrderArgs()
}

func newOrderServiceConfirmReceiptOrderResult() interface{} {
	return order.NewOrderServiceConfirmReceiptOrderResult()
}

func markOrderPaidHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*order.OrderServiceMarkOrderPaidArgs)
	realResult := result.(*order.OrderServiceMarkOrderPaidResult)
	success, err := handler.(order.OrderService).MarkOrderPaid(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServiceMarkOrderPaidArgs() interface{} {
	return order.NewOrderServiceMarkOrderPaidArgs()
}

func newOrderServiceMarkOrderPaidResult() interface{} {
	return order.NewOrderServiceMarkOrderPaidResult()
}

func getPayAmountHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*order.OrderServiceGetPayAmountArgs)
	realResult := result.(*order.OrderServiceGetPayAmountResult)
	success, err := handler.(order.OrderService).GetPayAmount(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServiceGetPayAmountArgs() interface{} {
	return order.NewOrderServiceGetPayAmountArgs()
}

func newOrderServiceGetPayAmountResult() interface{} {
	return order.NewOrderServiceGetPayAmountResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateOrder(ctx context.Context, req *order.CreateOrderReq) (r *order.CreateOrderResp, err error) {
	var _args order.OrderServiceCreateOrderArgs
	_args.Req = req
	var _result order.OrderServiceCreateOrderResult
	if err = p.c.Call(ctx, "CreateOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ViewOrderById(ctx context.Context, req *order.ViewOrderByIdReq) (r *order.ViewOrderByIdResp, err error) {
	var _args order.OrderServiceViewOrderByIdArgs
	_args.Req = req
	var _result order.OrderServiceViewOrderByIdResult
	if err = p.c.Call(ctx, "ViewOrderById", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ViewOrderList(ctx context.Context, req *order.ViewOrderListReq) (r *order.ViewOrderListResp, err error) {
	var _args order.OrderServiceViewOrderListArgs
	_args.Req = req
	var _result order.OrderServiceViewOrderListResult
	if err = p.c.Call(ctx, "ViewOrderList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CancelOrder(ctx context.Context, req *order.CancelOrderReq) (r *order.CancelOrderResp, err error) {
	var _args order.OrderServiceCancelOrderArgs
	_args.Req = req
	var _result order.OrderServiceCancelOrderResult
	if err = p.c.Call(ctx, "CancelOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ConfirmReceiptOrder(ctx context.Context, req *order.ConfirmReceiptOrderReq) (r *order.ConfirmReceiptOrderResp, err error) {
	var _args order.OrderServiceConfirmReceiptOrderArgs
	_args.Req = req
	var _result order.OrderServiceConfirmReceiptOrderResult
	if err = p.c.Call(ctx, "ConfirmReceiptOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MarkOrderPaid(ctx context.Context, req *order.MarkOrderPaidReq) (r *order.MarkOrderPaidResp, err error) {
	var _args order.OrderServiceMarkOrderPaidArgs
	_args.Req = req
	var _result order.OrderServiceMarkOrderPaidResult
	if err = p.c.Call(ctx, "MarkOrderPaid", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPayAmount(ctx context.Context, req *order.GetPayAmountReq) (r *order.GetPayAmountResp, err error) {
	var _args order.OrderServiceGetPayAmountArgs
	_args.Req = req
	var _result order.OrderServiceGetPayAmountResult
	if err = p.c.Call(ctx, "GetPayAmount", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
