// Code generated by Kitex v0.15.2. DO NOT EDIT.

package stockservice

import (
	stock "MengGoods/kitex_gen/stock"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateStock": kitex.NewMethodInfo(
		createStockHandler,
		newStockServiceCreateStockArgs,
		newStockServiceCreateStockResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AddStock": kitex.NewMethodInfo(
		addStockHandler,
		newStockServiceAddStockArgs,
		newStockServiceAddStockResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetStock": kitex.NewMethodInfo(
		getStockHandler,
		newStockServiceGetStockArgs,
		newStockServiceGetStockResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetStocks": kitex.NewMethodInfo(
		getStocksHandler,
		newStockServiceGetStocksArgs,
		newStockServiceGetStocksResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"LockStock": kitex.NewMethodInfo(
		lockStockHandler,
		newStockServiceLockStockArgs,
		newStockServiceLockStockResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UnlockStock": kitex.NewMethodInfo(
		unlockStockHandler,
		newStockServiceUnlockStockArgs,
		newStockServiceUnlockStockResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeductStock": kitex.NewMethodInfo(
		deductStockHandler,
		newStockServiceDeductStockArgs,
		newStockServiceDeductStockResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	stockServiceServiceInfo                = NewServiceInfo()
	stockServiceServiceInfoForClient       = NewServiceInfoForClient()
	stockServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return stockServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return stockServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return stockServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "StockService"
	handlerType := (*stock.StockService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "stock",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func createStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*stock.StockServiceCreateStockArgs)
	realResult := result.(*stock.StockServiceCreateStockResult)
	success, err := handler.(stock.StockService).CreateStock(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newStockServiceCreateStockArgs() interface{} {
	return stock.NewStockServiceCreateStockArgs()
}

func newStockServiceCreateStockResult() interface{} {
	return stock.NewStockServiceCreateStockResult()
}

func addStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*stock.StockServiceAddStockArgs)
	realResult := result.(*stock.StockServiceAddStockResult)
	success, err := handler.(stock.StockService).AddStock(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newStockServiceAddStockArgs() interface{} {
	return stock.NewStockServiceAddStockArgs()
}

func newStockServiceAddStockResult() interface{} {
	return stock.NewStockServiceAddStockResult()
}

func getStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*stock.StockServiceGetStockArgs)
	realResult := result.(*stock.StockServiceGetStockResult)
	success, err := handler.(stock.StockService).GetStock(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newStockServiceGetStockArgs() interface{} {
	return stock.NewStockServiceGetStockArgs()
}

func newStockServiceGetStockResult() interface{} {
	return stock.NewStockServiceGetStockResult()
}

func getStocksHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*stock.StockServiceGetStocksArgs)
	realResult := result.(*stock.StockServiceGetStocksResult)
	success, err := handler.(stock.StockService).GetStocks(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newStockServiceGetStocksArgs() interface{} {
	return stock.NewStockServiceGetStocksArgs()
}

func newStockServiceGetStocksResult() interface{} {
	return stock.NewStockServiceGetStocksResult()
}

func lockStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*stock.StockServiceLockStockArgs)
	realResult := result.(*stock.StockServiceLockStockResult)
	success, err := handler.(stock.StockService).LockStock(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newStockServiceLockStockArgs() interface{} {
	return stock.NewStockServiceLockStockArgs()
}

func newStockServiceLockStockResult() interface{} {
	return stock.NewStockServiceLockStockResult()
}

func unlockStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*stock.StockServiceUnlockStockArgs)
	realResult := result.(*stock.StockServiceUnlockStockResult)
	success, err := handler.(stock.StockService).UnlockStock(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newStockServiceUnlockStockArgs() interface{} {
	return stock.NewStockServiceUnlockStockArgs()
}

func newStockServiceUnlockStockResult() interface{} {
	return stock.NewStockServiceUnlockStockResult()
}

func deductStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*stock.StockServiceDeductStockArgs)
	realResult := result.(*stock.StockServiceDeductStockResult)
	success, err := handler.(stock.StockService).DeductStock(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newStockServiceDeductStockArgs() interface{} {
	return stock.NewStockServiceDeductStockArgs()
}

func newStockServiceDeductStockResult() interface{} {
	return stock.NewStockServiceDeductStockResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateStock(ctx context.Context, req *stock.CreateStockReq) (r *stock.CreateStockResp, err error) {
	var _args stock.StockServiceCreateStockArgs
	_args.Req = req
	var _result stock.StockServiceCreateStockResult
	if err = p.c.Call(ctx, "CreateStock", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddStock(ctx context.Context, req *stock.AddStockReq) (r *stock.AddStockResp, err error) {
	var _args stock.StockServiceAddStockArgs
	_args.Req = req
	var _result stock.StockServiceAddStockResult
	if err = p.c.Call(ctx, "AddStock", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetStock(ctx context.Context, req *stock.GetStockReq) (r *stock.GetStockResp, err error) {
	var _args stock.StockServiceGetStockArgs
	_args.Req = req
	var _result stock.StockServiceGetStockResult
	if err = p.c.Call(ctx, "GetStock", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetStocks(ctx context.Context, req *stock.GetStocksReq) (r *stock.GetStocksResp, err error) {
	var _args stock.StockServiceGetStocksArgs
	_args.Req = req
	var _result stock.StockServiceGetStocksResult
	if err = p.c.Call(ctx, "GetStocks", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) LockStock(ctx context.Context, req *stock.LockStockReq) (r *stock.LockStockResp, err error) {
	var _args stock.StockServiceLockStockArgs
	_args.Req = req
	var _result stock.StockServiceLockStockResult
	if err = p.c.Call(ctx, "LockStock", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UnlockStock(ctx context.Context, req *stock.UnlockStockReq) (r *stock.UnlockStockResp, err error) {
	var _args stock.StockServiceUnlockStockArgs
	_args.Req = req
	var _result stock.StockServiceUnlockStockResult
	if err = p.c.Call(ctx, "UnlockStock", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeductStock(ctx context.Context, req *stock.DeductStockReq) (r *stock.DeductStockResp, err error) {
	var _args stock.StockServiceDeductStockArgs
	_args.Req = req
	var _result stock.StockServiceDeductStockResult
	if err = p.c.Call(ctx, "DeductStock", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
