// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package user

import (
	"MengGoods/kitex_gen/model"
	"context"
	"fmt"
)

type RegisterReq struct {
	Username string `thrift:"username,1,required" frugal:"1,required,string" json:"username"`
	Password string `thrift:"password,2,required" frugal:"2,required,string" json:"password"`
	Email    string `thrift:"email,3,required" frugal:"3,required,string" json:"email"`
}

func NewRegisterReq() *RegisterReq {
	return &RegisterReq{}
}

func (p *RegisterReq) InitDefault() {
}

func (p *RegisterReq) GetUsername() (v string) {
	return p.Username
}

func (p *RegisterReq) GetPassword() (v string) {
	return p.Password
}

func (p *RegisterReq) GetEmail() (v string) {
	return p.Email
}
func (p *RegisterReq) SetUsername(val string) {
	p.Username = val
}
func (p *RegisterReq) SetPassword(val string) {
	p.Password = val
}
func (p *RegisterReq) SetEmail(val string) {
	p.Email = val
}

func (p *RegisterReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterReq(%+v)", *p)
}

var fieldIDToName_RegisterReq = map[int16]string{
	1: "username",
	2: "password",
	3: "email",
}

type RegisterResp struct {
	Base   *model.BaseResp `thrift:"base,1,required" frugal:"1,required,model.BaseResp" json:"base"`
	UserId int64           `thrift:"userId,2,required" frugal:"2,required,i64" json:"userId"`
}

func NewRegisterResp() *RegisterResp {
	return &RegisterResp{}
}

func (p *RegisterResp) InitDefault() {
}

var RegisterResp_Base_DEFAULT *model.BaseResp

func (p *RegisterResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return RegisterResp_Base_DEFAULT
	}
	return p.Base
}

func (p *RegisterResp) GetUserId() (v int64) {
	return p.UserId
}
func (p *RegisterResp) SetBase(val *model.BaseResp) {
	p.Base = val
}
func (p *RegisterResp) SetUserId(val int64) {
	p.UserId = val
}

func (p *RegisterResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *RegisterResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterResp(%+v)", *p)
}

var fieldIDToName_RegisterResp = map[int16]string{
	1: "base",
	2: "userId",
}

type LoginReq struct {
	Username string `thrift:"username,1,required" frugal:"1,required,string" json:"username"`
	Password string `thrift:"password,2,required" frugal:"2,required,string" json:"password"`
}

func NewLoginReq() *LoginReq {
	return &LoginReq{}
}

func (p *LoginReq) InitDefault() {
}

func (p *LoginReq) GetUsername() (v string) {
	return p.Username
}

func (p *LoginReq) GetPassword() (v string) {
	return p.Password
}
func (p *LoginReq) SetUsername(val string) {
	p.Username = val
}
func (p *LoginReq) SetPassword(val string) {
	p.Password = val
}

func (p *LoginReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginReq(%+v)", *p)
}

var fieldIDToName_LoginReq = map[int16]string{
	1: "username",
	2: "password",
}

type LoginResp struct {
	Base     *model.BaseResp `thrift:"base,1,required" frugal:"1,required,model.BaseResp" json:"base"`
	UserInfo *model.UserInfo `thrift:"userInfo,2,required" frugal:"2,required,model.UserInfo" json:"userInfo"`
}

func NewLoginResp() *LoginResp {
	return &LoginResp{}
}

func (p *LoginResp) InitDefault() {
}

var LoginResp_Base_DEFAULT *model.BaseResp

func (p *LoginResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return LoginResp_Base_DEFAULT
	}
	return p.Base
}

var LoginResp_UserInfo_DEFAULT *model.UserInfo

func (p *LoginResp) GetUserInfo() (v *model.UserInfo) {
	if !p.IsSetUserInfo() {
		return LoginResp_UserInfo_DEFAULT
	}
	return p.UserInfo
}
func (p *LoginResp) SetBase(val *model.BaseResp) {
	p.Base = val
}
func (p *LoginResp) SetUserInfo(val *model.UserInfo) {
	p.UserInfo = val
}

func (p *LoginResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *LoginResp) IsSetUserInfo() bool {
	return p.UserInfo != nil
}

func (p *LoginResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginResp(%+v)", *p)
}

var fieldIDToName_LoginResp = map[int16]string{
	1: "base",
	2: "userInfo",
}

type AddAddressReq struct {
	Province string `thrift:"province,1,required" frugal:"1,required,string" json:"province"`
	City     string `thrift:"city,2,required" frugal:"2,required,string" json:"city"`
	Detail   string `thrift:"detail,3,required" frugal:"3,required,string" json:"detail"`
}

func NewAddAddressReq() *AddAddressReq {
	return &AddAddressReq{}
}

func (p *AddAddressReq) InitDefault() {
}

func (p *AddAddressReq) GetProvince() (v string) {
	return p.Province
}

func (p *AddAddressReq) GetCity() (v string) {
	return p.City
}

func (p *AddAddressReq) GetDetail() (v string) {
	return p.Detail
}
func (p *AddAddressReq) SetProvince(val string) {
	p.Province = val
}
func (p *AddAddressReq) SetCity(val string) {
	p.City = val
}
func (p *AddAddressReq) SetDetail(val string) {
	p.Detail = val
}

func (p *AddAddressReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddAddressReq(%+v)", *p)
}

var fieldIDToName_AddAddressReq = map[int16]string{
	1: "province",
	2: "city",
	3: "detail",
}

type AddAddressResp struct {
	Base      *model.BaseResp `thrift:"base,1,required" frugal:"1,required,model.BaseResp" json:"base"`
	AddressId int64           `thrift:"addressId,2,required" frugal:"2,required,i64" json:"addressId"`
}

func NewAddAddressResp() *AddAddressResp {
	return &AddAddressResp{}
}

func (p *AddAddressResp) InitDefault() {
}

var AddAddressResp_Base_DEFAULT *model.BaseResp

func (p *AddAddressResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return AddAddressResp_Base_DEFAULT
	}
	return p.Base
}

func (p *AddAddressResp) GetAddressId() (v int64) {
	return p.AddressId
}
func (p *AddAddressResp) SetBase(val *model.BaseResp) {
	p.Base = val
}
func (p *AddAddressResp) SetAddressId(val int64) {
	p.AddressId = val
}

func (p *AddAddressResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *AddAddressResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddAddressResp(%+v)", *p)
}

var fieldIDToName_AddAddressResp = map[int16]string{
	1: "base",
	2: "addressId",
}

type GetAddressReq struct {
}

func NewGetAddressReq() *GetAddressReq {
	return &GetAddressReq{}
}

func (p *GetAddressReq) InitDefault() {
}

func (p *GetAddressReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetAddressReq(%+v)", *p)
}

var fieldIDToName_GetAddressReq = map[int16]string{}

type GetAddressResp struct {
	Base    *model.BaseResp      `thrift:"base,1,required" frugal:"1,required,model.BaseResp" json:"base"`
	Address []*model.AddressInfo `thrift:"address,2,required" frugal:"2,required,list<model.AddressInfo>" json:"address"`
}

func NewGetAddressResp() *GetAddressResp {
	return &GetAddressResp{}
}

func (p *GetAddressResp) InitDefault() {
}

var GetAddressResp_Base_DEFAULT *model.BaseResp

func (p *GetAddressResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return GetAddressResp_Base_DEFAULT
	}
	return p.Base
}

func (p *GetAddressResp) GetAddress() (v []*model.AddressInfo) {
	return p.Address
}
func (p *GetAddressResp) SetBase(val *model.BaseResp) {
	p.Base = val
}
func (p *GetAddressResp) SetAddress(val []*model.AddressInfo) {
	p.Address = val
}

func (p *GetAddressResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetAddressResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetAddressResp(%+v)", *p)
}

var fieldIDToName_GetAddressResp = map[int16]string{
	1: "base",
	2: "address",
}

type BanUserReq struct {
	UserId int64 `thrift:"userId,1,required" frugal:"1,required,i64" json:"userId"`
}

func NewBanUserReq() *BanUserReq {
	return &BanUserReq{}
}

func (p *BanUserReq) InitDefault() {
}

func (p *BanUserReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *BanUserReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *BanUserReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BanUserReq(%+v)", *p)
}

var fieldIDToName_BanUserReq = map[int16]string{
	1: "userId",
}

type BanUserResp struct {
	Base *model.BaseResp `thrift:"base,1,required" frugal:"1,required,model.BaseResp" json:"base"`
}

func NewBanUserResp() *BanUserResp {
	return &BanUserResp{}
}

func (p *BanUserResp) InitDefault() {
}

var BanUserResp_Base_DEFAULT *model.BaseResp

func (p *BanUserResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return BanUserResp_Base_DEFAULT
	}
	return p.Base
}
func (p *BanUserResp) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *BanUserResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *BanUserResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BanUserResp(%+v)", *p)
}

var fieldIDToName_BanUserResp = map[int16]string{
	1: "base",
}

type UnBanUserReq struct {
	UserId int64 `thrift:"userId,1,required" frugal:"1,required,i64" json:"userId"`
}

func NewUnBanUserReq() *UnBanUserReq {
	return &UnBanUserReq{}
}

func (p *UnBanUserReq) InitDefault() {
}

func (p *UnBanUserReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *UnBanUserReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *UnBanUserReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UnBanUserReq(%+v)", *p)
}

var fieldIDToName_UnBanUserReq = map[int16]string{
	1: "userId",
}

type UnBanUserResp struct {
	Base *model.BaseResp `thrift:"base,1,required" frugal:"1,required,model.BaseResp" json:"base"`
}

func NewUnBanUserResp() *UnBanUserResp {
	return &UnBanUserResp{}
}

func (p *UnBanUserResp) InitDefault() {
}

var UnBanUserResp_Base_DEFAULT *model.BaseResp

func (p *UnBanUserResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return UnBanUserResp_Base_DEFAULT
	}
	return p.Base
}
func (p *UnBanUserResp) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *UnBanUserResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *UnBanUserResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UnBanUserResp(%+v)", *p)
}

var fieldIDToName_UnBanUserResp = map[int16]string{
	1: "base",
}

type SetAdminReq struct {
	UserId   int64  `thrift:"userId,1,required" frugal:"1,required,i64" json:"userId"`
	Password string `thrift:"password,2,required" frugal:"2,required,string" json:"password"`
}

func NewSetAdminReq() *SetAdminReq {
	return &SetAdminReq{}
}

func (p *SetAdminReq) InitDefault() {
}

func (p *SetAdminReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *SetAdminReq) GetPassword() (v string) {
	return p.Password
}
func (p *SetAdminReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *SetAdminReq) SetPassword(val string) {
	p.Password = val
}

func (p *SetAdminReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SetAdminReq(%+v)", *p)
}

var fieldIDToName_SetAdminReq = map[int16]string{
	1: "userId",
	2: "password",
}

type SetAdminResp struct {
	Base *model.BaseResp `thrift:"base,1,required" frugal:"1,required,model.BaseResp" json:"base"`
}

func NewSetAdminResp() *SetAdminResp {
	return &SetAdminResp{}
}

func (p *SetAdminResp) InitDefault() {
}

var SetAdminResp_Base_DEFAULT *model.BaseResp

func (p *SetAdminResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return SetAdminResp_Base_DEFAULT
	}
	return p.Base
}
func (p *SetAdminResp) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *SetAdminResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *SetAdminResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SetAdminResp(%+v)", *p)
}

var fieldIDToName_SetAdminResp = map[int16]string{
	1: "base",
}

type GetUserInfoReq struct {
	UserId int64 `thrift:"userId,1,required" frugal:"1,required,i64" json:"userId"`
}

func NewGetUserInfoReq() *GetUserInfoReq {
	return &GetUserInfoReq{}
}

func (p *GetUserInfoReq) InitDefault() {
}

func (p *GetUserInfoReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetUserInfoReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetUserInfoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserInfoReq(%+v)", *p)
}

var fieldIDToName_GetUserInfoReq = map[int16]string{
	1: "userId",
}

type GetUserInfoResp struct {
	Base     *model.BaseResp `thrift:"base,1,required" frugal:"1,required,model.BaseResp" json:"base"`
	UserInfo *model.UserInfo `thrift:"userInfo,2,required" frugal:"2,required,model.UserInfo" json:"userInfo"`
}

func NewGetUserInfoResp() *GetUserInfoResp {
	return &GetUserInfoResp{}
}

func (p *GetUserInfoResp) InitDefault() {
}

var GetUserInfoResp_Base_DEFAULT *model.BaseResp

func (p *GetUserInfoResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return GetUserInfoResp_Base_DEFAULT
	}
	return p.Base
}

var GetUserInfoResp_UserInfo_DEFAULT *model.UserInfo

func (p *GetUserInfoResp) GetUserInfo() (v *model.UserInfo) {
	if !p.IsSetUserInfo() {
		return GetUserInfoResp_UserInfo_DEFAULT
	}
	return p.UserInfo
}
func (p *GetUserInfoResp) SetBase(val *model.BaseResp) {
	p.Base = val
}
func (p *GetUserInfoResp) SetUserInfo(val *model.UserInfo) {
	p.UserInfo = val
}

func (p *GetUserInfoResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetUserInfoResp) IsSetUserInfo() bool {
	return p.UserInfo != nil
}

func (p *GetUserInfoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserInfoResp(%+v)", *p)
}

var fieldIDToName_GetUserInfoResp = map[int16]string{
	1: "base",
	2: "userInfo",
}

type LogoutReq struct {
}

func NewLogoutReq() *LogoutReq {
	return &LogoutReq{}
}

func (p *LogoutReq) InitDefault() {
}

func (p *LogoutReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LogoutReq(%+v)", *p)
}

var fieldIDToName_LogoutReq = map[int16]string{}

type LogoutResp struct {
	Base *model.BaseResp `thrift:"base,1,required" frugal:"1,required,model.BaseResp" json:"base"`
}

func NewLogoutResp() *LogoutResp {
	return &LogoutResp{}
}

func (p *LogoutResp) InitDefault() {
}

var LogoutResp_Base_DEFAULT *model.BaseResp

func (p *LogoutResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return LogoutResp_Base_DEFAULT
	}
	return p.Base
}
func (p *LogoutResp) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *LogoutResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *LogoutResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LogoutResp(%+v)", *p)
}

var fieldIDToName_LogoutResp = map[int16]string{
	1: "base",
}

type SendCodeReq struct {
	Email  string `thrift:"email,1,required" frugal:"1,required,string" json:"email"`
	Action int64  `thrift:"action,2,required" frugal:"2,required,i64" json:"action"`
}

func NewSendCodeReq() *SendCodeReq {
	return &SendCodeReq{}
}

func (p *SendCodeReq) InitDefault() {
}

func (p *SendCodeReq) GetEmail() (v string) {
	return p.Email
}

func (p *SendCodeReq) GetAction() (v int64) {
	return p.Action
}
func (p *SendCodeReq) SetEmail(val string) {
	p.Email = val
}
func (p *SendCodeReq) SetAction(val int64) {
	p.Action = val
}

func (p *SendCodeReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendCodeReq(%+v)", *p)
}

var fieldIDToName_SendCodeReq = map[int16]string{
	1: "email",
	2: "action",
}

type SendCodeResp struct {
	Base *model.BaseResp `thrift:"base,1,required" frugal:"1,required,model.BaseResp" json:"base"`
}

func NewSendCodeResp() *SendCodeResp {
	return &SendCodeResp{}
}

func (p *SendCodeResp) InitDefault() {
}

var SendCodeResp_Base_DEFAULT *model.BaseResp

func (p *SendCodeResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return SendCodeResp_Base_DEFAULT
	}
	return p.Base
}
func (p *SendCodeResp) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *SendCodeResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *SendCodeResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendCodeResp(%+v)", *p)
}

var fieldIDToName_SendCodeResp = map[int16]string{
	1: "base",
}

type ResetPwdReq struct {
	Email    string `thrift:"email,1,required" frugal:"1,required,string" json:"email"`
	Code     string `thrift:"code,2,required" frugal:"2,required,string" json:"code"`
	Password string `thrift:"password,3,required" frugal:"3,required,string" json:"password"`
}

func NewResetPwdReq() *ResetPwdReq {
	return &ResetPwdReq{}
}

func (p *ResetPwdReq) InitDefault() {
}

func (p *ResetPwdReq) GetEmail() (v string) {
	return p.Email
}

func (p *ResetPwdReq) GetCode() (v string) {
	return p.Code
}

func (p *ResetPwdReq) GetPassword() (v string) {
	return p.Password
}
func (p *ResetPwdReq) SetEmail(val string) {
	p.Email = val
}
func (p *ResetPwdReq) SetCode(val string) {
	p.Code = val
}
func (p *ResetPwdReq) SetPassword(val string) {
	p.Password = val
}

func (p *ResetPwdReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ResetPwdReq(%+v)", *p)
}

var fieldIDToName_ResetPwdReq = map[int16]string{
	1: "email",
	2: "code",
	3: "password",
}

type ResetPwdResp struct {
	Base *model.BaseResp `thrift:"base,1,required" frugal:"1,required,model.BaseResp" json:"base"`
}

func NewResetPwdResp() *ResetPwdResp {
	return &ResetPwdResp{}
}

func (p *ResetPwdResp) InitDefault() {
}

var ResetPwdResp_Base_DEFAULT *model.BaseResp

func (p *ResetPwdResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return ResetPwdResp_Base_DEFAULT
	}
	return p.Base
}
func (p *ResetPwdResp) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *ResetPwdResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *ResetPwdResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ResetPwdResp(%+v)", *p)
}

var fieldIDToName_ResetPwdResp = map[int16]string{
	1: "base",
}

type UserService interface {
	Register(ctx context.Context, req *RegisterReq) (r *RegisterResp, err error)

	Login(ctx context.Context, req *LoginReq) (r *LoginResp, err error)

	AddAddress(ctx context.Context, req *AddAddressReq) (r *AddAddressResp, err error)

	GetAddress(ctx context.Context, req *GetAddressReq) (r *GetAddressResp, err error)

	BanUser(ctx context.Context, req *BanUserReq) (r *BanUserResp, err error)

	UnBanUser(ctx context.Context, req *UnBanUserReq) (r *UnBanUserResp, err error)

	SetAdmin(ctx context.Context, req *SetAdminReq) (r *SetAdminResp, err error)

	GetUserInfo(ctx context.Context, req *GetUserInfoReq) (r *GetUserInfoResp, err error)

	Logout(ctx context.Context, req *LogoutReq) (r *LogoutResp, err error)

	SendCode(ctx context.Context, req *SendCodeReq) (r *SendCodeResp, err error)

	ResetPwd(ctx context.Context, req *ResetPwdReq) (r *ResetPwdResp, err error)
}

type UserServiceRegisterArgs struct {
	Req *RegisterReq `thrift:"req,1" frugal:"1,default,RegisterReq" json:"req"`
}

func NewUserServiceRegisterArgs() *UserServiceRegisterArgs {
	return &UserServiceRegisterArgs{}
}

func (p *UserServiceRegisterArgs) InitDefault() {
}

var UserServiceRegisterArgs_Req_DEFAULT *RegisterReq

func (p *UserServiceRegisterArgs) GetReq() (v *RegisterReq) {
	if !p.IsSetReq() {
		return UserServiceRegisterArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceRegisterArgs) SetReq(val *RegisterReq) {
	p.Req = val
}

func (p *UserServiceRegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceRegisterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterArgs(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterArgs = map[int16]string{
	1: "req",
}

type UserServiceRegisterResult struct {
	Success *RegisterResp `thrift:"success,0,optional" frugal:"0,optional,RegisterResp" json:"success,omitempty"`
}

func NewUserServiceRegisterResult() *UserServiceRegisterResult {
	return &UserServiceRegisterResult{}
}

func (p *UserServiceRegisterResult) InitDefault() {
}

var UserServiceRegisterResult_Success_DEFAULT *RegisterResp

func (p *UserServiceRegisterResult) GetSuccess() (v *RegisterResp) {
	if !p.IsSetSuccess() {
		return UserServiceRegisterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*RegisterResp)
}

func (p *UserServiceRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceRegisterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterResult(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterResult = map[int16]string{
	0: "success",
}

type UserServiceLoginArgs struct {
	Req *LoginReq `thrift:"req,1" frugal:"1,default,LoginReq" json:"req"`
}

func NewUserServiceLoginArgs() *UserServiceLoginArgs {
	return &UserServiceLoginArgs{}
}

func (p *UserServiceLoginArgs) InitDefault() {
}

var UserServiceLoginArgs_Req_DEFAULT *LoginReq

func (p *UserServiceLoginArgs) GetReq() (v *LoginReq) {
	if !p.IsSetReq() {
		return UserServiceLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceLoginArgs) SetReq(val *LoginReq) {
	p.Req = val
}

func (p *UserServiceLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginArgs(%+v)", *p)
}

var fieldIDToName_UserServiceLoginArgs = map[int16]string{
	1: "req",
}

type UserServiceLoginResult struct {
	Success *LoginResp `thrift:"success,0,optional" frugal:"0,optional,LoginResp" json:"success,omitempty"`
}

func NewUserServiceLoginResult() *UserServiceLoginResult {
	return &UserServiceLoginResult{}
}

func (p *UserServiceLoginResult) InitDefault() {
}

var UserServiceLoginResult_Success_DEFAULT *LoginResp

func (p *UserServiceLoginResult) GetSuccess() (v *LoginResp) {
	if !p.IsSetSuccess() {
		return UserServiceLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*LoginResp)
}

func (p *UserServiceLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginResult(%+v)", *p)
}

var fieldIDToName_UserServiceLoginResult = map[int16]string{
	0: "success",
}

type UserServiceAddAddressArgs struct {
	Req *AddAddressReq `thrift:"req,1" frugal:"1,default,AddAddressReq" json:"req"`
}

func NewUserServiceAddAddressArgs() *UserServiceAddAddressArgs {
	return &UserServiceAddAddressArgs{}
}

func (p *UserServiceAddAddressArgs) InitDefault() {
}

var UserServiceAddAddressArgs_Req_DEFAULT *AddAddressReq

func (p *UserServiceAddAddressArgs) GetReq() (v *AddAddressReq) {
	if !p.IsSetReq() {
		return UserServiceAddAddressArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceAddAddressArgs) SetReq(val *AddAddressReq) {
	p.Req = val
}

func (p *UserServiceAddAddressArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceAddAddressArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceAddAddressArgs(%+v)", *p)
}

var fieldIDToName_UserServiceAddAddressArgs = map[int16]string{
	1: "req",
}

type UserServiceAddAddressResult struct {
	Success *AddAddressResp `thrift:"success,0,optional" frugal:"0,optional,AddAddressResp" json:"success,omitempty"`
}

func NewUserServiceAddAddressResult() *UserServiceAddAddressResult {
	return &UserServiceAddAddressResult{}
}

func (p *UserServiceAddAddressResult) InitDefault() {
}

var UserServiceAddAddressResult_Success_DEFAULT *AddAddressResp

func (p *UserServiceAddAddressResult) GetSuccess() (v *AddAddressResp) {
	if !p.IsSetSuccess() {
		return UserServiceAddAddressResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceAddAddressResult) SetSuccess(x interface{}) {
	p.Success = x.(*AddAddressResp)
}

func (p *UserServiceAddAddressResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceAddAddressResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceAddAddressResult(%+v)", *p)
}

var fieldIDToName_UserServiceAddAddressResult = map[int16]string{
	0: "success",
}

type UserServiceGetAddressArgs struct {
	Req *GetAddressReq `thrift:"req,1" frugal:"1,default,GetAddressReq" json:"req"`
}

func NewUserServiceGetAddressArgs() *UserServiceGetAddressArgs {
	return &UserServiceGetAddressArgs{}
}

func (p *UserServiceGetAddressArgs) InitDefault() {
}

var UserServiceGetAddressArgs_Req_DEFAULT *GetAddressReq

func (p *UserServiceGetAddressArgs) GetReq() (v *GetAddressReq) {
	if !p.IsSetReq() {
		return UserServiceGetAddressArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetAddressArgs) SetReq(val *GetAddressReq) {
	p.Req = val
}

func (p *UserServiceGetAddressArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetAddressArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetAddressArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetAddressArgs = map[int16]string{
	1: "req",
}

type UserServiceGetAddressResult struct {
	Success *GetAddressResp `thrift:"success,0,optional" frugal:"0,optional,GetAddressResp" json:"success,omitempty"`
}

func NewUserServiceGetAddressResult() *UserServiceGetAddressResult {
	return &UserServiceGetAddressResult{}
}

func (p *UserServiceGetAddressResult) InitDefault() {
}

var UserServiceGetAddressResult_Success_DEFAULT *GetAddressResp

func (p *UserServiceGetAddressResult) GetSuccess() (v *GetAddressResp) {
	if !p.IsSetSuccess() {
		return UserServiceGetAddressResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetAddressResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetAddressResp)
}

func (p *UserServiceGetAddressResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetAddressResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetAddressResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetAddressResult = map[int16]string{
	0: "success",
}

type UserServiceBanUserArgs struct {
	Req *BanUserReq `thrift:"req,1" frugal:"1,default,BanUserReq" json:"req"`
}

func NewUserServiceBanUserArgs() *UserServiceBanUserArgs {
	return &UserServiceBanUserArgs{}
}

func (p *UserServiceBanUserArgs) InitDefault() {
}

var UserServiceBanUserArgs_Req_DEFAULT *BanUserReq

func (p *UserServiceBanUserArgs) GetReq() (v *BanUserReq) {
	if !p.IsSetReq() {
		return UserServiceBanUserArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceBanUserArgs) SetReq(val *BanUserReq) {
	p.Req = val
}

func (p *UserServiceBanUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceBanUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceBanUserArgs(%+v)", *p)
}

var fieldIDToName_UserServiceBanUserArgs = map[int16]string{
	1: "req",
}

type UserServiceBanUserResult struct {
	Success *BanUserResp `thrift:"success,0,optional" frugal:"0,optional,BanUserResp" json:"success,omitempty"`
}

func NewUserServiceBanUserResult() *UserServiceBanUserResult {
	return &UserServiceBanUserResult{}
}

func (p *UserServiceBanUserResult) InitDefault() {
}

var UserServiceBanUserResult_Success_DEFAULT *BanUserResp

func (p *UserServiceBanUserResult) GetSuccess() (v *BanUserResp) {
	if !p.IsSetSuccess() {
		return UserServiceBanUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceBanUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*BanUserResp)
}

func (p *UserServiceBanUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceBanUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceBanUserResult(%+v)", *p)
}

var fieldIDToName_UserServiceBanUserResult = map[int16]string{
	0: "success",
}

type UserServiceUnBanUserArgs struct {
	Req *UnBanUserReq `thrift:"req,1" frugal:"1,default,UnBanUserReq" json:"req"`
}

func NewUserServiceUnBanUserArgs() *UserServiceUnBanUserArgs {
	return &UserServiceUnBanUserArgs{}
}

func (p *UserServiceUnBanUserArgs) InitDefault() {
}

var UserServiceUnBanUserArgs_Req_DEFAULT *UnBanUserReq

func (p *UserServiceUnBanUserArgs) GetReq() (v *UnBanUserReq) {
	if !p.IsSetReq() {
		return UserServiceUnBanUserArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceUnBanUserArgs) SetReq(val *UnBanUserReq) {
	p.Req = val
}

func (p *UserServiceUnBanUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceUnBanUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUnBanUserArgs(%+v)", *p)
}

var fieldIDToName_UserServiceUnBanUserArgs = map[int16]string{
	1: "req",
}

type UserServiceUnBanUserResult struct {
	Success *UnBanUserResp `thrift:"success,0,optional" frugal:"0,optional,UnBanUserResp" json:"success,omitempty"`
}

func NewUserServiceUnBanUserResult() *UserServiceUnBanUserResult {
	return &UserServiceUnBanUserResult{}
}

func (p *UserServiceUnBanUserResult) InitDefault() {
}

var UserServiceUnBanUserResult_Success_DEFAULT *UnBanUserResp

func (p *UserServiceUnBanUserResult) GetSuccess() (v *UnBanUserResp) {
	if !p.IsSetSuccess() {
		return UserServiceUnBanUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceUnBanUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*UnBanUserResp)
}

func (p *UserServiceUnBanUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceUnBanUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUnBanUserResult(%+v)", *p)
}

var fieldIDToName_UserServiceUnBanUserResult = map[int16]string{
	0: "success",
}

type UserServiceSetAdminArgs struct {
	Req *SetAdminReq `thrift:"req,1" frugal:"1,default,SetAdminReq" json:"req"`
}

func NewUserServiceSetAdminArgs() *UserServiceSetAdminArgs {
	return &UserServiceSetAdminArgs{}
}

func (p *UserServiceSetAdminArgs) InitDefault() {
}

var UserServiceSetAdminArgs_Req_DEFAULT *SetAdminReq

func (p *UserServiceSetAdminArgs) GetReq() (v *SetAdminReq) {
	if !p.IsSetReq() {
		return UserServiceSetAdminArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceSetAdminArgs) SetReq(val *SetAdminReq) {
	p.Req = val
}

func (p *UserServiceSetAdminArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceSetAdminArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceSetAdminArgs(%+v)", *p)
}

var fieldIDToName_UserServiceSetAdminArgs = map[int16]string{
	1: "req",
}

type UserServiceSetAdminResult struct {
	Success *SetAdminResp `thrift:"success,0,optional" frugal:"0,optional,SetAdminResp" json:"success,omitempty"`
}

func NewUserServiceSetAdminResult() *UserServiceSetAdminResult {
	return &UserServiceSetAdminResult{}
}

func (p *UserServiceSetAdminResult) InitDefault() {
}

var UserServiceSetAdminResult_Success_DEFAULT *SetAdminResp

func (p *UserServiceSetAdminResult) GetSuccess() (v *SetAdminResp) {
	if !p.IsSetSuccess() {
		return UserServiceSetAdminResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceSetAdminResult) SetSuccess(x interface{}) {
	p.Success = x.(*SetAdminResp)
}

func (p *UserServiceSetAdminResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceSetAdminResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceSetAdminResult(%+v)", *p)
}

var fieldIDToName_UserServiceSetAdminResult = map[int16]string{
	0: "success",
}

type UserServiceGetUserInfoArgs struct {
	Req *GetUserInfoReq `thrift:"req,1" frugal:"1,default,GetUserInfoReq" json:"req"`
}

func NewUserServiceGetUserInfoArgs() *UserServiceGetUserInfoArgs {
	return &UserServiceGetUserInfoArgs{}
}

func (p *UserServiceGetUserInfoArgs) InitDefault() {
}

var UserServiceGetUserInfoArgs_Req_DEFAULT *GetUserInfoReq

func (p *UserServiceGetUserInfoArgs) GetReq() (v *GetUserInfoReq) {
	if !p.IsSetReq() {
		return UserServiceGetUserInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetUserInfoArgs) SetReq(val *GetUserInfoReq) {
	p.Req = val
}

func (p *UserServiceGetUserInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetUserInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserInfoArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserInfoArgs = map[int16]string{
	1: "req",
}

type UserServiceGetUserInfoResult struct {
	Success *GetUserInfoResp `thrift:"success,0,optional" frugal:"0,optional,GetUserInfoResp" json:"success,omitempty"`
}

func NewUserServiceGetUserInfoResult() *UserServiceGetUserInfoResult {
	return &UserServiceGetUserInfoResult{}
}

func (p *UserServiceGetUserInfoResult) InitDefault() {
}

var UserServiceGetUserInfoResult_Success_DEFAULT *GetUserInfoResp

func (p *UserServiceGetUserInfoResult) GetSuccess() (v *GetUserInfoResp) {
	if !p.IsSetSuccess() {
		return UserServiceGetUserInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetUserInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserInfoResp)
}

func (p *UserServiceGetUserInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetUserInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserInfoResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserInfoResult = map[int16]string{
	0: "success",
}

type UserServiceLogoutArgs struct {
	Req *LogoutReq `thrift:"req,1" frugal:"1,default,LogoutReq" json:"req"`
}

func NewUserServiceLogoutArgs() *UserServiceLogoutArgs {
	return &UserServiceLogoutArgs{}
}

func (p *UserServiceLogoutArgs) InitDefault() {
}

var UserServiceLogoutArgs_Req_DEFAULT *LogoutReq

func (p *UserServiceLogoutArgs) GetReq() (v *LogoutReq) {
	if !p.IsSetReq() {
		return UserServiceLogoutArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceLogoutArgs) SetReq(val *LogoutReq) {
	p.Req = val
}

func (p *UserServiceLogoutArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceLogoutArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLogoutArgs(%+v)", *p)
}

var fieldIDToName_UserServiceLogoutArgs = map[int16]string{
	1: "req",
}

type UserServiceLogoutResult struct {
	Success *LogoutResp `thrift:"success,0,optional" frugal:"0,optional,LogoutResp" json:"success,omitempty"`
}

func NewUserServiceLogoutResult() *UserServiceLogoutResult {
	return &UserServiceLogoutResult{}
}

func (p *UserServiceLogoutResult) InitDefault() {
}

var UserServiceLogoutResult_Success_DEFAULT *LogoutResp

func (p *UserServiceLogoutResult) GetSuccess() (v *LogoutResp) {
	if !p.IsSetSuccess() {
		return UserServiceLogoutResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceLogoutResult) SetSuccess(x interface{}) {
	p.Success = x.(*LogoutResp)
}

func (p *UserServiceLogoutResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceLogoutResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLogoutResult(%+v)", *p)
}

var fieldIDToName_UserServiceLogoutResult = map[int16]string{
	0: "success",
}

type UserServiceSendCodeArgs struct {
	Req *SendCodeReq `thrift:"req,1" frugal:"1,default,SendCodeReq" json:"req"`
}

func NewUserServiceSendCodeArgs() *UserServiceSendCodeArgs {
	return &UserServiceSendCodeArgs{}
}

func (p *UserServiceSendCodeArgs) InitDefault() {
}

var UserServiceSendCodeArgs_Req_DEFAULT *SendCodeReq

func (p *UserServiceSendCodeArgs) GetReq() (v *SendCodeReq) {
	if !p.IsSetReq() {
		return UserServiceSendCodeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceSendCodeArgs) SetReq(val *SendCodeReq) {
	p.Req = val
}

func (p *UserServiceSendCodeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceSendCodeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceSendCodeArgs(%+v)", *p)
}

var fieldIDToName_UserServiceSendCodeArgs = map[int16]string{
	1: "req",
}

type UserServiceSendCodeResult struct {
	Success *SendCodeResp `thrift:"success,0,optional" frugal:"0,optional,SendCodeResp" json:"success,omitempty"`
}

func NewUserServiceSendCodeResult() *UserServiceSendCodeResult {
	return &UserServiceSendCodeResult{}
}

func (p *UserServiceSendCodeResult) InitDefault() {
}

var UserServiceSendCodeResult_Success_DEFAULT *SendCodeResp

func (p *UserServiceSendCodeResult) GetSuccess() (v *SendCodeResp) {
	if !p.IsSetSuccess() {
		return UserServiceSendCodeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceSendCodeResult) SetSuccess(x interface{}) {
	p.Success = x.(*SendCodeResp)
}

func (p *UserServiceSendCodeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceSendCodeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceSendCodeResult(%+v)", *p)
}

var fieldIDToName_UserServiceSendCodeResult = map[int16]string{
	0: "success",
}

type UserServiceResetPwdArgs struct {
	Req *ResetPwdReq `thrift:"req,1" frugal:"1,default,ResetPwdReq" json:"req"`
}

func NewUserServiceResetPwdArgs() *UserServiceResetPwdArgs {
	return &UserServiceResetPwdArgs{}
}

func (p *UserServiceResetPwdArgs) InitDefault() {
}

var UserServiceResetPwdArgs_Req_DEFAULT *ResetPwdReq

func (p *UserServiceResetPwdArgs) GetReq() (v *ResetPwdReq) {
	if !p.IsSetReq() {
		return UserServiceResetPwdArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceResetPwdArgs) SetReq(val *ResetPwdReq) {
	p.Req = val
}

func (p *UserServiceResetPwdArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceResetPwdArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceResetPwdArgs(%+v)", *p)
}

var fieldIDToName_UserServiceResetPwdArgs = map[int16]string{
	1: "req",
}

type UserServiceResetPwdResult struct {
	Success *ResetPwdResp `thrift:"success,0,optional" frugal:"0,optional,ResetPwdResp" json:"success,omitempty"`
}

func NewUserServiceResetPwdResult() *UserServiceResetPwdResult {
	return &UserServiceResetPwdResult{}
}

func (p *UserServiceResetPwdResult) InitDefault() {
}

var UserServiceResetPwdResult_Success_DEFAULT *ResetPwdResp

func (p *UserServiceResetPwdResult) GetSuccess() (v *ResetPwdResp) {
	if !p.IsSetSuccess() {
		return UserServiceResetPwdResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceResetPwdResult) SetSuccess(x interface{}) {
	p.Success = x.(*ResetPwdResp)
}

func (p *UserServiceResetPwdResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceResetPwdResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceResetPwdResult(%+v)", *p)
}

var fieldIDToName_UserServiceResetPwdResult = map[int16]string{
	0: "success",
}
