// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package payment

import (
	"MengGoods/kitex_gen/model"
	"context"
	"fmt"
)

type GetPaymentTokenReq struct {
	OrderId       int64  `thrift:"orderId,1" frugal:"1,default,i64" json:"orderId"`
	PaymentMethod string `thrift:"paymentMethod,2" frugal:"2,default,string" json:"paymentMethod"`
}

func NewGetPaymentTokenReq() *GetPaymentTokenReq {
	return &GetPaymentTokenReq{}
}

func (p *GetPaymentTokenReq) InitDefault() {
}

func (p *GetPaymentTokenReq) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *GetPaymentTokenReq) GetPaymentMethod() (v string) {
	return p.PaymentMethod
}
func (p *GetPaymentTokenReq) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *GetPaymentTokenReq) SetPaymentMethod(val string) {
	p.PaymentMethod = val
}

func (p *GetPaymentTokenReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPaymentTokenReq(%+v)", *p)
}

var fieldIDToName_GetPaymentTokenReq = map[int16]string{
	1: "orderId",
	2: "paymentMethod",
}

type GetPaymentTokenResp struct {
	Base         *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
	PaymentToken string          `thrift:"paymentToken,2" frugal:"2,default,string" json:"paymentToken"`
}

func NewGetPaymentTokenResp() *GetPaymentTokenResp {
	return &GetPaymentTokenResp{}
}

func (p *GetPaymentTokenResp) InitDefault() {
}

var GetPaymentTokenResp_Base_DEFAULT *model.BaseResp

func (p *GetPaymentTokenResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return GetPaymentTokenResp_Base_DEFAULT
	}
	return p.Base
}

func (p *GetPaymentTokenResp) GetPaymentToken() (v string) {
	return p.PaymentToken
}
func (p *GetPaymentTokenResp) SetBase(val *model.BaseResp) {
	p.Base = val
}
func (p *GetPaymentTokenResp) SetPaymentToken(val string) {
	p.PaymentToken = val
}

func (p *GetPaymentTokenResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetPaymentTokenResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPaymentTokenResp(%+v)", *p)
}

var fieldIDToName_GetPaymentTokenResp = map[int16]string{
	1: "base",
	2: "paymentToken",
}

type PaymentReq struct {
	OrderId      int64  `thrift:"orderId,1" frugal:"1,default,i64" json:"orderId"`
	PaymentToken string `thrift:"paymentToken,2" frugal:"2,default,string" json:"paymentToken"`
}

func NewPaymentReq() *PaymentReq {
	return &PaymentReq{}
}

func (p *PaymentReq) InitDefault() {
}

func (p *PaymentReq) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *PaymentReq) GetPaymentToken() (v string) {
	return p.PaymentToken
}
func (p *PaymentReq) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *PaymentReq) SetPaymentToken(val string) {
	p.PaymentToken = val
}

func (p *PaymentReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PaymentReq(%+v)", *p)
}

var fieldIDToName_PaymentReq = map[int16]string{
	1: "orderId",
	2: "paymentToken",
}

type PaymentResp struct {
	Base *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
}

func NewPaymentResp() *PaymentResp {
	return &PaymentResp{}
}

func (p *PaymentResp) InitDefault() {
}

var PaymentResp_Base_DEFAULT *model.BaseResp

func (p *PaymentResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return PaymentResp_Base_DEFAULT
	}
	return p.Base
}
func (p *PaymentResp) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *PaymentResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *PaymentResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PaymentResp(%+v)", *p)
}

var fieldIDToName_PaymentResp = map[int16]string{
	1: "base",
}

type GetRefundTokenReq struct {
	OrderId       int64  `thrift:"orderId,1" frugal:"1,default,i64" json:"orderId"`
	PaymentMethod string `thrift:"paymentMethod,2" frugal:"2,default,string" json:"paymentMethod"`
}

func NewGetRefundTokenReq() *GetRefundTokenReq {
	return &GetRefundTokenReq{}
}

func (p *GetRefundTokenReq) InitDefault() {
}

func (p *GetRefundTokenReq) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *GetRefundTokenReq) GetPaymentMethod() (v string) {
	return p.PaymentMethod
}
func (p *GetRefundTokenReq) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *GetRefundTokenReq) SetPaymentMethod(val string) {
	p.PaymentMethod = val
}

func (p *GetRefundTokenReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetRefundTokenReq(%+v)", *p)
}

var fieldIDToName_GetRefundTokenReq = map[int16]string{
	1: "orderId",
	2: "paymentMethod",
}

type GetRefundTokenResp struct {
	Base        *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
	RefundToken string          `thrift:"refundToken,2" frugal:"2,default,string" json:"refundToken"`
}

func NewGetRefundTokenResp() *GetRefundTokenResp {
	return &GetRefundTokenResp{}
}

func (p *GetRefundTokenResp) InitDefault() {
}

var GetRefundTokenResp_Base_DEFAULT *model.BaseResp

func (p *GetRefundTokenResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return GetRefundTokenResp_Base_DEFAULT
	}
	return p.Base
}

func (p *GetRefundTokenResp) GetRefundToken() (v string) {
	return p.RefundToken
}
func (p *GetRefundTokenResp) SetBase(val *model.BaseResp) {
	p.Base = val
}
func (p *GetRefundTokenResp) SetRefundToken(val string) {
	p.RefundToken = val
}

func (p *GetRefundTokenResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetRefundTokenResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetRefundTokenResp(%+v)", *p)
}

var fieldIDToName_GetRefundTokenResp = map[int16]string{
	1: "base",
	2: "refundToken",
}

type RefundReq struct {
	OrderId      int64  `thrift:"orderId,1" frugal:"1,default,i64" json:"orderId"`
	RefundReason string `thrift:"refundReason,2" frugal:"2,default,string" json:"refundReason"`
	RefundToken  string `thrift:"refundToken,3" frugal:"3,default,string" json:"refundToken"`
}

func NewRefundReq() *RefundReq {
	return &RefundReq{}
}

func (p *RefundReq) InitDefault() {
}

func (p *RefundReq) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *RefundReq) GetRefundReason() (v string) {
	return p.RefundReason
}

func (p *RefundReq) GetRefundToken() (v string) {
	return p.RefundToken
}
func (p *RefundReq) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *RefundReq) SetRefundReason(val string) {
	p.RefundReason = val
}
func (p *RefundReq) SetRefundToken(val string) {
	p.RefundToken = val
}

func (p *RefundReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefundReq(%+v)", *p)
}

var fieldIDToName_RefundReq = map[int16]string{
	1: "orderId",
	2: "refundReason",
	3: "refundToken",
}

type RefundResp struct {
	Base *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
}

func NewRefundResp() *RefundResp {
	return &RefundResp{}
}

func (p *RefundResp) InitDefault() {
}

var RefundResp_Base_DEFAULT *model.BaseResp

func (p *RefundResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return RefundResp_Base_DEFAULT
	}
	return p.Base
}
func (p *RefundResp) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *RefundResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *RefundResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefundResp(%+v)", *p)
}

var fieldIDToName_RefundResp = map[int16]string{
	1: "base",
}

type PaymentService interface {
	GetPaymentToken(ctx context.Context, req *GetPaymentTokenReq) (r *GetPaymentTokenResp, err error)

	Payment(ctx context.Context, req *PaymentReq) (r *PaymentResp, err error)

	GetRefundToken(ctx context.Context, req *GetRefundTokenReq) (r *GetRefundTokenResp, err error)

	Refund(ctx context.Context, req *RefundReq) (r *RefundResp, err error)
}

type PaymentServiceGetPaymentTokenArgs struct {
	Req *GetPaymentTokenReq `thrift:"req,1" frugal:"1,default,GetPaymentTokenReq" json:"req"`
}

func NewPaymentServiceGetPaymentTokenArgs() *PaymentServiceGetPaymentTokenArgs {
	return &PaymentServiceGetPaymentTokenArgs{}
}

func (p *PaymentServiceGetPaymentTokenArgs) InitDefault() {
}

var PaymentServiceGetPaymentTokenArgs_Req_DEFAULT *GetPaymentTokenReq

func (p *PaymentServiceGetPaymentTokenArgs) GetReq() (v *GetPaymentTokenReq) {
	if !p.IsSetReq() {
		return PaymentServiceGetPaymentTokenArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PaymentServiceGetPaymentTokenArgs) SetReq(val *GetPaymentTokenReq) {
	p.Req = val
}

func (p *PaymentServiceGetPaymentTokenArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PaymentServiceGetPaymentTokenArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PaymentServiceGetPaymentTokenArgs(%+v)", *p)
}

var fieldIDToName_PaymentServiceGetPaymentTokenArgs = map[int16]string{
	1: "req",
}

type PaymentServiceGetPaymentTokenResult struct {
	Success *GetPaymentTokenResp `thrift:"success,0,optional" frugal:"0,optional,GetPaymentTokenResp" json:"success,omitempty"`
}

func NewPaymentServiceGetPaymentTokenResult() *PaymentServiceGetPaymentTokenResult {
	return &PaymentServiceGetPaymentTokenResult{}
}

func (p *PaymentServiceGetPaymentTokenResult) InitDefault() {
}

var PaymentServiceGetPaymentTokenResult_Success_DEFAULT *GetPaymentTokenResp

func (p *PaymentServiceGetPaymentTokenResult) GetSuccess() (v *GetPaymentTokenResp) {
	if !p.IsSetSuccess() {
		return PaymentServiceGetPaymentTokenResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PaymentServiceGetPaymentTokenResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetPaymentTokenResp)
}

func (p *PaymentServiceGetPaymentTokenResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PaymentServiceGetPaymentTokenResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PaymentServiceGetPaymentTokenResult(%+v)", *p)
}

var fieldIDToName_PaymentServiceGetPaymentTokenResult = map[int16]string{
	0: "success",
}

type PaymentServicePaymentArgs struct {
	Req *PaymentReq `thrift:"req,1" frugal:"1,default,PaymentReq" json:"req"`
}

func NewPaymentServicePaymentArgs() *PaymentServicePaymentArgs {
	return &PaymentServicePaymentArgs{}
}

func (p *PaymentServicePaymentArgs) InitDefault() {
}

var PaymentServicePaymentArgs_Req_DEFAULT *PaymentReq

func (p *PaymentServicePaymentArgs) GetReq() (v *PaymentReq) {
	if !p.IsSetReq() {
		return PaymentServicePaymentArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PaymentServicePaymentArgs) SetReq(val *PaymentReq) {
	p.Req = val
}

func (p *PaymentServicePaymentArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PaymentServicePaymentArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PaymentServicePaymentArgs(%+v)", *p)
}

var fieldIDToName_PaymentServicePaymentArgs = map[int16]string{
	1: "req",
}

type PaymentServicePaymentResult struct {
	Success *PaymentResp `thrift:"success,0,optional" frugal:"0,optional,PaymentResp" json:"success,omitempty"`
}

func NewPaymentServicePaymentResult() *PaymentServicePaymentResult {
	return &PaymentServicePaymentResult{}
}

func (p *PaymentServicePaymentResult) InitDefault() {
}

var PaymentServicePaymentResult_Success_DEFAULT *PaymentResp

func (p *PaymentServicePaymentResult) GetSuccess() (v *PaymentResp) {
	if !p.IsSetSuccess() {
		return PaymentServicePaymentResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PaymentServicePaymentResult) SetSuccess(x interface{}) {
	p.Success = x.(*PaymentResp)
}

func (p *PaymentServicePaymentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PaymentServicePaymentResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PaymentServicePaymentResult(%+v)", *p)
}

var fieldIDToName_PaymentServicePaymentResult = map[int16]string{
	0: "success",
}

type PaymentServiceGetRefundTokenArgs struct {
	Req *GetRefundTokenReq `thrift:"req,1" frugal:"1,default,GetRefundTokenReq" json:"req"`
}

func NewPaymentServiceGetRefundTokenArgs() *PaymentServiceGetRefundTokenArgs {
	return &PaymentServiceGetRefundTokenArgs{}
}

func (p *PaymentServiceGetRefundTokenArgs) InitDefault() {
}

var PaymentServiceGetRefundTokenArgs_Req_DEFAULT *GetRefundTokenReq

func (p *PaymentServiceGetRefundTokenArgs) GetReq() (v *GetRefundTokenReq) {
	if !p.IsSetReq() {
		return PaymentServiceGetRefundTokenArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PaymentServiceGetRefundTokenArgs) SetReq(val *GetRefundTokenReq) {
	p.Req = val
}

func (p *PaymentServiceGetRefundTokenArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PaymentServiceGetRefundTokenArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PaymentServiceGetRefundTokenArgs(%+v)", *p)
}

var fieldIDToName_PaymentServiceGetRefundTokenArgs = map[int16]string{
	1: "req",
}

type PaymentServiceGetRefundTokenResult struct {
	Success *GetRefundTokenResp `thrift:"success,0,optional" frugal:"0,optional,GetRefundTokenResp" json:"success,omitempty"`
}

func NewPaymentServiceGetRefundTokenResult() *PaymentServiceGetRefundTokenResult {
	return &PaymentServiceGetRefundTokenResult{}
}

func (p *PaymentServiceGetRefundTokenResult) InitDefault() {
}

var PaymentServiceGetRefundTokenResult_Success_DEFAULT *GetRefundTokenResp

func (p *PaymentServiceGetRefundTokenResult) GetSuccess() (v *GetRefundTokenResp) {
	if !p.IsSetSuccess() {
		return PaymentServiceGetRefundTokenResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PaymentServiceGetRefundTokenResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetRefundTokenResp)
}

func (p *PaymentServiceGetRefundTokenResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PaymentServiceGetRefundTokenResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PaymentServiceGetRefundTokenResult(%+v)", *p)
}

var fieldIDToName_PaymentServiceGetRefundTokenResult = map[int16]string{
	0: "success",
}

type PaymentServiceRefundArgs struct {
	Req *RefundReq `thrift:"req,1" frugal:"1,default,RefundReq" json:"req"`
}

func NewPaymentServiceRefundArgs() *PaymentServiceRefundArgs {
	return &PaymentServiceRefundArgs{}
}

func (p *PaymentServiceRefundArgs) InitDefault() {
}

var PaymentServiceRefundArgs_Req_DEFAULT *RefundReq

func (p *PaymentServiceRefundArgs) GetReq() (v *RefundReq) {
	if !p.IsSetReq() {
		return PaymentServiceRefundArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PaymentServiceRefundArgs) SetReq(val *RefundReq) {
	p.Req = val
}

func (p *PaymentServiceRefundArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PaymentServiceRefundArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PaymentServiceRefundArgs(%+v)", *p)
}

var fieldIDToName_PaymentServiceRefundArgs = map[int16]string{
	1: "req",
}

type PaymentServiceRefundResult struct {
	Success *RefundResp `thrift:"success,0,optional" frugal:"0,optional,RefundResp" json:"success,omitempty"`
}

func NewPaymentServiceRefundResult() *PaymentServiceRefundResult {
	return &PaymentServiceRefundResult{}
}

func (p *PaymentServiceRefundResult) InitDefault() {
}

var PaymentServiceRefundResult_Success_DEFAULT *RefundResp

func (p *PaymentServiceRefundResult) GetSuccess() (v *RefundResp) {
	if !p.IsSetSuccess() {
		return PaymentServiceRefundResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PaymentServiceRefundResult) SetSuccess(x interface{}) {
	p.Success = x.(*RefundResp)
}

func (p *PaymentServiceRefundResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PaymentServiceRefundResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PaymentServiceRefundResult(%+v)", *p)
}

var fieldIDToName_PaymentServiceRefundResult = map[int16]string{
	0: "success",
}
